### ISSUE TITLE
Command for open direct a kit preview to a player

### ISSUE THREAD

**Issue by xion87** [Zrips/CMI#1063]
I see this thing is missing, a command to open a gui to another player  or preview it direct, like:
**/kitpreview kitname
/kitpreview kitname playername**

It would be awesome to add it

**Comment by LogGits** [comment]
Cmi has a `-preview` tag. You can use it like this "/cmi kit [kitname] -preview" or specify a player if needed. This is kind of a hidden feature because its used backend. However I do think it would be cool to set this up as a default alias for `/kitpreview [kitname] (playername)` (an optional playername argument.

**Comment by CloudeLecaw** [comment]
>           i already know that but i want open direct a specific kit PREVIEW without give to him the  kit

/cmi kit [kitName] [playerNamer] -preview also works from console ;)
