### ISSUE TITLE
Players inventory bugs

### ISSUE THREAD

**Issue by x1p** [Zrips/CMI#1073]
**Description of issue or feature request:**
Sometimes items disappear from inventory while holding in right hand when staff takes something out of a players inventory.

Situation1:
Player is holding something in his right hand
Staff is taking something out of his inventory, changes position or whatever.
Player sees his hand go down and up for a moment
Change of loosing the items which were held by the player
Staff looks in inventory. Confirms that stuff is really gone.

Situation 2 (probably related):
Player1 want to place (put down) a shulker box
Another player2 walks by and stands still right on that spot.
Player1 can't place the shulker. Shulker disappears from inventory leaving empty slot.
Staff looks in inventory: still sees shulker. Changes position, and back again.
Player1 sees his shulker again.

Conclusion: changes in inventory triggers right hand to go down and up with bugs of loosing or hiding of items

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
no config involved I think
```

---

**Cmi Version (using`/cmi version`):** 
8.0.23.0
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper version git-Paper-447

**Comment by mercurialmusic** [comment]
I don't think Situation 2 is related -- and I'm guessing there probably isn't a "fix" -- this sounds like a visual glitch on the client-side, where the client thinks the shulker has been placed, but because of latency between client and server it takes the client a minute to realize the shulker is still in the inventory. This is a vanilla thing that has always been an issue on servers.

**Comment by Zrips** [comment]
This should have been resolved with latest builds.
