### ISSUE TITLE
Things not working

### ISSUE THREAD

**Issue by thomasdaley2** [Zrips/CMI#1104]
**Description of issue or feature request:**

Flight Charge, GUI not working
Save inventory at death, Not working

**Cmi Version (using`/cmi version`):** 
8.0.1.*

**Server Type (Spigot/Paperspigot/etc):** 
Spigot

**Server Version (using `/ver`):** 
1.13.1

**Relevant plugins (Delete if this isn't needed):** 

Grief Prevention
Bottled XP
ShopGUI
Players hopeful
Worldedit
Worldguard
Crates plus

**Comment by LogGits** [comment]
First things first, please upgrade to 1.13.2. 1.13.1 has a fair number of issues. Also your version of cmi is outdated try the latest `8.2.0.2`. If you still have these issues please let me know 👍

**Comment by thomasdaley2** [comment]
8.2.0.2 was causing other issues (teleport, home, back didn't work)

Otherwise I would be using  the latest version. Looks like an update is on the cards (need to check the rest of my plugins if they are ready to upgrade)

**Comment by LogGits** [comment]
Wait what issues with teleporting? This was supposed to be fixed in `8.2.0.2` following a minor bug in the code of `8.2.0.1`. I would also assume all of your plugins would work on 1.13.2, just make sure to update any broken ones 🙂

**Comment by thomasdaley2** [comment]
For me back, dback, to, home all broke with 8.2.0.1 and 8.2.0.2 didn't help me. Downgraded to 8.0.* something to get everything working.

I'll look to see everything is ready for an update. Thanks.

**Comment by LogGits** [comment]
If you don't mind me asking, could you provide me some more info? What exactly broke? Is the /back /home etc teleport between worlds? Are there any errors in console or messages sent to you ingame? If possible can you also send me a screenshot of a home location that is broken.

In addition, just want some further information because "GUI not working" is a broad statement as we have many gui's. Which gui? what isn't working (e.g. does it not open?)

What is wrong with flight charge?

We need more info to fix things.

**Comment by LogGits** [comment]
That internal error was fixed in `8.2.0.2`. If you still get errors with it send me back the exact error you get.
