### ISSUE TITLE
[bug/request] cmi fixchunk fix

### ISSUE THREAD

**Issue by kassadGLA** [Zrips/CMI#1130]
bug: `cmi fixchunk fix` not work.

The need to use this command arose when an unexpected power failure occurred. At this moment, the FILL process was running on the server using the WorldBorder plugin (generating all chunks within the border). After that, when the player approached the damaged chunk, the server crashed.
The sequence of my actions:

1. On the server 0 players. All commands were entered into the console.
2.

`cmi fixchunk w w` (world name = `w`)
`cmi fixchunk autospeed false`
`cmi fixchunk speed 100`

3. After ~2 hours (~3000000 chunks). Result:
>
[03:12:11 INFO]: Scanning finished, use /cmi fixchunk fix to fix found issues. Chunks will be regenerated!
[03:12:11 INFO]: Checking from 1/10 from total of 18152
[03:12:11 INFO]: 1. X:-508 Z:-832
[03:12:11 INFO]: 2. X:-508 Z:-831
[03:12:11 INFO]: 3. X:-508 Z:-829
[03:12:11 INFO]: 4. X:-508 Z:-826
[03:12:11 INFO]: 5. X:-507 Z:-832
[03:12:11 INFO]: 6. X:-507 Z:-831
[03:12:11 INFO]: 7. X:-507 Z:-830
[03:12:11 INFO]: 8. X:-507 Z:-828
[03:12:11 INFO]: 9. X:-507 Z:-825
[03:12:11 INFO]: 10. X:-506 Z:-832
`>cmi fixchunk fix`
>
Result: `fixed chunks 0`

Addition information:
In the process of scanning in the console, there were many messages like `"chunk X Z is incorrectly located. Relocating..."`

All damaged chunks remained damaged. The problem is not solved. The server continued to crash when I approached the damaged chunks.

-----

Feature request: Make a standalone FixChunk utility that does not require starting a server.

-----

**Cmi Version - all** (I tried 3 latest)

**Server Type: Spigot and CraftBukkit** (I tried both)

**Server Version 1.13.2 latest build**

-----

Best regards

**Comment by Zrips** [comment]
I will need actual region file from your world folder which contains atleast one broken chunk to test out whats going on exactly.

**Comment by user127001** [comment]
I no longer have a damaged world. But I will try to reproduce the same situation.

**Comment by user127001** [comment]
Hello!
I successfully reproduced the same situation.
The sequence of my actions:

1. I started the `fill` process using `WorldBorder` plugin and after a while I incorrectly shut down the server using the task manager.
2. I started the server again and connected to it. Then I made sure that when I tried to move to the damaged chunk, the server would crash.
3. I have started the `cmi fixchunk` process. At the end of the process, I connected to the server. The server immediately crushed because I was in a damaged chunk (crush log attached).

World folder and all logs [here](https://drive.google.com/drive/folders/1mbRohmnE-6DXCPYc1oLQcD2o72AZ-NPC?usp=sharing)

Best regards.

**Comment by nazgool97** [comment]
![изображение_2021-04-28_143043](https://user-images.githubusercontent.com/83346984/116396664-500e2b80-a82e-11eb-8655-805e8aa34a63.png)
I can not do it!
when i write the command: fixchunk all
writes this error 
varsion server: paper 1.16.5
cmi version: 8.8.3.6

**Comment by kassadGLA** [comment]
I doubt the relevance of this bug. I reported this in December 2018.
