### ISSUE TITLE
PAPI rank placeholders always green, can't set color code

### ISSUE THREAD

**Issue by AsaAlv** [Zrips/CMI#1184]
**Description of issue:**
Placeholders (papi) cmi_user_rank and cmi_user_nextranks are always green. It should be able to set color code. Also not possible to set bold text.

**Cmi Version:** 
CMI8.0.20.0

**Server Type:** 
Spigot

**Server Version:** 
1.13.1

**Relevant plugins:** 
PlaceholderAPI

**Comment by Zrips** [comment]
Because those placeholders return rank display name which could contain color codes in itself. So update your ranks.yml file and remove any color codes from those ranks so you could manually set them where you need. 
And would recommend to update to 1.13.2 version as that one contains quite few minecraft bug fixes. Doesn't really have anything to do with CMI, simply a recommendation.

**Comment by AsaAlv** [comment]
Thanks for the quick reply, totally missed to look there. My bad. and yes I will of course update right away.
