### ISSUE TITLE
Holograms deleted on server crash

### ISSUE THREAD

**Issue by OpalMoonstride** [Zrips/CMI#1236]
Holograms are saved at server restart, but any holograms created between a restart, and a crash, are not saved. 

CMI plugin version: 8.3.0.0
Server version: Paper("684bd2ad") 1.13.2-R0.1-SNAPSHOT
Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}(CMIEInjector)

**Comment by Zrips** [comment]
It takes up to 30sec to save new holograms. There is delay for a reasson, as we have to avoid constant writes into file if you are actively editing holograms or you even have multiple people doing that. But yea, there was issue for forced save is not being done on server restart/shutdown if its in a line. Will be fixed with next build.

**Comment by OpalMoonstride** [comment]
If you're worried about writing to files, do it asynchronously. This is not that kind of problem. It just needs to save on creation, and edit. You could even do a /hologram save, if you want to make sure it's not checking per tick. 

I spent 4 hours writing holograms. I downloaded the file, when I was done, because I make backups of files which I change. I did not realize it did not write to the file, unless the server is restarted. The server crashed. I log back in, and both the file I downloaded, and the file on the server, had none of the 4 hours of work I had done. This is not a 30 second wait issue. There were not multiple people writing to the file. I am the only person writing holograms.
