### ISSUE TITLE
Feature Request: /cmi recipe (show custom recipes)

### ISSUE THREAD

**Issue by LucidusMC** [Zrips/CMI#1245]
I think this is the opposite of the other recipe requests, I would love to allow my players to see custom recipes from other plugins if possible.

**Comment by pinkpig3777** [comment]
Just worth noting, /CMI CustomRecipe supports NBT tags meaning you could transfer your recipes from other plugins over to the CMI one. That'd be much easier for the developer to create a GUI for to view all of the recipes I would think **[Please Add This Feature Zrips!]**. Otherwise I believe he'd have to add support for each plugin individually, and with all the custom recipes/item plugins out there, that'd take a very very long time. But I could be wrong.

Here's an example of using /CMI CustomRecipe:
    Say you use MythicMobs & MythicArtifacts. You could create a custom item, use a /mm give command to give yourself that custom item, put the desired item recipe ingredients in your inventory, type "/cmi customrecipe", then create a new recipe by putting in the recipe ingredients & putting that custom item into the crafting slot. Works like a charm. 👍

**Comment by Zrips** [comment]
There is no way in separating custom recipe from plugin A with generic vanilla recipe. There is no real indication which one was added by plugin and which one is prebuilt one. At best what we could do is to show all recipes.
