### ISSUE TITLE
[Suggestion] /cmi tree with worldguard region support.

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#1321]
Hi there,

It is pretty awesome to give a player or group access to build with a bit more tree control in their base, however, it would be nice if we had the option to get worldguard region support. This way they can only do so in their own base, not grief that of others, or place it in __global__

Would this perhaps be possible?

Thank you for considering.

**Comment by Zrips** [comment]
I did looked into this some time ago, but... API which allows in creation of trees doesnt really doing it in correct way. What i mean that generic method doesnt fire event with appropriate data so that plugins responsible for tree growing outside protected lands would be intruding into protected one. Will look again, maybe i can make some work around for it, but its not a priority at this point.
