### ISSUE TITLE
FeatureRequest: BalTop exclude permission

### ISSUE THREAD

**Issue by xXJustXx** [Zrips/CMI#1414]
**Description of issue or feature request:**
It would be very cool to be able to exlucde players from beeing shown in the baltop list instead of adding the usernames to the current list. The current way takes a way more time and if you (for example) promote a player to admin he'll be automatically excluded

**Comment by Zrips** [comment]
Checking by permission is not something i would want to add. because you can have thousands of entries, and to check each player for specific permission node even when they are offline, is overkill for server to handle. It would be simpler for me to add permission handling, but that would literally kill servers performance.
