### ISSUE TITLE
Add options to patrol

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#149]
Could you add config options to the patrol command and maybe a GUI? Could tie it into the vanish GUI.

**Comment by Zrips** [comment]
What config options? And how would patrol be tied to vanish?

**Comment by CypherPhyre** [comment]
Currently, the only mention of patrol is in the local .yml files. I would like to see options to 1) adjust how often a player can be patroled. 2) how long a player can be patroled for. 3) an option to auto patrol after x m, h. 4) option to auto vanish when patrolling, 5) add a button to the vanish GUI to start/stop auto patrol. Lastly an option to exempt players from being patroled ie, other staff.

**Comment by LogGits** [comment]
I cant see this getting added. The first suggestion could be done by using cooldowns for the /cmi patrol command. The second suggestion is unnecessary because a staff member should know when to stop looking. Auto patrol is not something that we would like to look into at the moment, as you can see there are quiet a few feature requests. Auto vanish with patrol is a good idea 👍We currently use the permission node: `cmi.command.patrol.bypass` to remove players from the /patrol list.

Closing this issue, however, in the future, we may come back to this 🙂
