### ISSUE TITLE
[Request] Is it possible to deny /back on spesific command

### ISSUE THREAD

**Issue by Baktus79** [Zrips/CMI#1541]
**Description of issue or feature request:**

---
I just got the KickFromClaim plugin again after it was updated to 1.13.x. I use GriefPrevention to manage the player claims, and KickFromClaim is a neat way to kick players out of their claim if they wont behave. 

But then I noticed that the players can just use /back to get back. 

Is there a way to banish plugins or commands to be registered as TP in CMI? If not, is there a possibility to get this feature?

**Comment by Zrips** [comment]
Its really depends on teleport cause. In general we cant know which plugin initialized teleport action, we can only know who in general initialized this teleport action and in most situations in will be PLUGIN which means that we cant exclude plugin teleportations as this would exclude CMI teleportations itself. So in general GP should prevent player teleportation into that area instead of CMI avoiding to record back location when some 3rd party plugin kick him out of it

**Comment by Baktus79** [comment]
Yeah, true. Thanks for the answer :D I'll look into it
