### ISSUE TITLE
CMI Commands causing TPS drop

### ISSUE THREAD

**Issue by Dgretty** [Zrips/CMI#1650]
When using some commands such as /cmi rt server tps drops down to about 4.
I have turned timings on, ran the command and this is what it shows.

https://timings.spigotmc.org/?url=etukenuvil

![Screenshot_1](https://user-images.githubusercontent.com/50040810/56845717-4554e080-687a-11e9-9de9-f5c8512be691.png)

####################
####################

**Cmi Version 8.6.0.1** 

**Spigot:** 

**Spigot-1.14** 

**CMI,mcMMO,PermissionsEX**

**Comment by Zrips** [comment]
If you have map which is not pre generated, then this command could cause some lag spikes as server has to generate chunks in random places when we are looking for valid location. Will have a look and maybe i can optimize it little bit, but in general 1.14 is quite broken now and map generation has few major issues which should be fixed in near future

**Comment by Zrips** [comment]
next update will have optimized methods for this feature which should make it instant without causing unneeded load on server.
