### ISSUE TITLE
Plugin does not save slots — /cmi maxplayers

### ISSUE THREAD

**Issue by Roper89** [Zrips/CMI#1685]
Why the plugin does **not save** installed slots through the command **/cmi maxplayers** ?
The command works, but after a reboot, **MultiCraft** resets the slots by default.

Can you force the **/cmi maxplayers** command to execute automatically after the server is loaded?

**Comment by Zrips** [comment]
This can be issue with 1.14 update which is still waiting a fix as we had some API changes in newest version which no longer allowed some changes to be done to server files, atleast not with old methods. Will try to fix this one with todays update.

**Comment by Roper89** [comment]
@Zrips The problem is still not solved.
After rebooting, MultiCraft resets the number of slots.

**Comment by mrfloris** [comment]
Sorry for sounding mean, but .. 

Is this not CMI doing what it's supposed to do and then MultiCraft forcing an amount of slots overriding what CMI has done?

DId it work with multicraft in 1.13.2 but stopped working in 1.14.1 perhaps? Just trying to understand it a bit better.

**Comment by the456gamer** [comment]
What roper wants is for cmi to set the slots after the plugin loads persistently

But I believe the intended use case is to temporarily increase maxplayers without rebooting,    otherwise you just modify it manually.

This in particular sounds like it's being used to try to bypass a forced playerlimit that resets on server restart
