### ISSUE TITLE
Warn on Teleport

### ISSUE THREAD

**Issue by LucidusMC** [Zrips/CMI#1805]
**Description of issue or feature request:**
```
Anytime a player teleports or warps using CMI, WarpSystem, Multiverse, etc.
```
---
**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/mhF8GvqU
```
---
```
CMI plugin version: 8.6.3.1
Server version: Paper(624) 1.13.2-R0.1-SNAPSHOT
Vault version: 1.7.2-b107

Plugins (62): Multiverse-Core (3.0.0-SNAPSHOT-b761), WarpSystem(4.0.6)
```

**Comment by Zrips** [comment]
This error is from player death event handling. First of all this should not get triggered while you simply teleporting around, so that one is a red flag that you have some broken plugin doing nasty things. Second, tested it out on same exact paper version, all works as intended and no error while teleporting with warps or respawning. This will be issue with compatibility with another plugin, without knowing which one exactly causes this and why, i cant really address it, i can only hide this error message.
