### ISSUE TITLE
Can't damage mobs or take damage from mobs.

### ISSUE THREAD

**Issue by pvpKingdoms** [Zrips/CMI#1884]
CMI is blocking the damage dealt to mobs and the damage taken from mobs. Found this via WorldGuard debug.
---

CMI Version 6.4.0

PaperSpigot

PaperSpigot build 624

WorldGuard/CMI

**Comment by 0xC1A551C** [comment]
Post the debug. I do not have this issue, and seems to be a issue with your server.

**Comment by pvpKingdoms** [comment]
![image](https://user-images.githubusercontent.com/42253494/58834669-cc7b3e00-8608-11e9-87e0-76a90898a559.png)

**Comment by 0xC1A551C** [comment]
Try disabling CMI to see if the issue goes away @pvpKingdoms 

I don't have this issue.

There is this seciton in the config that could affect this.

`# All posible damage causes: contact, entity_attack, entity_sweep_attack, projectile, suffocation, fall, fire, fire_tick, melting, lava, drowning, block_explosion, entity_explosion, void, lightning, suicide, starvation, poison, magic, wither, falling_block, thorns, dragon_breath, custom, fly_into_wall, hot_floor, cramming, dryout, 
# Syntax should be [permissionNode]:[damageCause]:[multiplier]
# Example: nolavadamage:lava:0 will prevent lava damage with cmi.damagecontrol.nolavadamage permission node
# Negative values will heal player instead of damaging him
# If player have more than one permission node for same damage cause, then last one in list will be used to determine final damage
DamageControl:
- nowalldamage:fly_into_wall:0
- lowermagmacubedamage:hot_floor:0.5`

**Comment by pvpKingdoms** [comment]
Disabling CMI does remove the issue. I'm not sure how that config could cause the effect but I will try messing around with it and seeing what happens.

**Comment by AcesGamingUK** [comment]
i also have this issue, 
pinpointed the issue to CMI, 
ive no idea how to fix it
