### ISSUE TITLE
Time related issues in CMI

### ISSUE THREAD

**Issue by Flexxxxx** [Zrips/CMI#2036]
**Description of issue:** /seen <playname> while someone is offline returns an insane time since last played time. Generally 100+ days despite them only being offline for moments or hours. I have never once seen an accurate /seen time, apart from time online. Another thing /cplaytime is recording inaccurate times too; recently players have been playing for hours, but it's only recording minutes.

---

**CMI Version:** 8.6.5.4 BungeeCord -> 8.6.7.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot (git-paper-121)
 
**Server Version (using `/ver`):** 1.14.3

**Comment by Zrips** [comment]
Recording of last played time could be skipped of a record if player has NPC meta data attached to it, which should only exist on fake players and not real ones. It could be caused by some NPC plugin. At this point cant reproduce this issue, playtime is recorded correctly and last offline timer is shown correctly. If issue persists, let me know and check if you have some NPC plugin which could be causing this issue.
