### ISSUE TITLE
cuff , Seriously copying bugs , Need to fix it right away

### ISSUE THREAD

**Issue by p82183645** [Zrips/CMI#2068]
see this video
https://www.dropbox.com/s/83t8gdq2aiqwns2/20190716_181042.mp4?dl=0

1. cuff player true
2. cuff player false
3. if player After the above two steps , the bug happen

He can use unlimited three-fork to copy infinitely

**Cmi Version (using`/cmi version`):**  8.6.7.3

**Server Type (Spigot/Paperspigot/etc):** paper 

**Server Version (using `/ver`):** 1.13.2

**Comment by Zrips** [comment]
test this without any other plugin but only CMI, as i cant reproduce this one and it looks like you have something or some plugin trying to pick up item which should not be possible, because when cuffed player tries to pickup item, that item gets pick up delay which should prevent its pickup for next 6 seconds.
