### ISSUE TITLE
CMI CUSTOM_PAYLOAD packets spam on join that it kicks players

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#2089]
I have the issue that players who join an empty server get kicked due to packet spam. After some debugging with protocolLib, I concluded that this was caused by CMI CUSTOM_PAYLOAD packages.

When one player joins it sends packets to everyone online in the server. In my case, it's over 1000 packets that are being sent resulting in kicking the player who was already online. ProtocolLib debug looks like this when that happens: [https://pastebin.com/PCLr9gW8](https://pastebin.com/PCLr9gW8)

I've reported this issue before but we fixed it ourself by blocking the custom_payload package coming from CMI. Would love a permanent fix in CMI itself tho since it's long overdue.

**Used versions**
CMI 8.6.7.5 (Happens on earlier versions as well)
Tested on paperspigot 1.8 and 1.12 and 1.13 (Servers are connected to Bungeecord)
Only protocollib and viaversion (viarewind on 1.12/1.13) are used.

**Comment by Zrips** [comment]
New version should contain some optimizations to address this issue. Thanks for reporting and providing quite useful debug log.

**Comment by xion87** [comment]
the issue is still here, why you are still sending bungee packets CMIPlayerInfochannels messages over all server? also if i don't use any bungee features, that will cause a lot of packet flood if any cmi server with a lot of player  (like 300-1000 extra packets per second)causing issues like the one reported
i have a small debug here
![unknown](https://user-images.githubusercontent.com/3611852/62792986-c6a24d00-bad0-11e9-98dc-f363b8f1206e.png)

**Comment by xion87** [comment]
i just seee now a update that andress this issue finally!
