### ISSUE TITLE
Deleting /mail with on screen [X] misleading

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#2130]
Let's say that I have 5 Messages...

1. Hey whats up! [X]
2. Hi! [X]
3. built the home for you [X]
4. havent seen you in ages! [X]
5. this server is great [X]

If I delete messages 5, 3, & 1, in that order, all works fine.

If I delete messages 1, 3 & 5 in that order, things go wacky.

* Message 1 Gets Deleted
* Message 4 Gets Deleted

That's it. When I delete message 1, Message 2 moves up to Message 1 spot. Message 3 Moves up to Message 2 spot. Thus, Message 4 gets deleted, which is now in position 3. Message 5 is ignored because it is now in position 3.

**HOW TO FIX:**

Have a unique id that each message is associated with and delete based on the uniqueid. That is probably the best implementation.

The lazy method would be to force a refresh of the mail list the player is viewing after they delete a message.

**Comment by ColaIan** [comment]
actually I don't prefer having unique ids, I think having a time code instead of time order before the message would be better

**Comment by digitalcrowd** [comment]
They can still show up as 1, 2, 3 etc on the list, but a unique ID behind the scenes is the only way to ensure you delete the right message from a programming perspective. A time code may not always be unique.

**Comment by x1p** [comment]
I have to agree that it's illogical. Hope this gets a solution

**Comment by Zrips** [comment]
With next update this will be fixed. It was the issue because they have been stored as simple list and mail got removed by its order place id, so in general you could remove entire list by clicking first entry, as it would be id of 0 which would remove first entry in the list each time you click. 
Redone entire handling of mail removal so now its removing by mail object itself, which eliminates requirement to have some specific id's in genaral.
In short: next version -> fix
