### ISSUE TITLE
request: add option to afk config

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/CMI#214]
I have auto afk enabled on my server. It is set as
```
  AutoAfkIn: 300
  AutoKickIn: 900
 # Disables afk on interaction
  DisableOnInteract: true
  # Disables afk on inventory click
  DisableOnInventoryClick: true
  # Disables afk on command usage
  DisableOnCommand: true
  # Disables afk on public chat message
  DisableOnPublicChat: true
  # Disables afk on private chat message
  DisableOnPrivateChat: true
  # Disables afk on move
  DisableOnMove: true
  # Disables item pickup while afk
  DisableItemPickup: true
```

Could you add a way to prevent afk pools? My server only has 15 join slots and I have seen 2 players so far using afk pools to bypass the auto afk. One player was even online for 20 hours

**Comment by MCTyler** [comment]
I have seen that option in the config, It doesn't work?

**Comment by CypherPhyre** [comment]
The problem is with an afk pool. The player is moved in a circle by water so it is detecting the player moving and not triggering afk. If there was a way to detect that kind and have an option to prevent. I don't want to disable the setting Disables afk on move
DisableOnMove: true

**Comment by MCTyler** [comment]
So you want to disable AFK on Move but not Disable AFK on Move? GL ZRips ;).

**Comment by LogGits** [comment]
Difficult to check this. I know it could be possible when checking the direction that they are facing (Yaw and Pitch) and disregard movements entirely. However, this could also pose issues. Regardless, I'm sure that a player who isn't afk and isn't typing in chat or placing blocks, isnt going to be travelling with the same pitch and yaw. Unless they are afk and just holding w and space bar.

`Potential solution is: Checking pitch and yaw changes instead of x/y/z changes.`

**Comment by Zrips** [comment]
Will be implemented with next build.
