### ISSUE TITLE
InGame Editor not work

### ISSUE THREAD

**Issue by Ashdeuzo** [Zrips/CMI#2165]
Hello,

Hologram and IC does not seem to work anymore in game and without error but when i change the config in ic.yml and holograms.yml, all changes work.
But all this features  was working a few days ago, nothing has change since. 
I think the problem come from ingame editing only

holograms.yml : https://pastebin.com/LJDAdqAR
interactiveCommands.yml : https://pastebin.com/7W8RtmUT

**Cmi Version :**  CMI8.6.8.4.jar

**Server Type :** PAPER 152 1.14.1-R0.1-SNAPSHOT

And another problem with KEY : https://pastebin.com/RB9Mms3H

**Comment by ChitterChatter** [comment]
I am using the same CMI Version as Ashdeuzo and my **Server Type** : Spigot version 1.14.4

When I type /hologram  
in game I get nothing. It was working a few days as I did set up some Holograms but now I can't continue.

**Comment by JasperLorelai** [comment]
Same bug. I attempted renaming the original `hologram.yml` file and generated a new one and the problem persisted. It has nothing to do with old configurations.

**Comment by ChitterChatter** [comment]
I also wanted to mention that the kiteditor also isn't working, so that in game editor isn't working either, and it was last week. I have half way through making some kits.  :(

**Comment by Zrips** [comment]
Can't reproduce this one on latest build. If issue persists, try running server with only CMI on it, to rule out posible issue with another plugin. If issue still persists, give me your config file (obfuscate mysql login data) related files, like holograms and exact server version. Och, and use latest 1.14.4 version and not outdated and broken 1.14.1.

**Comment by ChitterChatter** [comment]
I removed everything, still same issue. 
If I do /holograms I get the message "unknown command, type "/help" for help.  If I do /cmi holograms I get the message saying There is no command by this name!
If I do /hologram   I get nothing. If I do /cmi hologram  I get nothing.
If I /kit I get the kits. If I do /cmi kit  I get the kits. 
If I do /kiteditor  I get nothing. If I do /cmi kiteditor  I get nothing.

**Comment by JasperLorelai** [comment]
For me in general all raw messages are not working. Including `/broadcast`, `/checkcommand`, etc. The problem is not present in a fresh instalation of CMI - which is what Zrips said. I'll debug further to see what config property could be causing this.

**Comment by JasperLorelai** [comment]
Okay... what... Whatever is causing the problem doesn't like the `Alias.yml` configuration file. The problem with raw messages is not present on fesh instalations because all values in the file thereof are set to `false`. I could dig deeper to figure out exactly which command alias is causing this @Zrips - if you need me to. I should've while already reporting this issue, but to applying changes in this file requires a full server restart, `/cmi reload` won't do - probably because of Brigadier.

If this is enough information, let me know.

**Comment by JasperLorelai** [comment]
Perhaps this...

[Alias.zip](https://github.com/Zrips/CMI/files/3507628/Alias.zip)

**Comment by ChitterChatter** [comment]
hmm is that a fixed yml?  @JasperLorelai 

I was wondering if it had something to do with the alias's since /kit works, but /kiteditor does not.

**Comment by JasperLorelai** [comment]
I'm waiting for Zrips' response. I'm not sure if this is enough information for him to locate the issue yet. I hope it is.

**Comment by ChitterChatter** [comment]
I had sent Zrips my config file along with the kits, holograms and alias ymls' as well

**Comment by JasperLorelai** [comment]
This is possibly a related issue: https://github.com/Zrips/CMI/issues/2195

**Comment by JasperLorelai** [comment]
Well then... @TheCynicalKitty has some insane patience. He spend 2+ hours going through each command in `Alias.yml` and restarting the server after each one to find out the problem. He DMd me telling me how he had all of them disabled and enabled about 20 aliases so far and everything was fine.

Then I remembered that Zrips recently added the `/cmi tellraw` command. Guess what... by making an alias for it it broke all raw messages coming from CMI because it overwrote the minecraft tellraw command that displayed them.

For the hotfix you can enable any alias you need except `tellraw` until this is fixed. 
```
Alias:
  # /cmi tellraw $1-
  /tellraw: false
```

Or you can make a custom alias instead. Example: `/rawmsg`
```yml
CustomAlias:
  rawmsg:
    Cmds:
    - cmi tellraw $1-
```

**Comment by Zrips** [comment]
Got fixed, now its /cmi ctellraw to avoid this issue
