### ISSUE TITLE
World Removal CMI Retained World Removed

### ISSUE THREAD

**Issue by BearLeonLight** [Zrips/CMI#2256]
```
######################
## REPLACE WITH ERROR ##
######################
```

I removed the world when the server was shut down and showed the following message after startup.
[21:42:05 INFO]:[CMI] could not find a world with (BuildWorld2) name
[21:42:05 INFO]:[CMI] could not find a world with the name (BuildWorld1)
[21:42:05 INFO]:[CMI] could not find a world with (BuildWorld0) name
---

**Cmi Version (CMI8.6.10.0):** 

**Server Type (Paperspigot):** 

**Server Version (1.14.4`):**

**Comment by stashenko** [comment]
Delete everything in config data about the remote world and execute the command /cmi reload

**Comment by Zrips** [comment]
This message appears when you have random teleportations set for no longer existing worlds.

**Comment by mrfloris** [comment]
I really prefer that this data that cmi collects in config.yml doesn't get forcefully removed on world deletion. Because we have themes and events, and these are worlds that return monthly, or seasonal, or like halloween, once a year. Having the data there and don't have to reconfigure and double check 50x, is a huge plus. 

For all the other situations, yeh, getting those msgs that some world is gone, is a bit annoying, but they're an easy fix manually and only needs to be removed once.
