### ISSUE TITLE
Option to organize /list by rank

### ISSUE THREAD

**Issue by Sikatsu** [Zrips/CMI#2258]
Currently when you perform /list the ranks are listed in a random order. Would like to have it organized from highest to lowest ranks.

**Comment by Sikatsu** [comment]
Using all that it still won't show it in order.. weight's are setup correctly and they are being put in the right group aswell.

**Comment by Zrips** [comment]
CMI doesn't get permission group weights from permission plugin, it will only sort by group number itself

**Comment by Sikatsu** [comment]
How would that work to sort the list then?

**Comment by Zrips** [comment]
Give a player appropriate permission node **cmi.command.list.group.1** up to **cmi.command.list.group.10** (you can have more if you need) which description can be found in local file under **list->info->groups** section. So player will get group number of highest value he has access too and this number will be used to place him in the sorted list. So instead of using players permission group and their weight, you can simply give player a permission node and he will be placed in approriate group

**Comment by Sikatsu** [comment]
Alright, this is solved. Thanks for the explanation!
