### ISSUE TITLE
PLEASE REVERT /WE COMPASS /back support!! omg, wWHYYYy

### ISSUE THREAD

**Issue by mrfloris** [Zrips/CMI#2309]
Fix for issue when using WE compass to jump around and back location would be recorded each time you jump

WHY ...

When someone uses compass from worldedit and then /back, they end up on some old previous location and they SHOULD be going to the place where they stood when clicking the compass. 

This completely screws up how we use things in events and survival, and what certain ranks paid for. 

PLease tell me how i can make this work as before without being stuck now on an old version and never upgrade again? O_o

PLEASE revert this..

**Comment by TheoRetisch1** [comment]
I have requested not to set a backpoint for the worldedit navigation tool. Players use /back to teleport back to distinctive points such as their storage or a cave. No one wants to end up a few blocks from their last position. This makes the back function pretty useless.

Before it gets mentioned: The option "BackMinDistance" is only helpful to a limited extent, because the players often use the back function within their structures. For example to teleport from a storage to a farm. After a longer test period it turned out that the players are more fucked up about a distance limitation than about the unpleasant compass port problems.

I don't see how /back should be useful for the compass position in normal survival at all. I only got complaints about it.
If we talk about special events I can understand your problems. However, the case is so specific that it would be more appropriate to ask for a true/false config option rather than a revert.

**Comment by mrfloris** [comment]
Since the upgrade, we've had nothing but complaints from loads of our members :(

There's loads of situations where you are exploring, traveling in survival where you maybe double click on accident and want a step back, and /back then puts you back all the way 10k from where you started. Utter nonsense. 

The compass + /back works the same on every server that uses it, and has been for the last 8+ years.

It sucks for those handful of servers like yours who have a different opinion about it. 

We have servers with hundreds of users, and haven't seen a single one say : finally this is 'fixed', .. instead, we've had a nice evening of having criticism over all the servers where we use we/cmi combos and allow the compass.

This really isn't a fix, this is a ridiculous update because this is how it's been for many years.

**Comment by TheoRetisch1** [comment]
Well, that' s not exactly true. If we're talking about years, most of us have used Essentials and not CMI and EssentialsX doesn't have a back position for the compass port. That's also the reason why players even get the idea that it could be different.

When it comes to player numbers and server size, you definitely have the hat on. And I have to admit that I have never experienced you so upset before xD.

However, for me the above points outweigh the problems with exploration experiences. I would be very sad to lose this "feature" again :(. Therefore I am in favour of the compromise of a config option.

**Comment by mrfloris** [comment]
We used EssentialsX and had it setup the same as we did in CMI. 

I rather it supports both, i checked config.yml, i see no option for we integration or anything compass related (related to jumping and back)

**Comment by TheoRetisch1** [comment]
You see me surprised. Then it didn't work properly for us, I don't know. It is pointless to discuss it. Since I assume that Zrips appreciates your opinion more than mine. I just wanted to use this thread to suggest a config option as an alternative to revert. For my sake, the old behavior may be turned on by default. I would be very sad if I would lose the new feature, no offense.  Have a great day!

**Comment by mrfloris** [comment]
Our opinions are the same, size of playerbase doesn't mean much besides i guess some experience. 

I find this an odd update to cmi, and i hope it gets reverted. 

If it really turns out there's enough people who wish after a teleport they can't go /back to their previous location but like 09239020349 locations before.. then i hope we get a toggle for it in config.yml so we can better manage our servers. 

If zrips doesn't want to make any further changes i want to know and ill find an alternative teleport handler for compass/ cmi jump, and cmi back

**Comment by Zrips** [comment]
Dint know that this small change will cause such a big issue. Will add an option to switch between those two behaviors. Was considering that one from the beginning, but had no clue what someone might actually want that old behavior in place. Anyhow, next version, look for BackWithWE config section. Default behavior will be old one, where we will include compass teleportations into /back

**Comment by mrfloris** [comment]
> You see me surprised. Then it didn't work properly for us, I don't know. It is pointless to discuss it. Since I assume that Zrips appreciates your opinion more than mine. I just wanted to use this thread to suggest a config option as an alternative to a revert. For my sake, the old behavior may be turned on by default. But I would be very sad if I would lose the new feature, no offense. Have a great day!

Hey question, can you DM me on Disocrd or Spigotmc? `floris#0233` / `mrfloris`, all is well, just want to say hi. 

@Zrips 

Thank you! 

Sorry for being eh 'verbal' about this one, i had a bad week with a bad back and came online to many many MANY ppl complaining, and trying to figure out 'now what'.

I really really really appreciate it that you have a solution so swiftly that offers an option to both players.

**Comment by sandwally** [comment]
Did always believe in Zripz and have respect for the work Zripz do.
Fixed an issue I had and others had but it made another issue for another person I got great respect for who is mrfloris who use the plugins potential.
Always expect a middle ground from Zripz and don't rush anything.
