### ISSUE TITLE
[Suggestion] Option to disable using "/cmi"

### ISSUE THREAD

**Issue by ShaneBolenback** [Zrips/CMI#250]
I was looking over this on the plugin page a lot, and I really want to implement this on my server. My BIG issue is, if I use this instead of essentials, all my players have to get used to using "/cmi" infront of all their regular commands, like /spawn, /home, /warp. 
Also, I have a couple Skripts, aliases as well as plugins that run commands, such as /spawn and /warp
I would have to go thru all of those.

So I was hoping, is there a way to add a config option to drop /CMI from most commands?
I know myself and all my players would find it easier to switch over if they dont have to put /cmi infront of all the commands they are currently used to.

Thank you for reading.

**Comment by ShaneBolenback** [comment]
SCRATCH THAT...  I now know about the alias file.... SO we can disregard this. Sorry

**Comment by MCTyler** [comment]
Welcome to CMI, but I thought you said your not gonna buy it?

**Comment by ShaneBolenback** [comment]
Im really not sure where you get that idea?

**Comment by MCTyler** [comment]
Well you used the exact same name on Spigot. Your a shifty fellar aren't you?
![screenshot from 2018-04-11 04-48-35](https://user-images.githubusercontent.com/6390898/38609426-a5d25cf2-3d43-11e8-8887-3e782735915c.png)

**Comment by ShaneBolenback** [comment]
WHAT THE HELL IS WRONG WITH YOU BUD?
MY GOD what is with all the freaks like you?
First of all, its none of your business what I do or do not purchase.
Second, this thread is really not the place for discussing my spigot purchases.
Third, I haven't purchased it yet. When i sent that message to you on spigot, i was not aware of the power of the plugin. So yeah, like i said "Im not spending 15 on a plugin to fix one chunk"
After looking into this plugin further I have decided i really want to get this on my server.
I discussed with with my staff, and one of them has worked on servers that has used it.
BUT AGAIN, it is none of your business what I do.

As for SHIFT?!?! WTF?!?! How does me saying im not going to buy it, and then HOURS later saying I want to buy it... make me shifty? You are on problematic person bud. Grow up, and go harass someone else. 
This thread was not titled "SHOULD I OR SHOULDNT I PURCHASE THIS PLUGIN" So just screw off.

**Comment by ShaneBeee** [comment]
> His answer only showed what?....
> I would say he has not pushchased CMI and now tries to get support for it on GitHub ;)
> so pls go to Blackspigot or where ever u downloaded the leak and ask there for support 🗡
> 
> to fix a borken chunk Need the Player to regen it?.. na u simply Need WorldEdits //regen for example :3...but ok
> and hey to block /cmi u can create a Little alias in the commands.yml ;) ppl with permisison stillcan use cmi:cmi if Need or use the cmi aliases.
> 
> Also i would rate for the admins here to close this issuses, why?
> He said he solved it alone and allready found his answer, and let it open just will end in more "Leakhatter Posts ;) "

Im curious where you get the idea that I'm using a leaked version?
I never once said in this post that I was using it. 
The first line of my post reads "I was looking over this on the plugin page a lot, and I really want to implement this on my server."
All I was doing was asking a simple question before purchasing the plugin. 

Sidenote, I never ended up buying it because I realized how terrible the support is because of people like you. Accusing someone of using a leaked version of a plugin, when in fact, I never once made any implication that I was actually USING the plugin. I was simply asking questions before purchasing. I ended up finding out the answer from one of my admins who has previously used this plugin on a server he worked on before. 

We never once ran this plugin on our server. So again, please show me where you get the implication that I was using it or a leaked version?

**Comment by CloudeLecaw** [comment]
You have beed away a Long time 📦 

So you bought it now? ;)

**Comment by RedEpic** [comment]
meanwhile im using the leaked one for development testing lmao

**Comment by CloudeLecaw** [comment]
> meanwhile im using the leaked one for development testing lmao

we noticed that allredy 📦 

Zrips also learned a lot since he added the feature
The problem with your leaks is they all belong just one account from the license generated on orginal download
and this is where we know what names use them... blacklisted name used license^^


For development or not. its not allowed to use leaks even not for development. And you know this ;)
