### ISSUE TITLE
Home Point remove

### ISSUE THREAD

**Issue by banit** [Zrips/CMI#2544]
If a Player gehts non permanent extra home it will not get deleted when the permission wich gave this home does expire. he cant set new homes but he can use all he allready set. i would not consider this a intended use. Homes should get removed or be unaccessable when the permission granting them expires.

*8.6.16.2* 
Paper 230 .1.14.4*

**Comment by maxlehot1234** [comment]
Paper 1.14.4 build#226

**Comment by Zrips** [comment]
if you have 10 homes and you have access to only 9 of them, which one should get removed? Because i would not have any idea which needs to be removed as any of them could be needed for the player. If player looses access to new home creation, then he will need to remove old ones to create new one. So he can decide which one he doesn't need anymore.
Cant really solve this one without creating more issues for the players.
