### ISSUE TITLE
RPG Bank - CMI balance money dupe Bug

### ISSUE THREAD

**Issue by PuppyNomNom** [Zrips/CMI#2576]
Bug with RPG Bank where you deposit money into your bank, but your balance isn't effected, resulting in a dupe glitch. 

I contacted the RPG Bank Dev, he says it's most likely a bug with CMI and to contact you here.

---

CMI Ver: 8.6.16.4

Paper 1.15

Paper Version git-Paper-8 (MC: 1.15)

RPG Bank: https://www.spigotmc.org/resources/%E2%9C%85must-have%E2%9C%85-rpgbank-store-your-items-exp-and-money-using-villagers-npcs-and-custom-gui.29139/updates

**Comment by LogGits** [comment]
Are you still having this issue? If so, are you using cmi's build of vault? This sounds like an issue on rpgbank's end because CMI's vault is essentially a compilation of vault that allows built in cmi compatibility. For more info see <http://www.zrips.net/wp-content/uploads/2020/07/Vault-1.7.3.jar> (current uptodate version as of 24/11/2020)
