### ISSUE TITLE
[Request] Igonre Permissions option for cutomalias

### ISSUE THREAD

**Issue by TheRobLP** [Zrips/CMI#2713]
**Description of feature/improvement request:**

I think it would be nice if you could have an option for custom commands to ignore permissions.
---
### Detailed explanation of what it should do, when and in what situation: ###

So basically, if you create a alias for a /spawn command, right now you have to give the corresponding permission for that. Id like

### Basic explanation as to why this feature is needed and/or useful to have: ###

Its usefull for example if you want players to be able to use /hub but not /spawn .

**Comment by mercurialmusic** [comment]
I'm probably misunderstanding your request, but you already have the option to not require permissions for aliased commands in CustomAlias.yml. For example:

```
  hub:
    Cmds:
    - cmi spawn
    Perm: false
```

Then in your Alias.yml just make sure you have `/spawn: false`. This would prevent people from using /spawn but allow them to use /hub instead. However, it would not prevent them from using /cmi spawn, since that's a base command that they would need permission for in order to use /hub if you have it aliased to the /cmi spawn command.

All that said, if you're asking to ignore permissions for **base** commands, I think most server admins prefer for plugins not to give permissions by default - myself very much included.

**Comment by Zrips** [comment]
@TheRobLP 
You can make custom alias for any command which by itself uses specialized commands, which means that you can perform command like it was done from console without giving player direct access to core command. You can use some variable like bperm:[value][@][?][#]! so in example 
**bperm:cmi.customperm.anything@?#! cmi spawn**
which means that in case player has cmi.customperm.anything permission node he can perform thi alias which will perform generic spawn command. Or you could use 
**asConsole! cmi spawn [playerName]**
which will perform command from console which will send player who performed command to spawn.

**Comment by TheRobLP** [comment]
Sorry for not responding to it. I am not that often on Github. What I mean is to have the possibility to use the command which is used for the alias as if the player where OP. Example: YOu have a world management plugin and you use /world [world] to teleport to the worlds. But now you dont want a normal player to be allowed to use /world because he can warp to any world then. Instead you want him to use /hub for example to get to this world, which is a customalias with /world hub
