### ISSUE TITLE
[Update Request] Update lfix to version 1.15.2

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#2742]
It would be fantastic if the `lfix` command would work again in version 1.15.2.Currently there is a message that it is not yet supported on the used server version.
In fact, the possibilities to repair light bugs are very limited in version 1.15.2, because FAWE does not offer support either. So it would be pretty cool to use the CMI feature. 

This ticket is partially identical to #2278, but I have opened a new one because the author of the ticket seems to be unable to choose a differentiated heading and description.

**Comment by Zrips** [comment]
Its not supported because Mojang changed entire light rendering mechanic where client does most of the calculations and there is no simple way to force light recalculations. I have spent quite some time trying to figure out new way in forcing this light update which was relatively simple in previous versions, but now its ether imposible or requires quite complex code to trick server and client in forcing light update. 
It quite likely that light fix will no longer be possible, dont quote me on this tho.

**Comment by TheoRetisch1** [comment]
Uff that's bad news, some team members are afraid of the dark. Thanks for your commitment and the detailed information!

**Comment by TheoRetisch1** [comment]
The lighting issue has become quite complex and there is now a good solution for it: Most people use the Cleanlight plugin, which is based on an external library. It's definitely not a little extra feature anymore and I don't think it's worth to continue integrating this bug vulnerable feature into CMI. CMI has a lot more potential in other areas for which the time should be invested in. I am satisfied with the feature rich external solution and will close the feature request.
