### ISSUE TITLE
some lag

### ISSUE THREAD

**Issue by arts7493** [Zrips/CMI#2803]
**Description of issue:**

timings

	
CMI::Combined Totalcount(947)  total(3.16% 1.016s, 4.28% of tick)avg(1.07ms per - 2.14ms/1.99 per tick)
CMI::Command: CMI:cmicount(39)  total(2.84% 0.913s, 3.85% of tick)avg(23.41ms per - 1.92ms/0.08 per tick)
CMI::Task: com.Zrips.CMI.AllListeners.PlayerListeners$6 (Single)count(2)  total(0.15% 0.047s, 0.20% of tick)avg(23.72ms per - 0.10ms/0.00 per tick)
CMI::Task: com.Zrips.CMI.Modules.CmdWarmUp.WarmUpManager$1 (Single)count(5)  total(0.14% 0.043s, 0.18% of tick)avg(8.69ms per - 0.09ms/0.01 per tick

and other error

https://pastebin.com/x3d9UhBC

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.19.3
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1.15.2-r0.1-snapshot paper(105)
**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
For second error, should be fixed with next update.
For original "lag". You need to check what command was performed after command warmup. As this is only 2 instances of this method being performed, yet you have some heavy calculations. Will make some changes related to this, should improve some performance, if this will not help out, let me know with some extra information, especially on a command which was performed at that time.
