### ISSUE TITLE
Auto Config Updater

### ISSUE THREAD

**Issue by Insprill** [Zrips/CMI#2831]
**Description of feature/improvement request:**
Whenever there is something new added to any of the files, CMI should automatically add those lines.
---
### Detailed explanation of what it should do, when and in what situation: ###
Whenever there is something new added to any of the files, CMI should automatically add those lines. But also have an option (at the top of the config) to turn this off so it doesn't break things before testing them. The config i have is from like a year or two ago and there are alot of things im missing but it would take hours to put my settings in the new one on 7 servers. 

### Basic explanation as to why this feature is needed and/or useful to have: ###
People are missing out on a lot of features and it would take so long to move over old settings because the config (i have) is 2,159 lines.

**Comment by Zrips** [comment]
All files are updated with new things in them. Every new configuration option will be added automatically on first run. And we need to have default values in any case, so having the option for not updating file with new entries is quite pointless. You could only encounter issue where you have old entry with already existing text and new update has new and improved line which doesnt really get updated because you already have it. But this in general is not a big issue as changes like this usually are not crucial for plugin work, if they are, then i will force update those lines to new ones, which happened couple times now.
