### ISSUE TITLE
Some item-related features not working in 1.8

### ISSUE THREAD

**Issue by Zenya4** [Zrips/CMI#2841]
I'm having a few issues running CMI on a PaperSpigot 1.8.8 server, whereby a few item-related features are not working as intended

---

1. Typing "[item]" in chat is supposed to display item data, but it does not work as intended and shows as "Invalid item" when the cursor is hovered across it

2. `ICON` placeholder in holograms are not working as intended. I have already followed the instructions in https://www.spigotmc.org/wiki/cmi-holograms/ but the item displays as a blank line

3. `/hat` command does not correctly display items above the player's head as intended. It only works for blocks and not items
 
All of the above features work correctly when the same version of CMI is used on a 1.15.2 server, but not on 1.8.8
---

**Cmi Version (using`/cmi version`):**: CMI: 8.6.19.5-> 8.6.19.6

**Server Type (Spigot/Paperspigot/etc):**: PaperSpigot

**Server Version (using `/ver`):**: This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Zrips** [comment]
Keeping backwards compatibility is getting somewhat complicated, after all, 1.8.8 is 5 year old version and there was quite a few changes done for entire Minecraft code and handling for particular things, especially related to materials.  
1. Will be fixed
2. https://www.zrips.net/cmi/holograms/ floating icons are only for 1.10 and above due to how they are being handled by minecraft servers. 
3. /hat only places items into the appropriate slot in your inventory, it's not handling visualization itself
