### ISSUE TITLE
cmi.anvil.nolimits not working

### ISSUE THREAD

**Issue by thecenters** [Zrips/CMI#2846]
Players have cmi.anvil.nolimits as permission, but they still get "too expensive" messages in the anvil.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.6.19.5

**Server Type (Spigot/Paperspigot/etc):** 
Paper 1.15.2

**Server Version (using `/ver`):** 
git-Paper-66
![Screen_Shot_2020-02-21_at_12 27 49_PM](https://user-images.githubusercontent.com/1264853/75495800-4f50df80-5974-11ea-97e0-ff6f161b6972.png)

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
![image](https://user-images.githubusercontent.com/10416201/76512492-6eb03800-645d-11ea-8ab4-adde2bcba8d1.png)
As of testing, it does seam to be working correctly. Try checking permission access with **/cmi haspermission cmi.anvil.nolimits [playerName]**

**Comment by Isaiah-labs** [comment]
Cmi Version (using/cmi version):
8.7.8.2

Server Type (Spigot/Paperspigot/etc):
Paper 1.16.3

Server Version (using /ver):
git-Paper-215

This seems to be an issue on my server as well right now, I didn't want to submit a new bug report since this one is still open. Players do have access to cmi.anvil.nolimits as well as cmi.anvil just to be sure.

**Comment by Zrips** [comment]
This feature got removed due to possible issues which in general can create more inconveniences and it would resolve.
