### ISSUE TITLE
Command Costs

### ISSUE THREAD

**Issue by Aeyori** [Zrips/CMI#2863]
**Description of issue or feature request:**
Is there a way to add economy costs to commands?
EX: whenever a player gets tped it costs them money
not just when they type /tpa or /tpaccept because they haven't been tped yet
---

**Cmi Version (using`/cmi version`):** 
8.6.19.7
**Server Type (Spigot/Paperspigot/etc):** 
Paper
**Server Version (using `/ver`):** 
Paper-65 (MC: 1.15.2)

**Comment by Zrips** [comment]
There is no straight forward method, but you can achieve that by disabling /tpaccept alias in alias.yml then creating custom alias with something like 
**/cmi aliaseditor new tpaccept-moneycost:123?! cmi tpaccept**
which will mean that player has to pay 123 and because you have **?** it will inform player about missing money if he doesn't have enough.
