### ISSUE TITLE
The maxplayer feature is volatile

### ISSUE THREAD

**Issue by TheoRetisch1** [Zrips/CMI#3004]
An increased number of slots during runtime will always be reset to the value specified in the settings as soon as a player joins. 

Procedure: /maxplayers XY -> number of slots increases -> one player joins -> the number of slots decreases again

There are no errors in the log.
All players have the cmi.fullserver.bypass permission.

Paper 1.13.2 - 655
CMI version 8.6.20.9

**Comment by Zrips** [comment]
Tested on 1.13.2 paper version, all works as intended. You will need to test out if this is not caused by another plugin or by some incorrect CMI setup where you would perform maxplayers command on player login. As this is only one place where it can change maxplayer count and without performing it maxplayer count will not change.

**Comment by TheoRetisch1** [comment]
You're right, that was a mistake. Thanks for responding :)
