### ISSUE TITLE
"/mirror" block destroy does not work for non op-ped players.

### ISSUE THREAD

**Issue by BboyZeroOne** [Zrips/CMI#3045]
**Description of issue:**
"/mirror" command does not work when non-OP players tries to destroy mirrored blocks.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
Whenever players execute /mirror, this console message appears.

05.04 01:31:53 [Server] INFO ZJLee issued server command: /mirror
05.04 01:31:55 [Server] INFO Unknown command. Type "/help" for help.

**Cmi Version (using`/cmi version`):** 
8.6.21.2

**Server Type (Spigot/Paperspigot/etc):** 
Paper(83) 1.15.2-R0.1-SNAPSHOT

**Server Version (using `/ver`):** 
Paper version git-Paper-83 (MC:1.15.2)

**Comment by Zrips** [comment]
Players who cant build in area will not be allowed to break blocks in there. This might be due to some anticheat plugin blocking block break event checks as they are not in line of player sight which can be counted in as invalid action. Can really resolve this one from my end, as we need to fire some fake block break events before you attempt to replace them to avoid from players breaking blocks in some ones protected land.

**Comment by BboyZeroOne** [comment]
This is my NCP config from mcmarket. I've tried to disable block-break related anticheat checks but still does not work, can you help me take a look and disable the related ones for me. It would be greatly appreciated, thanks! 

https://pastebin.com/5RqfXiSS
