### ISSUE TITLE
Custom recipes and NBT-tags

### ISSUE THREAD

**Issue by DawrFromUa** [Zrips/CMI#3117]
**Description of issue:**
Hello. I made a recipe for players. This recipe was consist of 3 totems (with another names and lore) for making a sword with NBT-tags.

But players were tried place 3 clean totems and they made a sword with NBT-tags. How to make checking for having NBT in items of the recipe?

Ver. CMI: 8.6.19.3-> 8.6.22.1
Ser.Ver. Paper(137) 1.15.2-R0.1-SNAPSHOT

**Comment by OverBrave** [comment]
Yes, this is a very critical problem. I have the same problem and I cannot make special items. Even if I put the items with a special name later, when I save them later, their names appear to be gone in the menu.

@Zrips Can you fix it?

**Comment by mrfloris** [comment]
It's not a problem, it's not a bug, it's actually not a feature. 

The output should work fine with custom item. But the input what you put in the custom furnace melting or the custom recipe crafting, that's what only takes a single item and the raw material.

I do hope as a feature request this is going to get implemented in the future, because I see this question pop up weekly on the zrips discord. 

If it's too complex or something for the main cmi plugin, maybe a recipeLibrary.jar could be downloaded when we enable this plugin, so we can extend cmi with a custom recipe crafting/smelting feature?
