### ISSUE TITLE
/ignore doesn't actually ignore the messages

### ISSUE THREAD

**Issue by Xiri99** [Zrips/CMI#3245]
**Description of issue:** 
Whenever someone /ignore a player, they can still see them typing in chat.

I'm using Towny(chat) as well, is this fully compatible with /ignore?

---

**Cmi Version (using`/cmi version`):** 8.6.24.0

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 

**Server Version (using `/ver`):** 1.15.2 (Paper-185)

**Relevant plugins (Delete if this isn't needed):** Towny / Townychat

**Comment by LogGits** [comment]
This is related to TownyChat's recipients implementation. 
https://github.com/TownyAdvanced/TownyChat/blob/master/src/com/palmergames/bukkit/TownyChat/channels/StandardChannel.java#L140-L141

They are removing the existing recipients (which we remove the ignored player) and then creating a new one. 

You need to contact the townyChat devs asking them to resolve this (ideally they should use the  `getRecipients()` instead of `getOnlinePlayers()` as getRecipients should by default have all online players)
