### ISSUE TITLE
Actionbar problem of customjoinmessage

### ISSUE THREAD

**Issue by OverBrave** [Zrips/CMI#3251]
**Description of issue:**
![image](https://user-images.githubusercontent.com/47111280/81060607-7e874e00-8edb-11ea-873e-d2089c9a8d77.png)

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
`  LoginCustom: '!actionbar! &e&l(!) &d%vault_prefix%%player_displayname% &asunucuya katıldı!'`

**Cmi Version (using`/cmi version`):**  
![image](https://user-images.githubusercontent.com/47111280/81060678-9c54b300-8edb-11ea-9a61-9ba6334d895c.png)

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):**  
![image](https://user-images.githubusercontent.com/47111280/81060699-a70f4800-8edb-11ea-9c94-97f144857575.png)

**Comment by mrfloris** [comment]
Confirmed.

Comments at the top of locale implies we can use `!actionbar!`, adding it to the join message and relog, it shows as plaintext to just that user, other users do not see the join msg anymore.

spigot 1.15.2 and 8.6.24.1

<img width="712" alt="Screenshot 2020-05-05 at 15 22 59" src="https://user-images.githubusercontent.com/28841349/81071096-7ed81700-8ee4-11ea-8007-10cfb3de4067.png">

**Comment by Zrips** [comment]
@mrfloris 
Well i will have to poke at one attention to the details. Comments does say that things like this work in some places, but... Just above !toast! line you have something like "# **Some** lines supports option to send them to custom places, like action bar, title, sub title or even create JSON/clickable messages" which indicates that not all of them will work due to how they are being handled. In this case we have join message which is not been sent by CMI but rather modified during player login event and rest of it is left for server to be handled by.

**Comment by Zrips** [comment]
Next version
