### ISSUE TITLE
Issue with shulkerbox shift-click in duel

### ISSUE THREAD

**Issue by AerWyn81** [Zrips/CMI#3268]
**Description of issue:**

Hi, When a player is in combat and tries to open the shulkerbox, it refuses, fine. When the duel is over, the player can no longer re-open his shulkerbox and must disconnect to re-open it. When the player re-opens the shulkerbox, all the contents has disappeared

[Opened issue here](https://github.com/Realizedd/Duels/issues/33)

**Cmi Version (using`/cmi version`):** 
8.6.24.1
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
259 latest

**Comment by CloudeLecaw** [comment]
you mean the shulerbox is empty then? Uff you know that CMI does not manage shulkerboxes?
The just give the option to use it like a backpack

**Comment by AerWyn81** [comment]
We don't have other plugin that manage shulkerboxes. 
Ah, forgot to said something. Players dueling is managed by the plugin Duels (github provided in first message).

**Comment by CloudeLecaw** [comment]
But belive me CMI does not mange any content of shulerboxes.
The content of shulkerboxes if mages by your plugins or the serve it self.

so something is clearing your shulkers.  have your tried if this issues also appears when CMI is not loaded? i would test this first because normaly CMI has no Shulkerbox management

**Comment by AerWyn81** [comment]
Okey, after some testing with only CMI/Duels plugins, i think this is an issue with Duels who not restore properly the stuff in shulker after duels. Sorry for inconvenience.
