### ISSUE TITLE
Permissions | In square brackets

### ISSUE THREAD

**Issue by CyreX12** [Zrips/CMI#3311]
**Question: **

Hi, can you help me with this? What do I need to write in square brackets to apply to all?? In permissions. Example:  cmi.teleport.with.[entitytype] |  Valid for all entities.
OR
cmi.command.ride.[entitytype] | Valid for all entitiytipe
Thx:)

**Comment by CloudeLecaw** [comment]
Normaly you never should write in chat or elsewhere with [] or {}  because mostly these are used for placeholders. if the placeholder does not exists then its empty

About the Permission
u missunderstood the description:
cmi.command.ride.[entitytype]   the [Name] is standing for the thing in side
so [entitytype] mean u have to write in an entiry
if your permissionplugin accept * permissions then you can setup
cmi.command.ride.*  for all or for single once the real single permission
examples:

[you have to check for Entityname here:](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html)

some examples:
cmi.command.ride.donkey
cmi.command.ride.horse

so if your see aggain a permissin where inside something is written in square brackets then you know you have to define it (without square brackts!)

**Comment by CyreX12** [comment]
> Normaly you never should write with [] or {} because mostly these are used for placeholders. if the placeholder does not exists then its empty
> 
> **About the Permission**
> u missunderstood the description:
> **cmi.command.ride.[entitytype]** -> the **[Name]** is standing for the thing in side []
> so **[entitytype]** mean u have to **write in an entityname** after the dot.
> if your permissionplugin accept _-ermissions then you can also give **cmi.command.ride.**_
> for all possible entitynames. Else just give single entitiynames for single entities.
> [you need to check for Entitynames here:](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html)
> 
> **some examples for cmi.command.ride.[entitytype]**
> 
> * cmi.command.ride.*
> * cmi.command.ride.donkey
> * cmi.command.ride.zombie_horse
> * cmi.command.ride.horse
> * cmi.command.ride.player
> 
> I hope u understand now how to use [Namethings]
> So if your see aggain a permission where inside something is written in square brackets then you know you have to define it (without square brackts!)

tx

**Comment by CyreX12** [comment]
Thx:D
