### ISSUE TITLE
Compability with GadgetsMenu

### ISSUE THREAD

**Issue by therealatsuga** [Zrips/CMI#3509]
Hi. We are using GadgetsMenu for donator Perks. If a staff member is in vanish the player can still see the particles from GadgetsMenu. 

https://www.spigotmc.org/resources/gadgetsmenu-1-8-1-15-premium.62831/
---
It would be great if /v would also remove the particles from GadgetsMenu and "give them back" on unvanishing. 

Well, it's just convenient if the staff member forgets to disable the particle effects before vanishing.

**Comment by CloudeLecaw** [comment]
you may know cmi does nothing wrong here

Hedjetmenü has more problems like this, like that you see same particals in all worlds at the same kords even if there is no player... xD

You should go to gadjets menü plugin dev here asnd ask for Vanish compability.

This really would make more sense because CMI use a normal viansh methode like other plugins does too

**Comment by Zrips** [comment]
This should be handled by GadgetsMenu plugin and CMI cant do anything about this and in general should not. Players are vanished in generic method and GadgetsMenu dev can use bukkit API to check if he needs to show those particles or not. And in case he is not even using packets, then you have plugin which will never be compatible with vanish state. Anyways, not CMI issue to fix.
