### ISSUE TITLE
Auto-Prefix in language config

### ISSUE THREAD

**Issue by MaxWainer** [Zrips/CMI#3530]
**Description of feature/improvement request:**
Little feature which auto-prefix all messages in language.yml.
---
### Detailed explanation of what it should do, when and in what situation: ###
In CMI so many commands and so many messages. And add to all '!prefix!' tag very tired and eat some precious part of time which could be spent on setting up more important and time-consuming plugins.
### Basic explanation as to why this feature is needed and/or useful to have: ###
Time saving.

P.S Sorry if I didn't fully reveal the essence. :/

**Comment by CloudeLecaw** [comment]
The current solution is fine. If you had an automatic prefix thus would avoid more serverowners that dont want any kind of prefixes in their usermeassages and stuffmassages. Sothe current way is a fair deal. The owner can decide what language outputs use the prefix by Design it in the langfile. A fair deal. I know the langfile is long but it wont get shorter anymore since cmi is getting more and more Features over the time. This is a normal behave of essential plugins
