### ISSUE TITLE
ParseOther PlaceHolders with CMI

### ISSUE THREAD

**Issue by thomaboehi** [Zrips/CMI#3533]
**Description of issue:**
When I do the command:
/cmi placeholders parse %parseother_{Ange_32}_{cmi_user_meta_statut}%

It looks like CMI doesn't know that parseother exists and returnes me this:
(_considering my status is: TestWAXIE and Ange_32's one is: TestANGE_32_)

**%TestWAXIE%** 
(_exactly this, with the percentage signs_)

So it returns my status, and not Ange_32's one.

```
**Cmi Version (using`/cmi version`):** 
8.6.27.2

**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Server Version (using `/ver`):** 
1.15.2

**Comment by CloudeLecaw** [comment]
Praseothers is a plugin? Then you should consider writing a request to tge dev of this plugin. Usually cmi can hook to all plaveholders of the placeholder api. But its not fair to wanted a plugin ti accept all placeholderss in the world of all plugins

**Comment by thomaboehi** [comment]
Parseother isn't a plugin. It is an extension for Papi.

I don't like you. My bug report is for Zrips, you're always here to comment, but wrongly. Can you please go there: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#parseother

and come back when you'll be able to comment


"_But its not fair to wanted a plugin ti accept all placeholderss in the world of all plugins_" man -.- are you the Robin Hood of CMI ?

**Comment by thomaboehi** [comment]
Oh I was searching this:

Mind your own business 😄 I think that's what we say

**Comment by the456gamer** [comment]
The usage of the cmi placeholders command is
`placeholders (parse) (placeholder) (playerName)`
So have you tried `/cmi placeholders parse %cmi_user_meta_statut% Ange_32`

Source: [Here](https://www.zrips.net/cmi/commands/)

**Comment by CloudeLecaw** [comment]
Have you tested that the Placeholders are working elesewhere? may this is moer a request for Placeholder API

**Comment by thomaboehi** [comment]
Omg... I quite.

I'd love to speak french with you to explain why your suggestions are not helpful. If I want to use the ParseOther Extension, it's because I need it, not just for fun.

So don't tell me to do /cmi placeholders parse %cmi_user_meta_status% Ange_32 if it's not what I need.

My problem:

I created a CustomAlias for my player, so they can show the Status of another player.
For example:

/status Ange_32

should send back Ange_32's status. That's why I need ParseOther.

Because actually when they write this commands, it sends back their own status.

It will be the last time I explain this, because it's not that difficult to understand.

`
  me:
    Cmds:
    - asConsole! cmi usermeta [playerName] add statut $1-
    - 'asConsole! cmi msg [playerName] !&6Status: &7%cmi_user_meta_status%'
    Perm: true
  status:
    Cmds:
    - 'asConsole! cmi msg [playerName] !&eUsage: &6/status &f[playername]'
    - 'asConsole! cmi msg [playerName] !&6Status of $1: &7%parseother_{$1}_{cmi_user_meta_statut}%'
`

**Comment by CloudeLecaw** [comment]
1, your using $1 what means your status command needs a command argument
so status command
 is doing the following:
example:
your typing /status;
 'asConsole! cmi msg [playerName] !&eUsage: &6/status &f[playername]'
the console with send you the meassge "Uageage: /status thomaboehi
Note if your doing this then you get the how to use meassge aggain.. but ok
now you know how to use it and type: **/status thomaboehi**
 'asConsole! cmi msg [playerName] !&6Status of $1: &7%parseother_{$1}_{cmi_user_meta_statut}%'
the console now interprets this as
 'asConsole! cmi msg [playerName] !&6Status of thomaboeh: &7%parseother_{thomaboeh}_{cmi_user_meta_statut}%'
im sure that %parseother_{thomaboeh}_{cmi_user_meta_statut}%  is no vailed placeholder for CMI because this is not working like this!

**Comment by thomaboehi** [comment]
That what you should have say from the begining 

Thank my lovely friend
