### ISSUE TITLE
Warp create Fee

### ISSUE THREAD

**Issue by mark-sheremeta** [Zrips/CMI#3579]
**Description of feature/improvement request:**
The ability to add a fee for creating a warp

**Comment by mercurialmusic** [comment]
You can kind of do this already by using a [custom alias](https://www.zrips.net/cmi/commands/custom-alias/) with [specialized commands](https://www.zrips.net/cmi/commands/specialized/) that handle the fee. It's not a perfect solution since in order to create the warp in the first place they would need the permission (which would also then allow them to set the warp normally) but if you disable the default `/setwarp` alias in Alias.yml (so that they'd have to use `/cmi setwarp` in order to get around the fee, which is effective if they're not aware of that) then set the alias you want along with the specialized commands in the CustomAlias.yml. Setting that warp creation alias to something other than `/setwarp` might further throw them off the scent. 

This is such an edge case otherwise that it seems unlikely to be added. Fair number of security issues giving regular players access to warp admin commands. Keep in mind this will still open the warp GUI for them upon creation. If you do implement I'd highly recommend using the limitation of the number each user can create: cmi.command.setwarp.[anypositivenumber].

**Comment by CloudeLecaw** [comment]
Your wrong. You dont need to give them the permission to it. You also can define a command to be executed in the customalais as opband with the moneycost to be executed. If you execute a command as op the play does not need the permission
