### ISSUE TITLE
Color codes on items in player inventories from pre-1.16.1 include weird symbols.

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#3617]
**Description of issue:**
Having some strange behavior in items inside player inventories from pre-1.16.1 that were named using either `/cmi itemname`, `/cmi itemlore`, or through the `/cmi give` commands causing strange symbols to appear in place of where color codes would have been previously hidden. It does not seem to affect items in chests that were created using the same and it does not seem to affect items that were named on an anvil using color codes. Very possibly a Spigot error but thought I'd put it here just in case. 

Potentially relevant: this was on a test world that I _did not_ use the `--forceUpgrade` tag on before opening. This was just a test server for plugin testing and world generation.

Using the CMI commands in 1.16.1 to rename the items **works as expected**, but I'd love to not have to rename all the items for everyone on my server!

Items in player inventory created using CMI:
![weird_item_symbols](https://user-images.githubusercontent.com/21208123/86154132-a60c2880-bad0-11ea-98aa-2621dace3935.png)

Items in chests created using CMI:
![items_in_chests](https://user-images.githubusercontent.com/21208123/86155312-3dbe4680-bad2-11ea-8cfc-95bb23406e40.png)

---

**Cmi Version (using`/cmi version`):**  8.7.0.3 SqLite-> 8.7.0.5

**Server Type (Spigot/Paperspigot/etc):** Spigot

**Server Version (using `/ver`):** git-Spigot-0287a20-2fe6b4a (MC: 1.16.1)

**Comment by Zrips** [comment]
CMI dint included anything special in items int pre 1.16 version, which means that there is issue with conversion between versions. In pre 1.16 version basic §e color codes have been added, as it was done for countless years by now. Nothing special about it in any shape or form. Due to new hex color support there might have been issue during conversion, which is not directly related to CMI as any item created by any other plugin which contained color codes should have resulted into same exact issue.
