### ISSUE TITLE
Allow using key names in /cmi enchant

### ISSUE THREAD

**Issue by Auxilor** [Zrips/CMI#3681]
I have a custom enchantments plugin, EcoEnchants, however the names for some enchantments are multiple words. Because of this, I can't enchant items with those enchantments. One-word enchantments do work but longer ones do not. So, to fix this, could either enchantment aliases be customisable or could enchanting with key names be added? (eg minecraft:fragility_curse instead of Curse of Fragility)

**Comment by Auxilor** [comment]
Still not fixed?

**Comment by Zrips** [comment]
Have you tried to simply use one word instead of multiple ones? I mean /cmi enchant CurseofFragility or even /cmi enchant Curse_of_Fragility
FYI Its not a bug from CMI end, its more like compatibility issue with custom enchants, even tho they should work without any issues if one worded enchants worked for you then there is no reason for enchants with multiple words to work if you provide that name in one word format

**Comment by Auxilor** [comment]
Have tried, doesn't work.
Assuming you're doing Enchantment.getByName(name), and the actual registered names have spaces in them
You could also add the option to use Enchantment.getByKey(NamespacedKey.minecraft(name)) which would solve this problem

**Comment by Auxilor** [comment]
The custom enchantments are registered in the minecraft namespace (for compatibility) so this would work

**Comment by LegendaryJay** [comment]
This makes me sad :(

**Comment by Zrips** [comment]
@Auxilor 
Will make some changes to have enchant recognition on a higher level as i noticed that i could improve on that in any case, so win win situation here. Test it and let me know if you will still have issues with next build.
