### ISSUE TITLE
CMI ERROR

### ISSUE THREAD

**Issue by wallace329** [Zrips/CMI#3682]
**Description of issue or feature request:**
Type /lag and /cmi suicide make server ERROR
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
From console: https://hastebin.com/sivufezese.md

---

**Cmi Version (using`/cmi version`):** 8.7.0.11

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** Paper 83 (1.16.1)

**Comment by Zrips** [comment]
Not a CMI error in particular. This is issue with net.md_5.bungee.api.chat.BaseComponent in particular due to changes Mojang did and deprecated "value" and replaced with "contents" while spigot code translates properly deprecated "value" into "contents" MD_5 code doesn't work with that. Will try to report this issue to him personally so we can get appropriate fix from his end
