### ISSUE TITLE
Issue #75

### ISSUE THREAD

**Issue by Yuliansky** [Zrips/CMI#375]
Hey guys, since I started to use CMI there is a new warn message which is spamming my console from time to time. I'm not sure why and I'm looking for some help. 

####################
####################

Cmi Version (using`/cmi version`): 7.7.6.0
Server Type (Spigot/Paperspigot/etc): Spigot
Server Version (using `/ver`): 1.8.8-R0.1

**Comment by LogGits** [comment]
Check this out https://www.spigotmc.org/threads/10-52-07-am-warn-ignoring-unknown-attribute-generic-armor.112263/. This error is caused by updating past 1.9 then downgrading back down to pre1.9 so like 1.8.8 etc. Im not to sure why cmi would cause this issue? Did you upgrade when installing cmi and then downgrade?
