### ISSUE TITLE
Hex color codes translate to the old color codes in 1.16.1 in the scheduler.yml

### ISSUE THREAD

**Issue by dragontekgaming** [Zrips/CMI#3786]
**Description of issue:**
When using hex codes in the scheduler.yml, it pulls the closest of the old color codes to emulate the color actually put in.
![image](https://user-images.githubusercontent.com/67290518/88010067-48686c00-cad1-11ea-8fee-a78cfe966f7f.png)
This should be Robinseggblue or {#00cccc}
**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
  Commands:
  - broadcast! &8[&4Dawnless&8] &eRules can be found at &c/rules
  - broadcast! &8[&4Dawnless&8] &eDon't forget to vote with &5/vote
  - broadcast! &8[&4Dawnless&8] &eJoin our discord with {#00cccc}/discord
```

---

**Cmi Version (using`/cmi version`):** 
8.7.3.0
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git=Spigot-4d9262c-dc7c3c6 (MC:1.16.1)

**Comment by dragontekgaming** [comment]
According to someone else, this is also happening in eventCommands.yml

**Comment by CloudeLecaw** [comment]
Whats your Problem with this? The colorcode you posted is simliar to &b all fine

**Comment by Zrips** [comment]
@dragontekgaming 
Honestly i have no idea whats the issue here is exactly as you provided picture with actual color by provided hex color code. Even by importing your image into photoshop and checking its hex code i'm getting #00c9c9 which is really close to #00cccc.
Closing this ticket, unless i missed something more obvious, then let me know.
