### ISSUE TITLE
Nametag pets

### ISSUE THREAD

**Issue by Blandix** [Zrips/CMI#3804]
When you try to nametag pets like cats, wolfs or parrots, it seats/stands up, and you can't see the name (but it's named, because if you kill they you can see the name on the chat)

---

**Cmi Version (using`/cmi version`):**  8.7.3.2

**Server Type (Spigot/Paperspigot/etc):** Paper Spigot

**Server Version (using `/ver`):**  git-Paper-371

**Comment by Zrips** [comment]
You could try testing this by setting DisableTeamManagement to false and checking if this resolves issue. Its most likely due to team management issue where your pet gets put into same team as you and inherits some of the settings which hides his name. Cant reproduce this issue currently, so some specific setup is required.

**Comment by Blandix** [comment]
> You could try testing this by setting DisableTeamManagement to false and checking if this resolves issue. Its most likely due to team management issue where your pet gets put into same team as you and inherits some of the settings which hides his name. Cant reproduce this issue currently, so some specific setup is required.

Sorry for making you wait. It's already false, so i don't think that's the problem.

If it's helpfull, this is my config: https://pastebin.com/jHLiqC9B

**Comment by Zrips** [comment]
Most likely was related to players team management due to weird minecraft handling of them which applies to tamed entities and would hide its name when particular setting is enabled on player.
