### ISSUE TITLE
How do I get my ultra perms prefixes to work with CMI Chat

### ISSUE THREAD

**Issue by MarazaAlly** [Zrips/CMI#3853]
**Question: **
I installed CMI today and I use Ultra Permissions as my permissions plugin. I installed it and started configuring things but I cannot figure out how to get my prefixes over. Is there a way to disable the built in rankup system? The chat format has the {prefix} part in it already

**Comment by variananora** [comment]
Install PlaceholderAPI and use this placeholder (https://ultrapermissions.com/wiki/placeholders/), and you can disable the rank up system from modules.yml by making `ranks: false`

**Comment by CloudeLecaw** [comment]
Does ultra Perms has special placeholders?
You can try placeholder api if this has special once. At the Moment i think cmi does not hook with ultra perms luke it does with pex orluck perms. For Chat you can use the group chatformat and give your permission groupsthe reated permission to that chat format but this dies not help you with the tablist.there you just xould define differnt tabslists for each group (use the permission with numers you see them in the related config section). If you want the prefix and suffixes from this permission plugin and it dies not work with placeholder api then you could ask Zrips for supporting it :)

**Comment by CloudeLecaw** [comment]
One question..he the OP said he us Ultra Perms - Ultra Perms is not Ultra Permissions.. just let you know..
If the OP was wrong and he is using Ultra Permissions instead of Ultra Perms then he can simply install Playerholder API
and use 
%uperms_prefix% – The player’s prefix if set / their highest group’s prefix.
%uperms_suffix% – The player’s suffix if set / their highest group’s prefix.
%uperms_rank% – Player’s rank name.
%uperms_prefixes% – Player’s prefix & group prefixes.
%uperms_suffixes% – Player’s suffix & group suffixes.
%uperms_rank_timer% – Rank timer of the next highest timed group.

for the suffix and prefix

```
  GeneralFormat: '%uperms_prefix%&f{displayName}&7 %uperms_suffix%: &f{message}
```

```
  GroupFormat:
    '1': '%uperms_prefix%&f{displayName}&7 %uperms_suffix%: &f{message}'
    '2': '%uperms_prefix%&f{displayName}&7 %uperms_suffix%: &f{message}'
    '3': '%uperms_prefix%&f{displayName}&7 %uperms_suffix%: &f{message}'
```

**Comment by Zrips** [comment]
Will be fixed with next version
