### ISSUE TITLE
/ride

### ISSUE THREAD

**Issue by SottaByte-Ham5teak** [Zrips/CMI#3893]
players can ride item frame and if there is a solid block on top of the item frame (1 block higher than the item frame),they can teleport to another location and the item frame with the item inside will be teleported as well .
also players can ride another player and teleport them to another location.

---

**Cmi Version :** 
 8.7.5.1
**Server Type :** 
paper-131
**Server Version :** 
1.16.1

**Comment by CloudeLecaw** [comment]
Itf yiu give them the permission to ride (they sit on it) then they can ride. Its normal that the sitting sometime looos a bit like teleporting.
But the thing with the itemframes should not be... 
Very strange cant reproduce it. 
Could you type ingame /cmi Versionen and place st the Screenshot of it, so we can see what server causes this? Your useing other relevant 3rd plugin rather than CMI?

**Comment by SottaByte-Ham5teak** [comment]
>.... [06:08:41 INFO]: --------------------------------------------------
>.... [06:08:41 INFO]: CMI: 8.7.5.1 BungeeCord MySQL-> 8.7.5.3
>.... [06:08:41 INFO]: Server: Paper(131) 1.16.1-R0.1-SNAPSHOT
>.... [06:08:41 INFO]: CMI economy: True Vault: 1.7.2-b107(CMIEInjector) CMI Chat: True
>.... [06:08:41 INFO]: Modules -> 50 enabled 1 disabled: tablist
>.... [06:08:41 INFO]: --------------------------------------------------

yes but non of them are for teleportation

you can join our server and test it if you want :) SottaByte#1543

**Comment by Zrips** [comment]
Will fix issue with itemframe riding, while teleporting player is most likely related to cmi.teleport.with.[entitytype] permission node where you give players access to cmi.teleport.with.player permission node.
