### ISSUE TITLE
/stack

### ISSUE THREAD

**Issue by MrMcyeet** [Zrips/CMI#3900]
**Description of feature/improvement request:

/stack would let you get oversized stacks of items. For instance, if you had two stacks of 16 epearls, /stack would make it one stack of 32 epearls. Or if you had 4 white beds, and did /stack, it would put them all into the same stack.
**

---
### Detailed explanation of what it should do, when and in what situation: 

It can be used any time a player has, for instance, 20 lava buckets, and they do /stack, it would put them all into the same (20 bucket) stack
###

### Basic explanation as to why this feature is needed and/or useful to have: 

Useful for allowing players to transport larger amounts of items, like beds or buckets
###

**Comment by CloudeLecaw** [comment]
you can do this allready with the more command so why a stack would be needed? :3
but ok create custom alias for this

> more (playerName) (-clone/[amount])
> Fills item stack to maximum amount
> 
> Permissions:
> cmi.command.more.oversize  to get oversized stacks
```
  stack:
    Cmds:
    - cmi more $1-
```

**Comment by MrMcyeet** [comment]
I had looked into the /more command, and as far as I can tell, it only maxes out the stack of what you're holding.

My idea of a /stack would only use what you already have in your inventory, so if a player had one white bed in his inventory, held it in his and, and did /stack nothing would happen.

But If  a player had 6 white beds in his inventory, and then did /stack with a white bed in his hand, it would take all of the white beds from his inv and put them into his hand as one 6 stack of white beds.

I don't think /more can do that though.

**Comment by CloudeLecaw** [comment]
but ok since you wished this you may should work with existing stuff and extant it instead of adding new commands all time to cmi

So what about a new varriable for this? **(stack)**


more (playerName) (-clone/[amount]/**stack**)

What the new varriable should do: - stack existing items from inventoriy to the stacksize to allowed of maximum 64

Permission:
 **cmi.command.more.oversize.stack** -  allows using the stacking argument to stack items to the maximum of 64

Note you should not create bigger stack then 64! this the limitation if minecraft and this also has reasons. true - you can higher the amount with plugins but this can be result in buggy stacks. so pls limit it to 64.

if this is added you can create a custom alias.
```
  stack:
    Cmds:
    - cmi more stack
```

**Comment by MrMcyeet** [comment]
The problem I have with that idea is that it's still cheat-y.
The /stack would only use what the player already had in their inventory, and thus not give them anything they didn't get on their own. 

And I agree, there is no need to make stacks of more than 64.
The idea for /stack is just for things that don't already stack to 60 (i.e. beds, buckets, ender pearls, eggs, etc...)
