### ISSUE TITLE
No Playername Formatting in Console/Logs

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#3939]
Since {#color} has been added, player names show up wonky in console and in logs. This makes it hard to easily search the logs with "grep", but having to find out how their player name is formatted before gripping.

```
[14:05:02 INFO]:  §xJ§xu§xs§xt§xK§xa§xr§xm§xa joined the game
[14:05:06 INFO]: [§xDRFTR] PupsDaArtist: eyy
[14:05:08 INFO]: [§xDRFTR] Emily463: ayyy
[14:05:19 INFO]: [§xLEGND] §xJ§xu§xs§xt§xK§xa§xr§xm§xa: aye
```

It would be nice if no formatting was sent to console and logs. Thanks!

**Comment by CloudeLecaw** [comment]
This normal because this is hiw it works internaly they give a colorcide with 2letters like xx and that is telling them what hexcode is used. You consile just shiws the true colorcodes behind the Magic. ;) by the way... Look at plugins that does nit Support this like the console itself or dynmao there a hex colored name looks totally different 😂
