### ISSUE TITLE
Order tab not working | Lucksperms

### ISSUE THREAD

**Issue by JavituRec** [Zrips/CMI#4075]
**Description of issue:**
Hello,

I wonder why the order of the tab is not working. I've tried to use groups but the order still doesn't work. Would there be any possibility to order the ranges with Lucksperms? It looks pretty bad when there are 80 players and all the ranks are in disorder.

Thank you.

---

**Cmi Version (using`/cmi version`):** 
8.7.6.7
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot

**Comment by CloudeLecaw** [comment]
Thw tab order does not work because a feature like this does not exit. Look for tablist in the open threads you will see a lot of ppl askes for this the last two years.
But finally its no bug

**Comment by JavituRec** [comment]
This is simple, I do not know why it is not added. I will use another plugin for this.

**Comment by CloudeLecaw** [comment]
Simple or Not
Its not an existing feature of CMI
look here
https://github.com/Zrips/CMI/issues/3912, https://github.com/Zrips/CMI/issues/3571, https://github.com/Zrips/CMI/issues/2671,  https://github.com/Zrips/CMI/issues/1760, https://github.com/Zrips/CMI/issues/931, https://github.com/Zrips/CMI/issues/653
You see since Juli 2018 people aksing request for this feature and its not added.. noone knows why :3

**Comment by Zrips** [comment]
Tablist sorting isint as simple as it might look, there is a code which was doing that at some point, but due to some issues got disabled. This will be brought back when i will have time to mess around with it and retest entire system for possible issues.

**Comment by Skyfighter1** [comment]
Pls add this xd
