### ISSUE TITLE
Bug permission

### ISSUE THREAD

**Issue by Juiceqad** [Zrips/CMI#4094]
![Screenshot_1](https://user-images.githubusercontent.com/61871941/91475285-ce3bbc00-e8b4-11ea-9e2e-0f64c2ea6bf3.png)
In the admin group there is cmi. *, Which gives access to all commands, but I want to disable specific commands, but when I set it to false, the command continues to be available.

**Comment by CloudeLecaw** [comment]
i see your using luckperms
Well in Pex you need to negate and then give like in a list
i would check your perm grouppfile not with the gui editor to see what comes first
if cmi.* comes first then its nonsense to negate (false) after

**Comment by Zrips** [comment]
@Juiceqad 
In general this is not a CMI issue because it used generic permission check by utilizing official API for that. If you give player access to every permission node and then negate some of them you might need to do it backwards then you have it currently. Permission order does matter. You can always double check how CMI see particular permission nodes by using **/cmi haspermission (playerName) [permission]** command just to be sure that its correctly setup.
