### ISSUE TITLE
wrong TP off player on vanish

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#4171]
When i am in vanish mode and teleport a player to me it teleports the player to a place somewhere else...
When unvanished it works fine.
We tested the vanillatp command too and it works normal

![image](https://user-images.githubusercontent.com/12080017/92333754-3c883780-f088-11ea-967f-db5f9b145849.png)

**Comment by Zrips** [comment]
One of recent updates mentioned that in case you are using tp command on some one you cant see, you will be teleported to this players log out location, just to simulate you being off instead of being vanished. Tho will make some adjustments to teleport player to your exact location in case you initialized teleportation by yourself
