### ISSUE TITLE
cmi.server individual permissions

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4173]
Can we have a permission system that i can give cmi.server.specificserver?

The problem is that I have 4 servers in the bungee network and only 2 of them should be able to teleport with the cmi server command.

Thank you!

**Comment by CloudeLecaw** [comment]
Why not use one like Luckperms for Bungeeservers?

**Comment by blakedj012** [comment]
because cmi.server exist :)

**Comment by CloudeLecaw** [comment]
> server -> Connect to bungeecord server
> cmi.command.server -> default: op
> cmi.command.server.others
> 
> server [serverName] (playerName) (-f)
> Connect to bungeecord server
You see it just exist for this command
It is to Connect a player or your self to an other sever of your bungeecord

**Comment by blakedj012** [comment]
Sorry I have now installed Luckperms for Bungee. Now I can assign permissions for bungee.command.server which is enough for me. Thanks for your help.

**Comment by CloudeLecaw** [comment]
```
CustomAlias:
  tptobungee Bungeeserver1:
    Cmds:
    - perm:cmi.command.customalias.tobungee1! asConsole! server BungeServer1 $1
  tptobungee Bungeeserver2:
    Cmds:
    - perm:cmi.command.customalias.tobungee2! asConsole! server BungeServer2 $1
```
This commands create 2 custom alias

**_/tptobungee Bungeeserver1_**
and
_**/tptobungee Bungeeserver2**_
(both are tabcompleted ;)
They send player (argument is needed behind the command to Bungeeserver1 and Bungeeserver2 if group has permission _**cmi.command.customalias.tobungee1**_ and _**cmi.command.customalias.tobungee2**_
Tabcomplet works after restart of Server. The executer does not need permission to the command /cmi server for this because it is executed as console.
