### ISSUE TITLE
versionNotSupported

### ISSUE THREAD

**Issue by blakedj012** [Zrips/CMI#4175]
I get this message on Commands like lfix or fixchunk etc.

Latest CMI & Paper

**Comment by CloudeLecaw** [comment]
What version your using - Spigit/Paperversion CMI Version?
could you paste a screenshot of the issues?

**Comment by blakedj012** [comment]
As I wrote the last CMI version and the last paper version. 1.16.2

https://gyazo.com/60478c5e1d3b4f4e564115fbb6b80195

**Comment by CloudeLecaw** [comment]
Hm may paper does not Support this?
What happens on spigot?

**Comment by blakedj012** [comment]
I think it worked before in 1.16.1 or not ?

**Comment by CloudeLecaw** [comment]
> I think it worked before in 1.16.1 or not ?

no ;-)

![image](https://user-images.githubusercontent.com/12080017/92396744-d3570180-f125-11ea-8bd7-82e6ba8d9363.png)

**Comment by Zrips** [comment]
@blakedj012 
Couple commands got disabled in recent versions due to changed game mechanics. In case of Lfix, as of 1.15 or something like that, light is calculated client side and dint managed to find appropriate way to force this update in newer versions.
Similar thing applies to chunkfix, minecraft no longer supports direct chunk regeneration, atleast not throw official API, so some work around is needed to be made for it to get its functionality back. 
For time being those commands will be disabled until future notice.
