### ISSUE TITLE
Tfly doesn't work without cmi.command.tfly.admin permission

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4244]
**Description of issue:**

---
Hi, the issue is, that when players try execute /tfly, it doesn't work for them even if they have permissions cmi.command.tfly, cmi.command.tfly.give, cmi.command.tfly.others, cmi.command.tfly.maxtime.900... it doesn't work....

And I don't wanna give them tfly.admin, because then they can set tfly 0, which will give them infinite fly...
```

---

**Cmi Version (using`/cmi version`):** 8.7.7.4

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** Paper 202, 1.16.3

**Comment by CloudeLecaw** [comment]
This is normal. They need cmi.command.tfly.admin to be able to give more tfly time. Without they are just able to see their current tfly. This was a vantage and new Feature maybe its not listed in the wiki?

**Comment by Volgeop** [comment]
I though that when they have tfly.give, tfly.maxtime900 and command.tfly, they can normally set up max 900s there... without tfly.admin, because with tfly.admin they can set there infinite amount of tfly... I wanted it as feature for my VIP players with using it only once per hour.

And tfly.give was prob. found in luckperms, there are missing some permissions on perms page as I saw.

And as I mentioned, I wanted it as VIP, so VIPs can activate for themselves fly on 15 minutes per hour.

**Comment by Volgeop** [comment]
For now I created it via alternative - special commands for mod and for players, but I think it could be adjusted.
