### ISSUE TITLE
Clear Database for users non-premiums

### ISSUE THREAD

**Issue by AlfreDGR** [Zrips/CMI#4245]
**Description of feature/improvement request:**
I would like to make a suggestion and it is, for example my server is semi premium, premium and non-premium people can enter and I have a plugin that premiums do not have to put / login and the others do. The thing is, all users are saved in cmi, their progress, etc. Is there no way for non-premium users to be removed from the database if they don't connect in x time? For example 1 year, and premium users are never removed? That is, it only affects non-premium users.
---

**Comment by CloudeLecaw** [comment]
Luckly this is not possible. It would be not so goos if a plugin suports this kind of stuff. A server like this woud be remove really fast because this os not allowed by the eula. I hope for you your seperating your nonpremium and Premium players in two servers via bungee if you delet the data of non Premium players. Else you would go straight aggain the Minecraft eula
