### ISSUE TITLE
Players cannot teleport and will be blocked from teleporting

### ISSUE THREAD

**Issue by ChiboYen** [Zrips/CMI#4299]
**Description of issue:**
"Teleport location is unsafe. 3rd party plugin" happens sometimes when a player tries to teleport by doing /spawn or /home, or even me doing /tp with them.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Default config
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 
8.7.8.0
**Server Type (Spigot/Paperspigot/etc):** 
PaperSpigot
**Server Version (using `/ver`):** 
Paper-206
**Relevant plugins (Delete if this isn't needed):**
Worldguard, but reproducible without worldguard

**Comment by CloudeLecaw** [comment]
Ti they have the teleporttoworld permission?

**Comment by ChiboYen** [comment]
Yes

**Comment by Zrips** [comment]
This cant be resolved due to simple fact that teleportation was prevented by another plugin, usually its some area protection plugin which disables player teleportation to that area. Its not a bug in particular its just how other plugins handles actions like that and i should respect their teleportation blocking as it should be for good reasons.
