### ISSUE TITLE
Kit

### ISSUE THREAD

**Issue by qwer2415wy** [Zrips/CMI#4304]
Can you add command /kitusagereset Kit [all] for all online player and offline Pls?

**Cmi Version (using`/cmi version`):8.7.8.0** 

**Server Type (Spigot/Paperspigot/etc):CraftBukkit** 

**Server Version (using `/ver`):1.12.2**

**Comment by CloudeLecaw** [comment]
Not for all OFFLINE!! If you have 1000000000 Players in your worldforder and only 10 are online. what whould you think what happens if you execute some kind of this command for 1000000000 Players.
i aspect you can say goodbuy o the server then until it crashes ;)
Well ok may 1000000000 Players is a bit to much but this also wiuld happen with 100.000 playerfiles.
So please no reset for offline. only for online players if added

**Comment by qwer2415wy** [comment]
Ok Thx

**Comment by CloudeLecaw** [comment]
One suggestion:
Create a place where player can go or inform them about where they can get a onetime use item.
Give them the reset item for free there (a Seller NPC, and IC attached NPC or just a IC attached button or sign... something like that)
Then  create and save a item with attached command that the player can use only once.

When the player now clicks the npc he will get the item once only.
when you need thisnaagai for all
simply create new npc/button/what ever,   may modify the saved items if there are new kits to resets...and your done
So everyone could reset the kit itself.

Well...
you still can do this by yourself for all online players.. by command ;)

**Comment by Zrips** [comment]
Option to reset kit cd was added couple versions back.
