### ISSUE TITLE
Toggle kit enabled

### ISSUE THREAD

**Issue by Miclebrick** [Zrips/CMI#434]
When I click the red stained glass pane to enable a kit, nothing happens (Not even an error in console)

**Cmi Version (using`/cmi version`):** 
7.7.9
**Server Type (Spigot/Paperspigot/etc):** 
paper
**Server Version (using `/ver`):** 
1428

**Comment by Miclebrick** [comment]
Still getting this...

**Comment by mercurialmusic** [comment]
I've noticed that when first creating a kit you need to toggle over to the settings page (the workbench) from the inventory page to be able to enable it. I actually find this useful since it forces me to make sure the default settings are the ones I want to keep for the kit. It's only one extra click so not a big deal - try that and see if it works for you?

**Comment by Zrips** [comment]
Will do some changes with next release to address this inconvenience
