### ISSUE TITLE
/home do sometimes instant teleport and sometimes opens gui

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4385]
**Description of issue:**

---

Hi, I heard from my players, that home sometimes instant teleports them and sometimes it opens GUI. SHouldn't it do just one of these things? GUI prob. should be opened just when using /homes, and normal /home should teleport to the home? But if not, still why it's doing sometimes this and sometimes this?

---

**Cmi Version (using`/cmi version`):** 8.7.8.4

**Server Type (Spigot/Paperspigot/etc):** Paper

**Server Version (using `/ver`):** 228

**Comment by CloudeLecaw** [comment]
On our server using /home without any other Arguments opens the gui instead of telepoting to the first (default) home.

We also found out why:
If the first home was set with /sethome without any special name after then /home teleports there. 
But if you set your first home with /sethome AHomeName  then /home seems not to find a default home and opens the gui. 
So be able to solve this the first home of a player should be his default for /home  or the player should be able to set his default home for /home

What ever the solution will be, i can agree this needs some optimize for handling default home

**Comment by Zrips** [comment]
@Volgeop 
Its by design. If player have only one home then he gets teleported to that single home, if there are more than one home then we will open UI where player can pick which home he wants to travel too. This doesn't apply when player provides valid home name. 
@CloudeLecaw 
Home name doesn't have impact, home amount does.
