### ISSUE TITLE
Itemname and Itemlore can allow changing custom items into other custom items

### ISSUE THREAD

**Issue by Skizzles** [Zrips/CMI#4411]
**Description of issue:**
When doing /itemname and /itemlore it allows you to rename custom items into others. Thus allowing exploiting of items.
https://imgur.com/a/bWsY21X
---

**Cmi Version (using`/cmi version`):** 
8.7.8.4
**Server Type (Spigot/Paperspigot/etc):** 
Yatopia (Paper Fork)
**Server Version (using `/ver`):** 
1.16.3-Ro.01-Snapshot
**Relevant plugins (Delete if this isn't needed):**
CrazyCrates, Slimefun, WildStacker, etc

**Comment by CloudeLecaw** [comment]
This is normal because this is hiw mist special items are idented. By their name and lore. You should use lore abd itemname in colors for your special items and not allow players to use colors or lore when renaming.

**Comment by Skizzles** [comment]
@CloudeLecaw Or CMI could add NBT data when it renames them which would make it void the item. CMI has this issue with multiple plugins.... The rename feature should solve the issue, not make hundreds of plugins do that.

**Comment by CloudeLecaw** [comment]
Cmi should add nothing here

**Comment by Skizzles** [comment]
@CloudeLecaw 

I am not even sure who you are but you have blatantly no clue what you are talking about. A lot of renaming plugins add special NBT tags to items in order to modify them for this exact reason.

I could go download one right now and not use CMI but that is another plugin to install. If CMI handled renaming better then it would not be an issue with numerous plugins.

I am not going to go reach out to 20 devs when its as simple as adding NBT data to renamed items. Now unless you develop the plugin hop off my thread.

**Comment by CloudeLecaw** [comment]
You have no clue hiw it works thats all. Try any other renaming plugin with your keys
You wil have the same result. 
I Profil d this allready with 3 item renaming plugins and two of them add extra ntbs. Your keys will still be able to have the same issue because your plugin for the Keys just looks for the equal name.
Nothing cmi can do here

**Comment by Skizzles** [comment]
Guess I will be more direct. I don't care for your opinion as you don't mean shit on this thread. You don't develop any of the plugins I reference so your opinion is void.

I don't allow changing lore of items and only do names.

Now **fuck off** @CloudeLecaw

**Comment by CloudeLecaw** [comment]
Test itbself before telling Nonsens my dear.
And now clam down and closed your Ticket or wait for Zrips to tell you too that cmi cant do anything here for you to fix your issue

**Comment by Skizzles** [comment]
Its not about calming down, its the fact I told you I do not want your opinion and you are like a fly that won't go away.

I already tested it myself otherwise I would not be here, I am fully aware of how things work and have been doing things for a long time boy.

When a thread author says for you to go away, then go away. You are not the dev of the plugin, a contributor, or even anyone relevant so hop off peoples threads.

Your clear lack of respect for someone's wishes leads me to tell you off. Now I have better things to do than argue with a halfwit. So kindly fuck off "my dear"

**Comment by CloudeLecaw** [comment]
Oh chears, noone can help you anymore then, so the fly now leaves you alone with your Problem that cant be fixed by cmi as long as you allow your players colors in commands :*
I need to fly now to my Popcorn.. Well what sounds does a fly would make... Well *zooooom zoooom zoooommm* ;)

**Comment by Zrips** [comment]
@Skizzles 
Item name or lore manipulations should be left only for staff or given for simple users if that will not cause issues with other plugins. I can add NBT data to renamed items, but that doesn't resolve issue where other plugins will need to actually get this nbt data and check it. Which sounds cool until you realize that if plugin developer knows how to read nbt data then he will know how to create one, which would mean that they could actually use it to mark special items instead of using item name or lore which would resolve this issue. There is material black list for item name and item lore in config file which can be used to prevent item manipulation by for specific things into it. 
So at the end of day, this needs to be fixed from plugins side which uses items and identifies them by item name or lore, which is a terrible idea for obvious reasons. 
So for now you can simply black list some materials from being manipulated by item name or item lore commands and simply bring this issue to actual plugin developers who uses terribly unsecure method in identifying items. 
And again, if i add NBT that will not resolve issue, plugin dev's still need to know how to read it and check for possible manipulations which is terribly similar method for adding info into nbt. 

All that said, will add some generic indication for modified item name or item lore into NBT data as this was on my mind some time ago anyways. It will not really resolve your issue in any shape or form until plugins actually checks for it.

**Comment by Skizzles** [comment]
@Zrips Yes that would not solve it for this crate plugin. Would solve for a couple others but I see your standpoint and value your response.

The adding of NBT data would be great as it would solve those that do check for it. Those that do not I can either A replace the plugin or B go bug them to check for that.

Personally I think adding that indication is great, and I understand that is about as much as you can do on your side so I appreciate that.

Thank you
