### ISSUE TITLE
If you right-click on a player, show preview inventory (i need permission)

### ISSUE THREAD

**Issue by WolverStones** [Zrips/CMI#4484]
Hello, i need advice on what permission is for this function. When I right-click on a player, show preview of his inventory. https://www.youtube.com/watch?v=emHJqKW_RFI

**Comment by CloudeLecaw** [comment]
We allready had this. One time someone thought he can do this with an attached command of cmi. We noticed allready this is not possible that way because there is no clicked player event. Some plugins use some kind of attack event that they cancel and then look what the target was.. Well still not possible. Give your mods the option to use a shortcut (customalais) with playername in tab to use cmis inventory view (with or without modify its uo to u)

**Comment by WolverStones** [comment]
thanks for the reply but i need to deactivate it

**Comment by CloudeLecaw** [comment]
This is nothing cmi has enabled that Ou can disable. Without eyternal help cmi does not even this Feature.
You should check your server, permissionpluginn setting or a 3rd plugin did something wrong.
Pls try to recreate this with a clean testserver + cmi + your permission plugin (with minimal setup of permission you need) 
You will see the Feature your showing in the video does not exist without external help
