### ISSUE TITLE
Tags (such as <T>) don't seem to work well with Hex colors?

### ISSUE THREAD

**Issue by nemmynaomi** [Zrips/CMI#4500]
**Description of issue:**
When adding Hex codes to text tags (In files such as Locale_EN.yml), _**all**_ tags (such as H, CCI, etc--) do not format at all.

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```yml
info:
    NoPermission: '<T>{#F8858B}ABCABC</T>'
# Or
    NoPermission: '<T>{#F8858B}ABCABC</T><H>Another Example</H>'

```

---

**Cmi Version (using`/cmi version`):** 
8.7.9.3
**Server Type (Spigot/Paperspigot/etc):** 
Spigot
**Server Version (using `/ver`):** 
git-Spigot-2740d5a-890130b (MC: 1.16.3)
API Version 1.16.3-R0.1-SNAPSHOT
(I'm not in charge of versions, otherwise It'd be kept up to date- but I can inform the host owner to upgrade)

**Screenshots (Error messages from Locale_EN.yml -- NoPermsision error)**
![](https://cdn.discordapp.com/attachments/693065734024069182/771414037405630464/javaw_5nZ8KuRsAF.png)
![](https://cdn.discordapp.com/attachments/693065734024069182/771414040369954816/javaw_wAdzS7fR9t.png)

**Comment by CloudeLecaw** [comment]
the hexcolors dont work well in this Format.. o noticed this too. i recomment to use the 16 & colors you have (color each letter for a rainbowlike style)

**Comment by Zrips** [comment]
Because they never been made to be used in those areas. ctext format is for ctext, locale files mainly deals with basic text messages and not complex json ones. So its not a bug and i dont think i will be implementing full support for them in locale file as that would be a pain to handle properly when it comes to showing those messages in different places and having it in a tag format like that.
