### ISSUE TITLE
Hello Does anyone know why I get this?

### ISSUE THREAD

**Issue by Amadeuss31** [Zrips/CMI#4513]
31.10 16:13:09 [Server] Server thread/ERROR Could not pass event EntityDamageByEntityEvent to CMI v8.7.9.3
31.10 16:13:09 [Server] INFO org.bukkit.event.EventException: null
31.10 16:13:09 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:251) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:966) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:853) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:809) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:998) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity0(EntityLiving.java:1755) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.EntityHuman.damageEntity0(EntityHuman.java:828) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1139) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.EntityHuman.damageEntity(EntityHuman.java:745) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.EntityPlayer.damageEntity(EntityPlayer.java:716) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.EntityHuman.attack(EntityHuman.java:1068) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.EntityPlayer.attack(EntityPlayer.java:1629) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1910) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(SourceFile:74) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:941) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-17d78db-a339310]
31.10 16:13:09 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
31.10 16:13:09 [Server] INFO Caused by: java.lang.NullPointerException

Spigot 1.16.3 latest CMI, DeluxeCombat

2 players fighting and one regular player not taking any type of damage. not God mode, not creative, not anything. just regular

**Comment by GcGoat** [comment]
Could you paste entire log? As crucial part is missing

**Comment by Amadeuss31** [comment]
> 
> 
> Could you paste entire log? As crucial part is missing

Of Course. I am not sure if it is CMI now since it is that Event Listener thing ( not sure if that's a spigot integrated thing or some other plugin) and it does the same for other plugins.

Complete log at https://pastebin.com/GdgziZnJ

**Comment by nitewing76** [comment]
Are you trying to run a hub, SkyBlock, Survival, and multiple minigames on 1 server???  That's too much going on...especially with intense plugins like SuperiorSkyBlock & EpicWorldGen....plus you are running CMI & Essentials (this is like trying to give 2 cars at the same time)....plus about **19 other plugins that CMI can already do** and LuckPerms can handle your prefixes....plus you're trying to run Geyser/FloodGate before ensuring no bugs exist elsewhere....plus it takes slightly more than 10 minutes for your server to load and you have multiple warnings which confirms you are trying to put too much on 1 server:

`[16:53:21] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6667ms or 133 ticks behind`

Since your error relates to combat, normally the first thing to do would be to remove any other plugin that affects combat (e.g. Boss, DeluxeCombat, and the addon). But in your case you need to divide these up into separate servers and remove the 19 redundant plugins.  Start with the ones which are required, such as LuckPerms, WorldEdit, ASyncWE, WorldGuard, Core Protect....then add CMI...then add the others 1by1 based on how important they are to you.

Plugins that CMI replaces:

- InventorySaver
- CommandWatcher
- Wailat
- SimpleAltChecker
- ItemRecycler
- RestartCountdown
- ServerSelectorX (but this is for a Hub/Lobby that doesn't really need CMI....DeluxeHub is a good choice)
- HomePlus
- MyCommand
- MysqlEconomyBank
- Essentials
- EssentialsMysqlStorage
- Maintenance
- HolographicDisplays 
- HolographicPlaceholders
- HolographicExtension
- Multiverse-Portals
- Multiverse-SignPortals
- NexelWilderness

And plugins like VisualFileEditor, the LuckPerms GUI, and other utilities are not worth the tradeoff of wasting server resources vs saving a few seconds of time. For YMLs use Notepad++ and _/lp editor_ for perms. Also there is nothing light about FeatherBoard...plus afaik it's the only thing you have that requires MVdWPlaceholderAPI, which is loading placeholders for plugins that support PlaceholderAPI (and you may already have expansion packs for), so it's further wasting resources.  WildTools can replace MultitoolPlusPro and ChestSort. WildStacker can replace IllegalStack & Mob Farm Manager (can also manage spawners, custom mob drops, and silk touch spawner mining that you'll likely need for SkyBlock & Survival). You have HeadsDatabase and HeadsPlus. ServerNPC and Citizens. 

Divide the servers by gamemode, remove the 19 redundant plugins and the other cases where you have 2 plugins doing the same thing...until then there is too much that could cause the multiple errors you have in the 10minute log. 

I hope this helps you!!

**Comment by starnauceanu** [comment]
😄 yeah. I know it is a lot but it is for a small server with about 10 players and tps is good (for now). Thank you for the answer. Already started selecting plugins to find out which one is exactly causing the error and i have to say your detailed response is a life saver. I knew CMI could replace some plugins but had no idea it could replace so many. Will give it a try and see how it goes. I am a noob after all in spigot related matters and every reply helps. Now...i just learned something new.thank you.

**Comment by CloudeLecaw** [comment]
he is right, cmi can do many many things and also replace many many plugins. even after 3 years we often find some ways and features where cmi can replace a long used plugin.. 

about Holographicdisplays... check if one if your plugins has it as dependency. 
some plugins do and dont acept the cmi holo display feature :/

**Comment by nitewing76** [comment]
One caveat I should have mentioned is that while on the surface CMI may seem to replace a plugin, it may not be a complete replacement. A few prime examples would LiteBans, CombatLogX, PremiumVanish, VotingPlugin...while CMI does offer a portion of these features, it does not offer the more advanced features. nor should it. It offers a platform for server owners to get started, with the ability to disable modules when the more advanced features of other plugins are desired. In other cases, like CMIs control of armorstands....I still use ArmorStandEditor because the ASE provides is more intuitive and easier to use, even though CMI does offer a few extra features. So it's all personal preference and not a bad thing for CMI.

True, not all plugins support CMI. Of the all plugins I use (about 90 in total), only 1 Songoda plugin doesn't support CMI...and I like CMI's holograms better than Citizen's multiline name holograms for stationary NPCs.  So I used CMI to place these holograms manually.

**Comment by CloudeLecaw** [comment]
hat you are missing from litebanns? the Over other server feature?

And about the Premium Vainish are these ANimated things of vanish nesseary?

But ok its allways up to you to decide ou also cn stay with your bunch of plugins ^^

About Voting Plugin
you need one dont worry ;)
cmi hooks well into voting plugins like Votifier

Finaly the question is what you really need, ifu want this little feature that other offer? yes then use the plugins.
noone forces you to replace all with cmi features^^

**Comment by starnauceanu** [comment]
Oh i am definitely doing what nitewing recommended. Splitting them all on different servers and adding only the necessary plugins. I didn't expect my question to get such detailed answers and i want to thank you again and again. This was basically the information i have been looking for from day one but moat answers i found were a bit outdated. Instead of an answer like " give up noob" i have received a full detailed explanation on how things should optimally be. Kudos. And that is why I cringe when I get "If you are to lazy to follow instructions " on some other developers' plugins [true story and no. Wiki was 2 years old]. Again. Thank you for your time all.

**Comment by Zrips** [comment]
@Amadeuss31 
Will fix your error, but yea, as people mentioned here you need to clean up some of the plugins especially if they fail to even start or you have duplicates which does same things.
