### ISSUE TITLE
Shulker box lores

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4536]
**Description of feature/improvement request:**

---
### Detailed explanation of what it should do, when and in what situation: ###
Hi, can you add way to disable special item names in shulker boxes lores to prevent baiting players?
![image](https://user-images.githubusercontent.com/18662086/98290167-94202200-1fa9-11eb-8f1d-d42b7309a09e.png)
![image](https://user-images.githubusercontent.com/18662086/98290173-95514f00-1fa9-11eb-9b6e-8aa13750ff0f.png)

### Basic explanation as to why this feature is needed and/or useful to have: ###
Would be useful, because players are making frauds on another players and putting these shulker boxes into auctions... Way to prevent scams in auctions - prevent renamed item names in shulker boxes, if it's possible.

**Comment by mrfloris** [comment]
To be fair, this isn't done by CMI but a vanilla behavior. It is more a request for Mojang to show renamed items properly in the lore.

I do not know if there's a attribute that can be cancelled or some method to prevent it from showing. If there is, then maybe cmi could have it as a global toggle i config.yml maybe.

**Comment by Volgeop** [comment]
I know it's not anything related to CMI, just requesting feature if there can't be added something to prevent it.

**Comment by Zrips** [comment]
@Volgeop 
Well its mainly done at client side and not from server. Server simply sends data what shulkerbox contains exactly to the player. I could maybe make some code for item into chat feature to filter out this and show actual contents instead of renamed ones, but this cant really be handled on a scale where auction plugins would actually show different information.
