### ISSUE TITLE
Signedit does not work for players

### ISSUE THREAD

**Issue by xReplicate** [Zrips/CMI#4556]
[Video](https://cdn.discordapp.com/attachments/655307774653366272/774373151047680020/Minecraft__1.16.3_-_Multiplayer_3rd-party_Server_2020-11-06_21-40-27.mp4)
Signedit doesnt give a pop-up anymore.

As you can see in the video, I started by turning /signedit off and on.
I tried to edit my interactive sign, I did not got the pop-up, I did get the chat confirmation about creating an interactive sign, so it looks like it did change the sign.

I also placed a new sign, I tried to edit it after I placed it, it didnt do anything.

Signedit does work for op's but not for normal players even if they have the cmi.command.shiftedit and cmi.signs.shiftedit permissions. The area is not protected by a claim.

---

There is no console error appearing.

---

**Cmi Version:** 8.7.10.2

**Server Type:** Tuinity

**Server Version:** 1.16.3

**Relevant plugins:** Worldguard for protecting areas.

**Comment by EkonC** [comment]
Yes, I have exactly the same issue on my server.
Permission `cmi.signs.shifteditbypass` "solves" this problem but players can edit signs in other players residences (in worldguard regions they can't, it lets them edit the sign but when saving it says they don't have a permission).
This problem is not only in protected areas but in the whole world (it might take worldguard global region as a protected area?) I don't know. But I'd certainly like to have this fixed as soon as possible.

**Comment by Zrips** [comment]
Some small issue with event check, should be working properly with next update
