### ISSUE TITLE
Mirror

### ISSUE THREAD

**Issue by Volgeop** [Zrips/CMI#4573]
**Question: **
Hi, I would like to ask how does mirror exactly works? Can I give it as advantage to the highsest VIP ranks? Could players duplicate blocks with it, OR do they need blocks in inventory? So for ex. if they can mirror glass, they need to have few stacks of glass in invetory to do it, or it allows them to do it without taking materials?

If so, couldn't be way to improve it to takes their materials?

**Comment by AZFire1** [comment]
Unless your server is a creative server, or something where players can get infinite blocks without any effort don't give that to your players. That's more of a small fun looking building thing that your builders can use to build stuff. It shouldn't be given to players because, yes they can dupe blocks. Bassically, how it works is, you place a block, an that block gets copied an placed in all the directions you have chosen. It's not a thing where it takes blocks out of your inventory. It could definitely possibly be a perk for a creative server though.

**Comment by CloudeLecaw** [comment]
I agree with AUFire. mirroring is something only for creative cause a.it overwrites protections + b. it mirrors (duplicate the blicks u set)
So just use it if the Region has no protectionzone + is limited to creative

**Comment by Volgeop** [comment]
And what about option that players with not creative mode will need enough material to mirror? If this would be possible, then it could be a perk for Survival too. But yeah, if it doesn't respect protections (like residences), then it's prob. not so good idea.

**Comment by AZFire1** [comment]
You may suggest it with a new github issue dedicated to it if you want. I can't guarantee you that it will be added though. No, it doesn't support claiming plugins, as I said it's just a simple building tool to help make builds. Or, for me to help make weird looking builds xd

**Comment by CloudeLecaw** [comment]
You can suggest this, but this would be a new feature request. Currently this “need itemsthing" does Not work, currently it duplicates.

**Comment by Volgeop** [comment]
Ok, thanks, will open feature request.
