### ISSUE TITLE
nickname task is taking too many tick

### ISSUE THREAD

**Issue by AuroraCraftSG** [Zrips/CMI#4671]
**Description of issue:**

nickname task is taking too many tick
---

**CMI::Task: com.Zrips.CMI.Modules.NickName.NickNameListener$1 (Single)count(2962)  total(13.57% 10.103s, 20.77% of tick)avg(3.41ms per - 10.38ms/3.04 per tick**
---

**Cmi Version (using`/cmi version`):8.7.11.1

**Server Type (Spigot/Paperspigot/etc): paper

**Server Version (using `/ver`):1.16.4

**Comment by Insprill** [comment]
that doesn't do much at all without the full timings reports. please send the link to it and make sure to run it for >10 minutes.

**Comment by Zrips** [comment]
Well in general i can move this one into async. This was caused by showing Json type messages. Tho without any extra information about actual time span of this timings its hard to say if its an actual issue or just false/positive. In any case, if you will experience same issue with next update, let me know.
