### ISSUE TITLE
CMI ride + towny

### ISSUE THREAD

**Issue by Kbryst** [Zrips/CMI#4745]
**Description of issue:**
Players who are in towny claimed areas cannot use /cmi ride on eachother. It gives them the correct text, but doesn't actually complete the action even if they have full perms to the towny area.

**Cmi Version (using`/cmi version`):**  8.7.11.2

**Server Type (Spigot/Paperspigot/etc):**  paper 

**Server Version (using `/ver`):** 1.16.4, 267 (a little behind)

**Relevant plugins (Delete if this isn't needed):**
Towny Advanced 0.96.5.0

**Comment by Zrips** [comment]
This seams to be caused by towny preventing slime being spawned in, which is used to place player slightly above another player. What i can do is simply place player directly on top of another one if slime cant be spawned in. This will result in rider blocking players view, but at this moment we cant really do anything about it if another plugin blocks entity spawn in event.
