### ISSUE TITLE
Glow colours

### ISSUE THREAD

**Issue by argnapa** [Zrips/CMI#4755]
**Description of issue:**
Hi, I've set certain ranks to have the glow colour and put both perms on luckperms although from reading similar issues online, I think one of the permissions doesn't work.
![image](https://user-images.githubusercontent.com/73750433/102492820-20723a00-406a-11eb-8112-d5a2230eeee4.png)

The issue is that the colour does not show up. If I log in and out, it shows for two seconds and then disappears again. 

If you need any further info, happy to provide.

Thanks,
Adrianne

```
######################
## REPLACE WITH ERROR ##
######################
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
## REPLACE WITH RELEVANT CONFIG SECTION  ##
#######################################
```

---

**Cmi Version (using`/cmi version`):** 8.7.10.0 sqlite

**Server Type (Spigot/Paperspigot/etc):** paper(331) 

**Server Version (using `/ver`):** 1.16.4

**Comment by Zrips** [comment]
This can be due to multiple reasons, most common is issue with compatibility with another plugin which would modify glow color on login. You might need to retest this with CMI only to make sure its CMI issue and not compatibility with another plugin. In any case, we need more information what is going on in your particular situation to know if we can fix this.

**Comment by WolverStones** [comment]
If you use a plugin such as TAB, it overrides the color glow according to the color of the nickname.

**Comment by argnapa** [comment]
Ohh, I see...thanks for the info!
