### ISSUE TITLE
Missing Locale value

### ISSUE THREAD

**Issue by winnipeg21** [Zrips/CMI#4783]
**Description of issue:**
Basically when you do /tpahere you get the error "Missing locale for command.tpahere.info.requestSent". Issue is fixed when adding requestSent to the locale file.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
Missing locale for command.tpahere.info.requestSent
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
command.tpahere.info.requestSent
```

---

**Cmi Version (using`/cmi version`):**  8.7.12.2

**Server Type (Spigot/Paperspigot/etc):** Tuinity

**Server Version (using `/ver`):** paper-312

**Relevant plugins (Delete if this isn't needed):**

**Comment by winnipeg21** [comment]
Edited my message a lot since the bug report format is weird to view with markdown lol

**Comment by Zrips** [comment]
Cant reproduce this one. Locale lines are generated automatically if they got removed. So ether you had something else set for this path, maybe a listString type entry or you have some issues with locale file updates due to lack of permissions to do it. But in general its not an issue at this moment.

**Comment by winnipeg21** [comment]
I reproduced this on a test server same error. Also viewing the translations folder on this repo the line is missing from the locale file as-well.
