### ISSUE TITLE
Hologram icons are shown below holograms on Bedrock (Geyser compatibility)

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#4807]
**Description of issue:**

---
Hi, I'm using Geyser plugin for connecting Java and Bedrock edition and there's problem with hologram icons. Do you think that you can improve it a little bit to work on Bedrock edition too?
![image](https://user-images.githubusercontent.com/18662086/103137757-27352880-46cc-11eb-84c3-3961b4247d7e.png)

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/18662086/103137766-3f0cac80-46cc-11eb-8024-0a1a59eab62b.png)

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/18662086/103138267-2783f280-46d1-11eb-8721-480bf9a279d5.png)

**Relevant plugins (Delete if this isn't needed):** Geyser

**Comment by Zrips** [comment]
You might simply need to give more free space for that icon to float around. CMI places item where it should be, but game could decide to move it to empty space if current position is not suitable for it. This is similar to the issue with water where icons placed in water will tend to float up due to general game behavior with items in water. Cant really resolve this without change in game code itself

**Comment by bobhenl** [comment]
![image](https://user-images.githubusercontent.com/18662086/105051509-1da2a480-5a6f-11eb-8e39-12d9e8b3e6b3.png)
There are more problems on Bedrock, holograms are visible through walls.

And it's not due to space
![image](https://user-images.githubusercontent.com/18662086/105051614-39a64600-5a6f-11eb-8995-0b5794fcc778.png)
