### ISSUE TITLE
/ride >> press SHIFT >> Player can't send messages

### ISSUE THREAD

**Issue by iBuseWinner** [Zrips/CMI#4845]
**Description of issue:**
When someone rides a player and then leaves him (not the server), that player can't chat and nobody can see him.
![image](https://user-images.githubusercontent.com/44753872/103458431-237f5280-4d19-11eb-9701-6f05f5aedba6.png)

---

**Cmi Version (using`/cmi version`):** 
8.7.12.4

**Server Type (Spigot/Paperspigot/etc):** 
Yatopia

**Server Version (using `/ver`):** 
1.16.4-RO.1-SNAPHOT

**Comment by Zrips** [comment]
This you will need to retest with CMI only as issue like this relates to some issues with packets between user and server being messed up, while CMI doesn't do anything like that for riding so it could be caused by another plugin when player jumps off. 
And just extra question, does this happen when riding another player or entity or in every case?

**Comment by iBuseWinner** [comment]
Hmm, something wrong with another plugin's config.yml...

**Comment by iBuseWinner** [comment]
So it's still happens and I don't know why...

https://drive.google.com/file/d/1XEOJrR-K3CxPIQioOUrbqsXQVLuMIifl/view

**Comment by Zrips** [comment]
Your video link is broken

**Comment by Zrips** [comment]
While you mentioned this realized that this might be issue with NoCheatPlus plugin interfering. Will issue fix for that one which might fix this.

**Comment by iBuseWinner** [comment]
It isn't NCP, I'm using Matrix

**Comment by iBuseWinner** [comment]
Fixed link sorry Zrips
https://drive.google.com/file/d/1XEOJrR-K3CxPIQioOUrbqsXQVLuMIifl/view

**Comment by Zrips** [comment]
Test new version and let me know how it goes

**Comment by iBuseWinner** [comment]
Bug still works
