### ISSUE TITLE
Glow command Cant seem to get Color working.

### ISSUE THREAD

**Issue by RustyDagger** [Zrips/CMI#492]
**Description of issue or feature request:**
As seen in this Gif I cant seem to get /glow Green or any other color to work its just making me white every time. I have all the perms needed as also seen in the Gif. 

https://gyazo.com/932d36c02ae676961cc438b242f0c308

**Cmi Version (using`/cmi version`):** 
7.8.3.0
**Server Type (Spigot/Paperspigot/etc):** 
CraftBukkit
**Server Version (using `/ver`):** 
CraftBukkit 1.12.2
https://gyazo.com/5fd0195db80d530eeac648b52591a008

**Comment by CloudeLecaw** [comment]
iu Setup wrong permission:

cmi.command.glow.[colorname] - is correct
ur pictur Show us u made it cmi.command.glow.color.<colorname>  <- nonsense

https://www.spigotmc.org/wiki/cmi-permissions/

**Comment by RustyDagger** [comment]
Where Did I show the permission I have set. the list in chat is what CMI is checking its a debug mode provided by luckperms, Luckperms is saying that All the permissions its being asked to check is TRUE

If it was the wrong perm CMI should be telling me that.

**Comment by CloudeLecaw** [comment]
Yours
![image](https://user-images.githubusercontent.com/12080017/41294822-3b72120c-6e59-11e8-946b-982e76fa6ed1.png)

**Comment by RustyDagger** [comment]
Yes as i explained I have set that NODE to true because CMI is checking it.

**Comment by CloudeLecaw** [comment]
here i  made a test what permisison are asked for on /cmi glow green

![image](https://user-images.githubusercontent.com/12080017/41295139-0ec84a54-6e5a-11e8-873f-e7427c7e5fe5.png)

**Comment by RustyDagger** [comment]
https://gyazo.com/e6e58e9224f3767e6da1211c8af4f996

**Comment by CloudeLecaw** [comment]
did i? not really. the screenshot was just in playermode to see all asked permissions. As admin you would not see all why? if i would have cmi.command.* then my permissionsystem dont asks anymore for cmi.command,glow.* etc... but ok (only if specialy negated)
but ok :-D

fact is that the Colors do not Change. your just can turn on / off White since the last Version.

by the way. i had not read the upload Things About Color, so i just saw yur asked permissions. when checking itself after i saw too that is changed, so i edted my post to correct it and that is totally ok.^^
by the way ist not my Problem that u let every answer responce in one thread Mailing to your mail, you should know u can set this up a bit better in GitHub ;) but ok. i think u havent done this, so..Hey..welcome for this new mail in your box XD

**Comment by LogGits** [comment]
@RustyDagger do you by any chance have a seperate plugin that modifies scoreboards, e.g. featherboard?

**Comment by RustyDagger** [comment]
not that im aware of, Plugin List
https://gyazo.com/5a29d98c9882b85ca2498c0fc7122bbc

**Comment by realCmdData** [comment]
Getting the same error. I disabled the scoreboard plugin I was using (Quickboard) and gave my alt the user permission for the specific colour and it still doesn't work
https://imgur.com/a/2WzyArP

**Comment by Zrips** [comment]
Testing without any other plugin is needed in this case. On a clean server it does work as its suppose too, so this means something outside plugin interferes with this feature, so we need to find out what exactly and then i can come up with a fix for it.
