### ISSUE TITLE
Issue with armorstand and hex

### ISSUE THREAD

**Issue by Gayytis** [Zrips/CMI#4968]
**Description of issue:**
People have the permissions cmi.command.armostand.body but can't edit the body [(see here)](https://cdn.discordapp.com/attachments/777969179680440321/802622973873225778/unknown.png)

Also, people with the permission cmi.colors.publicmessages.* can't use &k and hex color [as you can  see here](http://thomasclosson.fr/videos/hex.mp4)

---

**Cmi Version (using`/cmi version`):** 8.8.0.5

**Server Type (Spigot/Paperspigot/etc):** Paperspigot

**Server Version (using `/ver`):** Paper 1.16.5-443

**Relevant plugins (Delete if this isn't needed):** GroupManager

**Comment by Zrips** [comment]
For armor stands, as you dont have set empty field filler its hard to say if you can edit or not, 
![image](https://user-images.githubusercontent.com/10416201/105695968-61802880-5f0b-11eb-9215-28caeae98c8d.png) this is how actual editor looks like with all permissions and appropriate lost indicated for armor stand item editing. 
For color permissions, currently wild card type permission disabled due to some issues relating to it. That doesn't mean that you cant use wild card permission node, you will simply need a permission plugin which supports that, one of those would be LuckPerms which properly handles wild card permission nodes at their end.

**Comment by Gayytis** [comment]
That's what i have when i am OP : ![image](https://user-images.githubusercontent.com/65625456/105735863-78874080-5f34-11eb-8648-cec04e3ed87e.png)
And this when i am not : ![image](https://user-images.githubusercontent.com/65625456/105735883-7de48b00-5f34-11eb-879a-47284e1ffd88.png)

And OK so with GM i'll need to add every single color manually... Imma try to converge to LP tho

**Comment by Zrips** [comment]
GroupManager is outdated and quite inefficient in multiple places, if there is a way to convert i would strongly recommend to do so. 
And for UI, everything seams to be fine, regular player simply missing cmi.command.armorstand.torso and cmi.command.armorstand.interactable permission nodes
