### ISSUE TITLE
Portals won't select

### ISSUE THREAD

**Issue by Hobiten** [Zrips/CMI#5008]
**Description of issue:**
so I'm trying to make a portal but it won't select like nothing happens, perms and portals is enabled in modules  ( and yes I do have a shovel in hand).. Apart from that i can't see any errors or issues that like cmi spamming in the console or logs that something should be broken or wrong.

**Cmi Version 8.8.0.9

**Server Type: Paper

**Server Version: 1.16.3

**Comment by Zrips** [comment]
Could be interference from another plugin canceling selection event. If tool doesn't work you can ether change selection tool material in config file or try disabling plugins to figure out if it was caused by another plugin or simply use **/cmi select pos1** and **/cmi select pos2** commands as alternative.
