### ISSUE TITLE
Something

### ISSUE THREAD

**Issue by MCServerCreator** [Zrips/CMI#5043]
Hello. About a year ago I purchased a copy of your plugin from SpigotMC. I was impressed by the number of features, commands and functions. Then I thought it would be nice to use it for my server. But I was faced with the lack of sorting the players in the tab and the ability to listen to the local chat for the administration. Then I decided to go to GitHub and write a proposal for adding these functions, since many people use them. It turned out that there were already a lot of such requests (#5019 #3260 #3444 #3510 #4874  and etc). I thought I should wait until they are added. As you can imagine, Zrips, they still don't exist.

Now I am wondering why they still do not exist, and why should I use third-party plugins when I bought CMI?

**Comment by mrfloris** [comment]
Because a plugin can't just add every single feature, option, customization, tweak, edge case scenario, plugin integration, api support, library support, etc that everybody is always asking for. Sometimes things are out of the scope of a plugin, other times it's just lack of free time. Sometimes things require a rewrite or library update. Or because of how bukkit/spigot's api works not technically possible at that point in a way that it makes sense. 

^ that is a general statement that applies to every plugin.

Local chat has been a thing though. there is a way for private/persistent staff channels. Team members with permissions can make these and use them. Spy feature is also available to allow others who aren't in those chats to still keep track. There's also /staffmsg 

Sorting players in the tablist is a highly requested feature. I hope one day it makes it into CMI if possible.

**Comment by Zrips** [comment]
@MCServerCreator 
You are getting what was promised, tab sorting is not one of those things. It could be added later on, but priority falls to bug fixes and not to every single suggestion people would have for new feature which would require quite allot of extra work. Some features are requested quite frequently, those are not added because they are not 5 minute implementations and nagging about  it will not speed up process of it being added.
