### ISSUE TITLE
Random target on effects when no targar is set in custom alias

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5084]
```
  eswerdelicht:
    Cmds:
    - perm:cmi.command.customalias.eswerdelicht@! msg! [playerName] &cDu kannst diesen Befehl nicht benutzen.
    - perm:cmi.command.customalias.eswerdelicht#! check:$1==%cmi_user_name%! asPlayer! cmi effect night_vision 20000 1
    - check:$1==null! asPlayer! cmi effect night_vision 20000 1
    - check:$1!=%cmi_user_name%! asPlayer! cmi effect $1 night_vision 20000 1
```
![Snag_26cbf220](https://user-images.githubusercontent.com/12080017/107821230-5f77ef80-6d7c-11eb-8873-dee867874b92.png)

Whe n someone usses now/eswerdelicht   then the target of the effect is a random person
well we can avoid this with using  [playerName]  but normaly the used player should be target if no other playername is used...

![Snag_26ccff69](https://user-images.githubusercontent.com/12080017/107821329-87ffe980-6d7c-11eb-9311-5f36ed377656.png)

**Comment by Zrips** [comment]
Hard to get whats the issue here exactly. Tested out your setup, everything seam to work properly and correct lines been performed depending on criteria. Without providing any variable its being performed on one player as that player which triggered command. Will have to close. If you have any extra information, please open new ticket with anything you can add to debug this issue.

**Comment by CloudeLecaw** [comment]
I added the playerName Variable to the enchant commands of the custom aliases.this solved the Problem for us.
