### ISSUE TITLE
lfix does not work on 1.16.x versions?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5148]
the lightfix command seems not to be supported on newer versions of spigot/papermc

![Snag_82fde6b](https://user-images.githubusercontent.com/12080017/108779839-cd37ce80-7567-11eb-9448-1d98e595a587.png)

![Snag_83009b1](https://user-images.githubusercontent.com/12080017/108779858-d32daf80-7567-11eb-8d5b-a128d7e72bea.png)

**Comment by Zrips** [comment]
As of 1.14 version lfix broke due to change in how light is being calculated, which was mainly done by client and not by server. For time being this is none working and until i can figure out how to force light update client side it remains disabled. Dont really even have broken map with light glitches as this is really rare situation, if you have any, send it to me over discord for testing.
