### ISSUE TITLE
Some high values at Timings?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5278]
Hi, I wanna ask about these values in timings?
![image](https://user-images.githubusercontent.com/18662086/111034359-7fe7a800-8415-11eb-83c7-f7ed17bba331.png)

![image](https://user-images.githubusercontent.com/18662086/111034386-a86fa200-8415-11eb-8667-d6e60dcbd7d4.png)
But I don't know that I'm using bossbar somewhere

https://timings.aikar.co/?id=f38815f6b43549e9a0c3656042b81018
https://spark.lucko.me/PgpT340j4p

I swtiched completely from using ctellraw to msg, broadcast or ctext, so what can now cause the problem?

**Comment by Zrips** [comment]
Bossbar manager and chunk loading, will do some investigation. Maybe bossbar compass enabled or you are doing something with them?

**Comment by bobhenl** [comment]
But I don't think that so many players use bossbar compass.. And by logs no one enabled it. Cause I really don't use anything that uses bossbar, max compass like you mentioned... but if it wasn't enabled and only VIPs can enable it... and there were just 3 of them online since restart, then I don't think that compass could cause lag.

**Comment by bobhenl** [comment]
Same for holograms 
![image](https://user-images.githubusercontent.com/18662086/111188051-eb1bb080-85b4-11eb-9027-3dc6a34b1e88.png)
https://timings.aikar.co/?id=7e03f6888cfa4ef29ed39f98808c358b#plugins
And may portal too. When I use it on my Lobby server.

**Comment by bobhenl** [comment]
And when I switch vanish, there are high values too from some reason.
https://timings.aikar.co/?id=9b4ba4489e614db3bc12983a82a816ef
![image](https://user-images.githubusercontent.com/18662086/111391175-5e581c00-86b4-11eb-8ec5-496e039a321e.png)
Look at the count

**Comment by Zrips** [comment]
Plugin isint magic, if entire server starts to lag due to its limitations in how many players it can handle, then any action could be shown in timings even if it would not be issue with stable server. Its hard to say why exactly it creating extra load, but this 1007863 creature spawn event trigger is something for you to look into. 
will do some optimizations relating to vanish and creature spawn event. 
For holograms, you might double check if you have some heavy duty holograms containing allot of dynamic variables with rapid update intervals.
