### ISSUE TITLE
click:[value]! isn't working for entities (armorstands)?

### ISSUE THREAD

**Issue by bobhenl** [Zrips/CMI#5296]
Hi, I wanna ask if it's bug or if this specialized command value is only for blocks like is mentioned here https://www.zrips.net/cmi/commands/specialized/

**Comment by CloudeLecaw** [comment]
U cant check for entities;)

**Comment by bobhenl** [comment]
But for holograms you can click, so why not for armor stands?

**Comment by CloudeLecaw** [comment]
U mixed uo things

Hologramms are objects created by a plugin with a database that has entries about the hologram. So ubcan check and interact with it. It doesnt matter that holograms are mostly made with hidden armorstand because here we have a database behind.

The armorstand itself is a vanilla living entities. To check for this you would need Something that scans for all armorstands in the world or arround you and checks if it can interact or not.
This would need a check for all types of living entities like creepers zombies chickens...etc.. and it would need a plugin that gives all entities (or for your case may just all armorstands inna world) a database entries.

Not why? Acept the fact that its not possible to use check for them ;)

Please next time dont considern not existing feature as a bug. Your bug is a Feature request
So you can go to the new discussion here and ask for a Feature to track all armorstands to be able to check them in commands.

**Comment by bobhenl** [comment]
OK, I understand your reply and agree that it would have big performance impact if it has to check all entities. I just firstly thought it could be possible maybe somehow, but ok.
