### ISSUE TITLE
Critical Vault Issue

### ISSUE THREAD

**Issue by mare-on** [Zrips/CMI#5302]
**Description of issue:**
Hi, something really bad happened to me what I must report to be fixed.
This issue happened with version 8.8.2.2 while enabling CMI.
Exception state bellow caused for me change lang file to default EN and disabling of all Aliases.

---

**NORMAL STATE:**
```
[11:03:15] [Server thread/INFO]:   Vault was found - Enabling capabilities. Economy: CMIEconomy
```

**EXCEPTION STATE ON NEXT SERVER RESTART:**
```
[23:03:08] [Server thread/INFO]: [CMI] Vault was found but economy engine is missing. Use one from list provided in https://dev.bukkit.org/bukkit-plugins/vault/
[23:03:08] [Server thread/INFO]: Vault was found but not economy plugin, you will have limited economy support
```

---

**Cmi Version** 8.8.2.2

**Server Type:** Paper

**Server Version:** 1.16.5-b553

**Relevant plugins:** Vault 1.7.3

**Comment by b01w** [comment]
Enable economy in your config, get an economy plugin such as shopgui plus.

**Comment by mare-on** [comment]
Read again my issue.... I have economy enabled and everything about economy works great but after updating CMI to newest version there is a problem where after first restart on my server ran everything fine and 12 hours later after next restart everthing is just randomly fucked up and IDK why... I didn't changed anything between those restarts and I'm scared about happenning it again.

**Comment by Zrips** [comment]
@mare-on 
If files got reset this could indicate that you had miss format in them and it went back to default state while broken file should have been placed in backup folder. Simply check previous server startups or basic /cmi reload instances with errors following them at some point it might simply broke 
as an example this what happens when you have formatting issues in config file and you tried to reload it
![image](https://user-images.githubusercontent.com/10416201/112013566-cb473800-8b32-11eb-95c8-4b57117d7d80.png)
any error messages which look something like 
![image](https://user-images.githubusercontent.com/10416201/112013674-e5811600-8b32-11eb-83da-f2351daa370e.png)
will be result of miss formatting in your file

**Comment by mare-on** [comment]
You know what... just forget about that. I know what happens if there is any issue with config files but in this case the console was perfectly clean. This bug happened to me only once sooo maybe it was just really random incident and since then is evertyhing fine.

I just wanted to know how is it possible that once CMIEconomy with Vault was loaded well and couple hours later not.
