### ISSUE TITLE
Error when using "sethome" command

### ISSUE THREAD

**Issue by xGlenor** [Zrips/CMI#5306]
Cmi Version: 8.8.1.1
Paper 1.16.5

Hi, I am using your CMI plugin with AAC (Anti Cheat) plugin The problem is when I use the "Sethome" command I get this message:
"You can''t perform this action in this area"

I am able to fix this by setting the "interaction" option to false in AAC config. I wonder where to report it. Here or at the author of AAC?

Is there a chance to solve this problem?

**Comment by Stoniasawsome** [comment]
try cmi sethome, on one of my servers sethome, and cmi sethome cancel eachother i have an alias set on that server so i think ive done something wrong, but its worth a shot

**Comment by xGlenor** [comment]
Should I check on your servers? Or on mine? Because I don't know if I understood correctly

**Comment by Stoniasawsome** [comment]
if you have set aliases for sethome, just try cmi sethome and see if it has a different outcome

**Comment by xGlenor** [comment]
I just checked, same problem

**Comment by Zrips** [comment]
This is mainly due to CheckBlockBreak option, which fires block break event when you try to create home and checks if player can break blocks in that location and can prevent home location creation if player is not allowed to break blocks in that location. Mainly used in pvp servers to prevent players creating homes in some ones protected area. Simply set it to false in config file and issue will get resolved.
