### ISSUE TITLE
VanishListener lags with minecart

### ISSUE THREAD

**Issue by Kapitowa** [Zrips/CMI#5327]
**Description of issue:**
Server laggy with this event. Server lagging, when player in vanish use minecart.
![image](https://user-images.githubusercontent.com/62211966/112032855-e1162680-8b4d-11eb-80c1-a4f29a8b82e7.png)

**Cmi Version (using`/cmi version`):** 
8.8.2.3
**Server Type (Spigot/Paperspigot/etc):** 
Tuinity
**Server Version (using `/ver`):** 
1.16.5

**Comment by Zrips** [comment]
You have 437 515 490 move events, dont know what's the time frame, but it looks allot more then it should be. 
For event itself, its completely blank event listener in 8.8.2.3 so it cant create any actual load on server. You might want to recheck if you actually have 8.8.2.3 or its older one which contained some code in it before it got removed due to similar issue. At this moment this cant be caused by that version of plugin as it does nothing during that event.
