### ISSUE TITLE
/Cmi glow Issue

### ISSUE THREAD

**Issue by MasonKidder345** [Zrips/CMI#5330]
**Description of issue:** /cmi glow works but it only makes my color white, if i choose a color from gui or with /cmi glow <color> it just makes it white.

**Cmi Version (using`/cmi version`):**  8.8.2.5

**Server Type (Spigot/Paperspigot/etc):**  Paper

**Server Version (using `/ver`):** 1.16.5

**Comment by CloudeLecaw** [comment]
hehe old issue that may comes from mysqlor other plugin.

You could try Spigot + CMI (clean!) + your Permission plugin nothing else

You will see the glow color change.
We also have this problem since years and accepted this behave because there was no solution for it

May there is  reason for this but the devs where never able to point it out

**Comment by Zrips** [comment]
Compatibility issue with another plugin. At this moment we can only live with that as there isint good solution until we have appropriate way to handle players glow color without changing bunch of other criteria.
