### ISSUE TITLE
why we have /cmi balance?

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#5357]
When looking into the commandlist u may notice fast
CMI has
/cmi money (playername) -cmi money [pay/give/take/set] [playerName/all/alloffline] [amount/%rand/1-1000%/1%[min-max][playerName]] (-s)
and
/cmi balance (playername)

well both can seems to do the same...

So why we have an extra balance command here?

Would it be simplier to have /balance in alias.yml leading to /cmi money (playerName)?

permissions:
cmi.command.money
cmi.command.money.others

normlay the play has the money permission... sp the /cmi balance itself is totally unneeded.. So why it exists?

**Comment by Zrips** [comment]
It does the same thing because /cmi money redirects to /balance command. Its  just a bonus behavior for /money command and not the other way around. having dedicated balance command is always nice if you want to give access to it for some one while having better control over your actual balance management.
