### ISSUE TITLE
itemshop Unable to successfully purchase and sell

### ISSUE THREAD

**Issue by dd880602** [Zrips/CMI#5458]
https://paste.helpch.at/raw/vevicidero
https://imgur.com/A0ndF3f

**Comment by mrfloris** [comment]
Forge? I am not sure CMI works on forge servers.

**Comment by Zrips** [comment]
This looks more issue with your server not processing hex color codes properly and not CMI in general, as its failing on server side when trying to parse hex code, more specifically this part "Caused by: java.lang.NumberFormatException: For input string: "§#§d§5§9§1§a§4" "which is not and error of CMI
