### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by LivingDarkness** [Zrips/CMI#5496]
put a placeholder that says if the player is online or offline

**Comment by CloudeLecaw** [comment]
You allready have that. Simply use
Cmi info on a player or other
Most commands allready have online or not in ita responce.

**Comment by LivingDarkness** [comment]
> Lo hai già. Usa semplicemente le
> informazioni Cmi su un giocatore o altri
> comandi già presenti online o meno.
> 
> potresti anche creare un alias personalizzato come:
> 
> ```
>   isonline:
> 	Cmds:
> 	- asConsole! ifoffline $1 msg! [playerName] &c$1 is not online.
> 	- asConsole! ifonline $1 msg! [playerName] &2$1 is online.
> ```
> 
> ora puoi eseguire / isoline Player e riceverai una risposta.

I need the placeholder because I have to use it on a gui of another plugin.

**Comment by CloudeLecaw** [comment]
why dont you use prhase other and player extation of papi then?

**Comment by LivingDarkness** [comment]
where can I find it?

**Comment by CloudeLecaw** [comment]
[install PlaceholderAPI (spigot)](https://www.spigotmc.org/resources/placeholderapi.6245/?__cf_chl_jschl_tk__=567e408d472605107b91b689880d0a7c3b9d16eb-1619509627-0-AUojgcDwZ2hFRhHHDSkWdO9bogWOAESubL9_wSf2Aa3-EB4PR0RO1bhnKLoQioAkTyZxFDfnH4soEWWiPoPOw1KVgvtZWKU12sC6RIgrsY1xiRiZbL2Iog8-i1-a7SbHMqQhz3jvp3td2yqZrWMFO-5mk-wdmXalLEUcaxICS97Ns9qT9p1hWWnlv8U2Fgw_eQSROlGwrnhZnncMQEUlSyhV3wxQ5-jmKoOB6MoCzyPSgtDf7nT11yLPovsI_TntObDnYYiMjAXZy3PLoAx0yXG_Na3kOr8RmGxTEHCecA8ms5K9SMXD8zRRM99ZBcuS-PlqkX1FGSi90LheyUSmIs6ga5VgrlTRT6KwMqcZvw74lmbeyBVDt_O5Ud3Gru9i2bNmSjbc0ydgL803J_-4QkjTFpp1K1ZMgyXh4WMHDOl_5GvJ0z0YDWjijXgMnLwfcQ)
install the extations ingame by typing `/papi ecloud download Player`
install phrase other extation by typing  `/papi ecloud download ParseOther`
restart server
now you can use placeholders of other players in this structue:
`%parseother_{username}_{placeholder_without_percent_signs}%`

so you placeholder now would be `%parseother_{PlayerName}_{player_online}%`

Note your plugin where you want to use this placeholder must be hooked (supported) to placeholders from PlaceholderAPI
If not, ask the dev of it to support it. He should add it because its the best solution to work with placeholders from other plugins and also give its own placeholders outside to other plugins

**Comment by LivingDarkness** [comment]
I want you to tell me if the player is online or offline

**Comment by CloudeLecaw** [comment]
This is what this placeholder does

**Comment by LivingDarkness** [comment]
I put the placeholder %parseother_ {PlayerName} _ {player_online}% but it doesn't work

**Comment by CloudeLecaw** [comment]
ok.. i aspcect u installed PlaceholderAPI on your Server and also the two extansion i wrote above
and also restarted the server on it to take effect.

`%parseother_ {PlayerName} _ {player_online}%` 
an axample would be
` %parseother_ {Cloude_Lecaw} _ {player_online}%`

Dont use playernames that never played on your server (means they have to be joined minimum once!)

Where u try to use this placeholder if it does not work for you? You really should start explain. Saying simply it does not work is not the right way to find the problem.

**Comment by LivingDarkness** [comment]
but then I have to put the name of a player, and if I put another placeholder instead of {playername}? can you?

**Comment by LivingDarkness** [comment]
so let me explain, I created a gui with various statistics of a player, I miss the placeholder to see if the player is online or offline, I cannot put the name of a player, it depends on the player and he has to tell me if he is online or offline.

**Comment by CloudeLecaw** [comment]
This is why i said i have to descripe what you wanne do >.>

If your using
`%parseother_{LivingDarkness}_{player_online}%`  then this is for the player LivingDarkness
In this case if you have 20 players u need this placeholder 20 times each time with the playername of it inside

So where your statisics that the names from they should show you?

**Comment by LivingDarkness** [comment]
and if i can't use a placeholder for all players it's useless, at this point it's better to add a placeholder to cmi that does this thing

**Comment by CloudeLecaw** [comment]
u can
%parseother_{placeholder_for_username}_{player_online}%

this Placeholder for username must come from your GUI Statisic

**Comment by LivingDarkness** [comment]
I put the placeholder% parseother_ {placeholder_for_username} _ {player_online}% but it doesn't work, what am I wrong?

**Comment by CloudeLecaw** [comment]
This means your "placeholder_for_username" does not work

**Comment by mrfloris** [comment]
Most gui plugins have an internal placeholder in their config like [player] or %player%, look at other examples in that plugin's configuration it might disclose it. You can then use that nested.

That said, yes, cmi having offline/online for a player would be handy. %cmi_user_online% resulting in true/false.

**Comment by Zrips** [comment]
Will add basic %cmi_user_online% placeholder for this one

**Comment by mrfloris** [comment]
Awesome
