### ISSUE TITLE
bbroadcast not working when server is empty

### ISSUE THREAD

**Issue by blek-id** [Zrips/CMI#5505]
**Description of issue:**
When running /bbroadcast command, it will only broadcast to where the command is run, and not to other servers when the original server is empty

steps to reproduce
a. have 2 server with bungeecord, lobby and survival
b. connect to survival, make sure lobby has no players
c. run /bbroadcast command from lobby with console

expected result
broadcast is shown on both lobby and survival

actual result
broadcast is only shown on lobby
---

**Cmi Version (using`/cmi version`):** 8.8.3.6

**Server Type (Spigot/Paperspigot/etc):** Paperspigot 592

**Server Version (using `/ver`):** 1.16.5

**Comment by Zrips** [comment]
That's due to how bungeecord works in general, which requires atleast one player to be online before we can send cross server messages like this. For time being there is no fix we could add to resolve this one without creating separate dedicated system which would work on completely different level than it is now.
