### ISSUE TITLE
MOD items to worth.yml

### ISSUE THREAD

**Issue by dd880602** [Zrips/CMI#5516]
I use Mohist server
I hope to add MOD items to worth.yml

**Comment by CloudeLecaw** [comment]
Its not possible. You need to use a shop plugin here.
Worth.yml is just as it was attented to be there to have a little basics for vanilla items.

Same comes with custom recipe materils. Just for vanila items.

Sorry to tell that :( but sugestions and requests for both exists in discussion since years  now :3

**Comment by Zrips** [comment]
Moded items are not something i have plans to make special support for, to many variables at play here to take into consideration when dealing with custom made ones.
