### ISSUE TITLE
Auto Updating CMI [With a key and server ID]

### ISSUE THREAD

**Issue by 4lve** [Zrips/CMI#5535]
Hello it would be really nice if you could add automatic updates to CMI. I have a suggestion so you only can update non-pirated versions.

You could setup some kind of service where the plugin can download the jar itself and to verify the purchase you could:
In CMI config you could add a key that you need to verify your purchase to get and to avoid people sharing that key you can add a tracker to each Minecraft server to track the Minecraft server ID on someway. Then you need to apply for both the key and the server id.

Both these factors will make it harder to pirate. But if they think this i too hard you could update manually.

**Comment by Zrips** [comment]
To much of a hassle just to have auto updater which will be disabled by default in any case. And you should avoid having any plugin on auto update anyways. Having auto update mechanics would mean that we should have some way to publicly store plugin file without exposing it to everyone. Could be minimized access with specific keys, but that would require some sort of automatization on multiple levels. 
I do have more important and more needed updates in the list, so this even if it will come, it will not be any time soon, due to low need and allot of work surrounding it.
