### ISSUE TITLE
Error when first player logs in related to hex colors, cmi ctext, CMI placeholders, and Featherboard

### ISSUE THREAD

**Issue by Momshroom** [Zrips/CMI#5621]
**Description of issue:**
When I have a ctext set to the MOTD in the config, when the first player logs in after a restart, we get this error.  If I remove the motd, the error no longer occurs.   

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://paste.gg/p/Momshroom/363a4485dda1461a8010c829571f0a2f
```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
# Defines name of customtext on players login to server. To disable just set name to non existing customText
Motd: news
```
**CTEXT for news **
```
<NoAutoPage><NoAutoAlias><NoReqPermission>
&f>>>>>>>>>>>>>>>>&b&lTrek&7&lNews&f<<<<<<<<<<<<<<<<<<
&f** &b&lWeekly Contests!! &7&lThis week: &2&lsugar cane harvested!! &f**
&f** &7&lNew jobs quests available for builder job! Do &b&l/jobs quests &7&lto see!
&f** &7&lWant to play in our &cCrea{#yellow}tive{#green} wo{#blue}rld{#purple}? &b&lAsk staff!
&f** &b&l/News &7&lto see this again &f**
&d&ltest server!
```
---

**Cmi Version (using`/cmi version`):** 
[21:46:03 INFO]: --------------------------------------------------
[21:46:03 INFO]: CMI plugin version: 8.8.4.4 MySQL-> 8.8.4.6
[21:46:03 INFO]: CMILib: 1.0.0.2 
[21:46:03 INFO]: Server: Paper(735) 1.16.5-R0.1-SNAPSHOT
[21:46:03 INFO]: CMI economy: Disabled Vault: 1.7.3-b131 CMI Chat: Disabled 
[21:46:03 INFO]: Modules -> 47 enabled 8 disabled: spawnerProximity, flightCharge, disabledEnchants, mirror, ranks, moneyCheque, spawners, spawnerCharge
[21:46:03 INFO]: --------------------------------------------------

**Server Type (Spigot/Paperspigot/etc):** 
Paper

**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-735 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Relevant plugins (Delete if this isn't needed):**
FeatherBoard version 4.30.0

**Comment by Momshroom** [comment]
I've just realized this is likely due to FeatherBoard trying to parse the CMI hex colors as placeholders. (Ie, it's trying to parse {#yellow} as a placeholder).  Do you have any suggestions on how to stop it from doing so, or can CMI fix this issue on your end?  Thanks!

**Comment by Zrips** [comment]
Yea, its an issue with FeatherBoard. I cant really fix that at my end, but you could try using actual hex color codes instead, like {#FFFF00} or simply inform FeatherBoard dev so that he would avoid parsing anything what is not actual hex color code. I mean, this is fully an issue with FeatherBoard trying to parse something what should not be, but as it doesn't perform any rudimentary checks before doing so you have this error. 
It seams that its grabbing letters after # without checking if it contains valid hex code letters which can only be A, B, C, D, E and F. You can point that one too. Its easy fix from his end.
