### ISSUE TITLE
CMI and Plotsquared 5 generate errors

### ISSUE THREAD

**Issue by Malachiel87** [Zrips/CMI#5679]
**Description of issue:**
When i use CMI and plotsquared it spam this error https://pastebin.com/SH32rwYT, i went to discord and they say is CMI Fault doing something nasty

---

**Cmi Version (using`/cmi version`):**  Versione di CMI: 8.8.4.8 MySQL

**Server Type (Spigot/Paperspigot/etc):**   git-Tuinity-"df76b3c" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) - happen also with Paper as well

**Server Version (using `/ver`):**  1.16.5+ Protocolsupport

**Comment by Zrips** [comment]
CMI doesn't do anything nasty. From logs is seams that player gets teleported to spawn on login, due to your usage of Tuinity which is fork of paper spigot, we are using async teleportation to get better performance, which is the case by your logs. After that it seams that PlotSquared derps out. Even tho its CMI which initialized teleportation, PlotSquared failed to handle async teleportation which is a part of PaperSpigot and its forks. You might want to revisit their github about this issue and point that one out, maybe they are not aware of paper async teleportation's as this entire issue looks to be relating to issue with their code not being able to handle multithreading while getting player list

**Comment by mrfloris** [comment]
Plotsquared is on version 6, and CMI is on version 9, I've used both on 1.16.5 and 1.17.0 and seems to work fine. I recommend trying to upgrade (after making a backup of your server first) and see if being current resolves the issues you're having.
