### ISSUE TITLE
Can the comment of config not be updated when the server is turned on? This will increase our workload too much.

### ISSUE THREAD

**Issue by MuChen886** [Zrips/CMI#5692]
Can the comment of config not be updated when the server is turned on? This will increase our workload too much.

**Comment by Zrips** [comment]
Are you talking about ability to change locale of comment section in config files?

**Comment by MuChen886** [comment]
Yes, starting the server will restore

**Comment by Zrips** [comment]
Comments are hard coded to provide basic explanation what does what. Even having comments for config sections is relatively rare as its not that simple to handle, while allowing comments to be modified without changing them is even more complicated task. Will keep this in mind, but for time being it will remain as it is, due to time restrictions and huge amount of that would be required to make this happen.
