### ISSUE TITLE
[SVIS] Console Spam with ChunkyBorder Integration

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#5714]
**Description of issue:**
Heya. Getting pretty significant error spam with ChunkyBorder after the recent ChunkyBorder update - unsure if it's an SVIS thing or a CB thing so posting it in both places. Spam shows up regardless of whether the SVIS integration is enabled. Looks like it's due to CB's changes to the center point of the border. Was also getting the spam on SVIS 3.0.3.5 but wanted to wait until SVIS updated before making a report in case it was a compatibility thing (idk). 

**ERROR:** https://gist.github.com/mercurialmusic/96ea289df3b0e1353137a77dfc32247b

---

**SVIS Version:** 3.0.4.0 and CMILib 1.0.2.0

**Server Type:** Paper

**Server Version:** git-Paper-777 (MC 1.16.5) on Java 16

**Relevant plugins:** [ChunkyBorder 1.0.38](https://www.spigotmc.org/resources/chunkyborder.84278/)

Thanks as always! You rock.

**Comment by pop4959** [comment]
Hi, author of ChunkyBorder here. It looks like this issue is caused due to the fact that Selection Visualizer currently supports my plugin by directly hooking into its implementation. This is okay for the moment, as there is no proper API available, however obviously breaking changes may occur and are to be expected. In this case it looks like you're trying to access `getCenterX` which used to return an `int` but now returns a `double` (since the latest version now supports selecting the center and radius using decimal values).

@Zrips Fixing this may be as simple as just updating the dependency version of ChunkyBorder to `1.0.38` within Selection Visualizer's build script. Also just as a heads-up, I do plan on refactoring some code in the future which will most likely break direct integrations like this again, but I'll try to have an API out before then. It would be great, if at that time, you could switch to using the API. Until then, if you wish to keep in touch please add me on Discord (pop4959#1781) and I can try to notify you of any upcoming changes which could impact compatibility with this plugin.

Until then, @mercurialmusic may want to use the previous release of Chunky/Border on their server (there should be nothing wrong with doing so, as it should still work on 1.17, just missing newer features for now).

**Comment by Zrips** [comment]
@mercurialmusic 
Could you provide actual world border setup? As of some testing it look to have some issues with more none standard shapes like diamond, but everything works just fine with circle or square type borders.

**Comment by Zrips** [comment]
@pop4959 
Its not an issue with int and double values, as of error it looks more like an issue with actual ChunkyBorder plugin not being loaded in properly or recognized or something. As its indicating missing method which obviously exist but creates this stack trace.

**Comment by mercurialmusic** [comment]
@Zrips Here's my borders.json file: https://gist.github.com/mercurialmusic/4a0f0cdceaa4b0309f5c1bc9c0ad7a23

Mine are all circle or square, although so far I'm not seeing the spam after the update to SVIS 3.0.4.1. Potentially solved? 

Thanks for looking into it!

**Comment by Zrips** [comment]
Changed some core mechanics for chunky handling, dint encountered your issue while testing, so who knows. If issue reappears let me know.

**Comment by pop4959** [comment]
Strange, I was very certain it had to do with the method signature changing. Either way, I could not test since I do not have a copy of this plugin. Glad to see that it's fixed though :)
