### ISSUE TITLE
[request] money message gotmoney on command /cmi money give

### ISSUE THREAD

**Issue by iaxedu** [Zrips/CMI#583]
When you do **/cmi money pay examplename 1000** examplename gets a message that he received money from someone. 

The command **/cmi money give examplename 1000** does not send this message. The request is that /cmi money give also sends a confirmation message to the receiver. 

EDIT: Also add in feedback for `/cmi money take [username] 1000`.

Thanks in advance! Great work on this plugin!

**Comment by CloudeLecaw** [comment]
ist this part of your economy? give,pay,sent, etc?

**Comment by RustyDagger** [comment]
I also ran into this just yesterday, seemed a little odd it provided no feedback However I just sent the player an additonal message stating that X had been added or taken because i was working with the Warning system adding an extra command was not too complex most scripted type plugins allow for that and if your doing it manually then rip.

**Comment by CloudeLecaw** [comment]
on a testsystem i created an alias that took the place of the command (CMI customalias) and gave the measge Feedback after to the Player that got the Money. CMI has nice placeholders for These Kind of meassages :-)

**Comment by LogGits** [comment]
Edited post to include feedback for take aswell.

**Comment by Zrips** [comment]
Will be added with next build. and -s as option to hide those messages.
