### ISSUE TITLE
Anchor doesn't work when the players died

### ISSUE THREAD

**Issue by MusicTW** [Zrips/CMI#5862]
https://imgur.com/jPVOa5g
Anchor doesn't work when the players died
---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#######################################
##  https://pastebin.com/LT9CxWyx  ##
#######################################
```

---

**Cmi Version:** 
![image](https://user-images.githubusercontent.com/52475422/125391997-f9999d80-e3d7-11eb-9435-fb5fdf8a1375.png)

**Server Type:Paperspigot** 

**Server Version:** 
![image](https://user-images.githubusercontent.com/52475422/125392053-11712180-e3d8-11eb-8c8d-8ce34e1ccad9.png)

**Comment by Zrips** [comment]
Retest without any other plugin, as this could be interfered by another plugin amd upi respawn being set to something else then it actually needs to be. Will increase vent priority to maybe help out with this issue, but in general its most likely caused by another plugin changing players respawn point after CMI sets it.

**Comment by MusicTW** [comment]
ok thx
I just found the problem that is Multiverse-Core will force to respawn at spawn
