### ISSUE TITLE
[Request] Unmute command

### ISSUE THREAD

**Issue by ignissak** [Zrips/CMI#598]
Can we please get /unmute command? I have no clue how to unmute muted player.

**Comment by CloudeLecaw** [comment]
https://github.com/Zrips/CMI/issues/568

**Comment by ignissak** [comment]
We want unmute command,
not an alias. It will more spam the chat.

**Comment by TheWranger** [comment]
https://github.com/Zrips/CMI/issues/568

**Comment by CloudeLecaw** [comment]
> We want unmute command,
> not an alias. It will more spam the Chat.

u got an alias to creat it, dont be a lazy nut man^^

and if u wanne spam your Chat, then you can add as much broadcasts and private maeasges as u want instead of the actionbar..the actionbar was just a Suggestion Nothing elese.. The main unmute command is the first part.

**Comment by MCTyler** [comment]
I suppose we code learn to code and add all sorts of our own features...whats wrong with /unmute? It just make sense if you can /mute [PlayerName] then there should be /unmute [PlayerName] IMHO.

**Comment by CloudeLecaw** [comment]
u also can unmute them wit hcustomaslias ;) 
ahas Nothing to do with coding,
it more using a CMI feature Nothing else ;)


but i would not wonder if ZrIps will add this unmute since there where allready added so much u*********y things just because other owner dont want to use CustomAlias ^^

and if u wanne unmute someone simply do /cmi mute [playerName] 1s -s
done is the perfect unmute, same for unmutechat - /cmi mute [playerName] 1s -s.. done
In customalais the [playerName] simply must be a $1 ..done
oh an chatprintouts off all Kinds can be done this way


i also could ask why there is no /ungod,/unfly? /untogod and /untfly?
why? because ist not needed. and the disableding od them also work with a simliar logic ->
u use one command for enable and disbale it.

**Comment by TheWranger** [comment]
The reason there is no `/ungod` or `/unfly` is because those are toggle commands, completely different from `/mute`. Using custom aliases for this sort of thing is a cheap workaround and if anything makes a server look less professional if they don't even have an unmute command.

**Comment by CloudeLecaw** [comment]
god and fly goggle? yes and no, i had it often enough now Special when the playervar is comming to ti, that this  "toggle" in CMI does not work correclty and i have to force it with the extra Option "false" in the command

**Comment by MCTyler** [comment]
I think the whole point of this board is a two-way conversation between the purchaser and the Dev/Owner. It's not a place for discussion of what some consider alternatives.

**Comment by CloudeLecaw** [comment]
as a Result and thinging about the conservation with u, i created a own Request now ;)..Feel free to suggest :P
https://github.com/Zrips/CMI/issues/608

**Comment by CloudeLecaw** [comment]
The Unmute command was done. So pls close this.
