### ISSUE TITLE
Invincible time that cannot be forbidden

### ISSUE THREAD

**Issue by FZDNSZYT** [Zrips/CMI#6013]
After the TP is transmitted, there will be a few minutes to be unable to attack and be attacked. After looking for the configuration file, it cannot be solved.

**Comment by CloudeLecaw** [comment]
Cmi offers no behave setting like that... So it was normal you could not find it.
Well have you checked for other plugins or doing a littl offline test with just serverjar +cmi + cmilib + vault + cmieinjector ( if used) + permission system   take a look there, you should notice your issue is not reproduceable with this plugins.

**Comment by Zrips** [comment]
@FZDNSZYT 
There is section Teleport->Invulnerability which would define how long you cant take damage after you perform teleportation, tho its only limited to max 1minute and defaults to 5 seconds. You can always check current no damage mode with /cmi info command and hovering over God section which will give you exact time left
