### ISSUE TITLE
The Only One Player sleeping can't skip night at the server (only one of the player at the server)

### ISSUE THREAD

**Issue by MusicTW** [Zrips/CMI#6133]
**Description of issue:**
if only one player at the server, when he/she is sleeping, the skip night message will show, but can't sleep through the night actually

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
https://pastebin.com/w50wbijj

---

**Cmi Version (using`/cmi version`):** 
![image](https://user-images.githubusercontent.com/52475422/132156692-a909e760-6acd-4791-8e56-e841acfee818.png)

**Server Type (Spigot/Paperspigot/etc):** 
PurPur
**Server Version (using `/ver`):** 
![image](https://user-images.githubusercontent.com/52475422/132156714-8d0aad0e-729b-490f-b2bf-81051b628e2d.png)

**Comment by MusicTW** [comment]
![image](https://user-images.githubusercontent.com/52475422/132156850-3589b4be-9a7c-4305-a867-56cf3171798e.png)

**Comment by Zrips** [comment]
If 100% of players are sleeping then night skip should be performed by server itself. Due to how minecraft handles sleep mechanic i cant stop it from performing actual night skip, so if you have 100% players in bed everything is done by server and CMI simply outputs that message informing that night will get skipped. If that doesn't work then issue is somewhere inside server itself and its configuration.

**Comment by MusicTW** [comment]
ok
