### ISSUE TITLE
Group tablist by permission rank

### ISSUE THREAD

**Issue by Bloodlex** [Zrips/CMI#6199]
Would it be possible to add sorting to tablist so Admins are on top, Mods beneath and so on? Thank you 🙂

**Comment by CloudeLecaw** [comment]
Long wished 1000 times,.and 1000 times was adding in discussion..so this.time too.;o

Would be more effictiv if users would rate and comment the discussion instead of opening a new one each time. So Open the Discussion tab, type in TAB and you will find enough other once where u might can rate and comment  this to upvote it.
