### ISSUE TITLE
cmi clearchat causes server to stop responding briefly.

### ISSUE THREAD

**Issue by hemanth4121** [Zrips/CMI#6366]
**Description of issue:**
Clearing the server chat makes the server stop responding, and causes TPS to dip in game.

---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
https://pastebin.com/ksREjEda
```
---

**Cmi Version (using`/cmi version`):** 
```9.0.6.1```

**Server Type (Spigot/Paperspigot/etc):** 
```Airplane (fork of paper)```

**Server Version (using `/ver`):** 

[23:16:52 INFO]: This server is running Airplane version git-Airplane-103 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 86fee6b on HEAD)
You are on the latest version!
Previous version: git-Airplane-99 (MC: 1.17.1)

**Relevant plugins (Delete if this isn't needed):**
 https://pastebin.com/6qUj1uzS

**Comment by Zrips** [comment]
This looks more like it was caused by loohp interactivechat plugin. /clearchat only sends to all players empty message made of 100 empty lines. From your logs it looks that protocollib intercepts this event and passes to interactivechat plugins which does something with it which creates this issue. You will need to get into contact with that plugin developer to sort it out why its lagging out so much.
