### ISSUE TITLE
[Request] Ability to define pickaxe types for breaking spawners

### ISSUE THREAD

**Issue by TheWranger** [Zrips/CMI#641]
A list in the config of pickaxe types that can break spawners with silktouch and pick it up. Similar to what SilkSpawners has.

**Comment by CloudeLecaw** [comment]
why this would be needed?
you can set it up the the Itmes Needs some enchant liek Silktouch II and this you can let your Players craft themself with CMIs custom Recripe Editor...

For example:
my Players Need 6 Diamaonds and 3 Obsidian in the Right Shape to Craft the a Silktouch 2 Stoneaxe and only with this axe (because of silktouch 2) they can collect the mined spawner if they have enough charges (charges also can be disabled if u dont work with them)

**Comment by TheWranger** [comment]
I don't know why you're bringing up custom recipes or silk touch levels.
I simply want to be able to select which types of pickaxes can pick up spawners (wood, stone, gold, iron, diamond).

**Comment by TheWranger** [comment]
I shouldn't have to do all of this just to stop silk touch wooden pickaxes from picking up spawners.

**Comment by CloudeLecaw** [comment]
a simple crafting recipe confuses your Players?
how old they are?..uhm better i dont wanne know ;)

**Comment by TheWranger** [comment]
This is how 90% of servers handle mining spawners and I simply want to be able to do the same.

**Comment by CloudeLecaw** [comment]
i see you are 90% ;)
There are more then enough Server that work with speicla items and not with simple vanilla items
why? because they want ppl to craft, them, or buy them etc..
this is what most Servers do. Allowing mine spawners by Default?
na never.. but allow for VIP?..yes this is what many Servers do even if the eulo just talks About cosmeticla Things.
