### ISSUE TITLE
The message types "requestSent and gotRequest" in the tpa command do not support placeholders.

### ISSUE THREAD

**Issue by Brancast** [Zrips/CMI#6512]
I am using the latest version of everything.

https://prnt.sc/24yjx78 / https://prnt.sc/24yjyg8

https://prnt.sc/24yk9nx / https://prnt.sc/24ykawx

**Comment by Brancast** [comment]
Also, the "exist" message format in sethome does not support placeholders.

**Comment by Brancast** [comment]
The "list" message format in home does not support placeholders.

**Comment by Brancast** [comment]
> The "list" message format in home does not support placeholders.

home:
    help:
      info: '&eEv konumuna ışınlar'
      args: (homeName) (playerName) (whoTeleport)
    info:
      list: '%testsds%(sample} {#8DE516}Sahip olduğun evler: '

**Comment by Brancast** [comment]
baltop not support placeholder.

**Comment by Brancast** [comment]
helpop "message" not support placeholder

**Comment by Brancast** [comment]
removehome -> list: 
not support placeholder

**Comment by Zrips** [comment]
There are few places which will not parse placeholders due to how those get handled. Main support is for already existing variable in a default message and in some cases general global variables as defined at top of locale file. Parsing actual placeholders is another thing on itself and can in general introduce some unvented behavior, like players intentionally adding placeholders into messages to get translated result back. For time being we will need to stick to what is already translated,
