### ISSUE TITLE
Invisible Armor Stands spawn after crash when players /sit

### ISSUE THREAD

**Issue by horsecraft** [Zrips/CMI#6527]
If a player is using /sit and sitting on the ground during a crash, an invisible armor stand (entity) appears. Players cannot interact with it or break it. The only way to remove is with the /minecraft:kill command.

---

---

**Cmi Version (using`/cmi version`):** Latest

**Server Type (Spigot/Paperspigot/etc):** 18.1 latest paper 

**Server Version (using `/ver`):** Java

**Relevant plugins (Delete if this isn't needed):**

**Comment by Zrips** [comment]
Armorstand are spawned in to create this sit effect which have specific settings including no ability to interact with them or kill them. Server crashing will result in this effect due to the fact that armorstand remains there without properly seat exit process. You can clean all those with `/cmi util removechairs` command
