### ISSUE TITLE
"uuid" is null

### ISSUE THREAD

**Issue by xiaoxianxiacao** [Zrips/CMI#6551]
**Description of issue:**
Some commands cannot be executed uuid prompt is empty
---

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
[03:44:58] [Server thread/INFO]: huaji52 issued server command: /cmi tps
[03:44:58] [Netty Epoll Server IO #3/ERROR]: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null
[03:44:58] [Netty Epoll Server IO #3/ERROR]: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null
[03:44:58] [Netty Epoll Server IO #3/ERROR]: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null
```

---

**Cmi Version (CMI9.1.0.5):** 

**Server Type (Spigot):** 

**Server Version (1.18 and 1.18.1):**

**Comment by WOLFI3654** [comment]
I can confirm this.
Same Issue on Server Version 1.16.5.
## Further details from my investigation:

> The Custom Chat Packets sent by CMI pass "null" into the ChatPacket Constructor as the uuid.
> Therefore the packet can not be properly serialized.
A quick look at the [protocol specifications](https://wiki.vg/index.php?title=Protocol&oldid=16681#Chat_Message_.28clientbound.29) defines the uuid as the sender of the message.
This information is said to be used in order to allow chat disabling on the client.

The Protocol also speciefies that an UUID with all bits=0 (new UUID(0,0)) will be treated as a kind of system message that is always displayed.

## Suggestion
Passing an instance of "new UUID(0,0)" instead of null in the MessageManager.

**Comment by mrfloris** [comment]
A temp fix could perhaps be to downgrade cmilib to 1.1.0.6 and set the cmilib config.yml to not auto update. 
let me know if that resolves it.

**Comment by WOLFI3654** [comment]
Downgrading to CMILib 1.1.0.6 indeed solves this issue.
Thank you very much :)

**Comment by Zrips** [comment]
@WOLFI3654 
Alternatively you can use paperspigot which avoids having this issue in general, but yea, will make some changes to address this issue across the board with next CMILib update
