### ISSUE TITLE
I don't give players permission to fly, but some players can fly after passing through the next portal.

### ISSUE THREAD

**Issue by NEIKI19914** [Zrips/CMI#6581]
**Description of issue or feature request:**

---

#### DELETE THIS SECTION IF YOU ARE SUBMITTING A FEATURE REQUEST ####

**ERROR (DELETE IF YOU HAVE NO ERROR):**
```
####################
## PASTE ERROR HERE ##
####################
```
I don't give players permission to fly, but some players can fly after passing through the next portal.
My server uses mysql

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
## PASTE RELEVANT CONFIG SECTION HERE ##
#####################################
```

---

**Cmi Version (using`/cmi version`):** 
CMILib1.1.0.8       CMI9.1.0.6
**Server Type (Spigot/Paperspigot/etc):** 
paper-1.18.1-152
**Server Version (using `/ver`):** 
windows11
**Relevant plugins (Delete if this isn't needed):**

**Comment by x1p** [comment]
Unfortunately you're not providing very much clues under what circumstances it appears to be happening.
I have a similar bug. Maybe the same. Who knows.

When teleporting to a certain world: some players with fly permissions get their fly turned on.
How they teleport is irrelevant. It's not related to permissions. Only a certain group of players have this in my case. Players who have every right to fly. The bug is that it's turned on somehow.

Check if you have this function enabled:
```yaml
WorldLimits:
  Enabled: true
```
If so, list every world you have here:
```yaml
  Fly:
  - world:False
  - world_nether:False
  - world_the_end:False
  - whatever_world:False
```
If you have players that have the ability to fly everywhere, make sure to give them the cmi.worldlimit.fly.bypass perm.

Note: this is only a workaround. Not a solution. The bug is still that CMI somehow decides to turn on Fly for no reason on world change on a random chosen world.

If you have more information, please add to this issue so the developer can get a clear picture of your issue.

**Comment by NEIKI19914** [comment]
OK, one of my players has a high delay and appears after logging in repeatedly for a period of time.
There is no error report in background.

**Comment by FONatureKoh** [comment]
This is happening to me as well, I realise, but it is only happening to one person, aka me. My other op don't have that problem.

**Comment by Zrips** [comment]
Should be resolved with next update
