### ISSUE TITLE
per:[permissionNode] doesn't work with LuckPerms?

### ISSUE THREAD

**Issue by J0schlZ** [Zrips/CMI#661]
Hi, sorry but my english is very bad.

I use LuckPerms and CMI on Spigot 1.13 and want to give a Player AdventureMode if he doesn't have
permission: player.canbuild

My test player does have the permission but CMI always acting like he doesn't have it.

EventCommands-Config:
`joinServer:
  Use: true
  List:
  - perm:player.canbuild#! gm 2 [playerName] -s
  - perm:player.canbuild#! say [playerName] cannot build
  - perm:player.canbuild! say [playerName] can build`

https://i.imgur.com/eGOd3v0.png

It always says: [playerName] cannot build

LuckPerms-Version: 4.2.17
CMI-Version: 8.0.1.0
Server-Type: Spigot
Server Version: 1.13 

Thank you

**Comment by CloudeLecaw** [comment]
sorry my dear this is not made for EventCommands
its made for customalias

**Comment by Zrips** [comment]
In general there should be no difference which permission plugin you are using as we are checking players permission access throw bukkit API and not throw that permission plugin. If something doesn't work, then issue could be due to wrong permission setup or specialized command setup. In general use /cmi haspermission command to double check if player has access to permission node.
