### ISSUE TITLE
ArmorStand blank item

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#6628]
**Description of issue:**
Hello, 
I just found a problem with the ArmorStands, when a player does not have permission to modify some options, it makes a blank, would it be possible that it is automatically put in the place where there is a blank (see image).

---

**Cmi Version (using`/cmi version`):**  9.1.1.2

**Server Type (Spigot/Paperspigot/etc):** Pufferfish-20 (MC: 1.17.1)

**Screen:**
![image](https://user-images.githubusercontent.com/75265787/152377739-7953f8e6-eb02-48b1-8064-79b861bd477b.png)

**Comment by Zrips** [comment]
Its not really a bug, it simply disables that slot if you dont have access to it. Moving around buttons isint best solution ether as you might get confused why button which previously was located in slot X got moved to new location, now its more in a fixed locations.
What i can do is to move around those buttons so that least used ones and least likely to be given access to would be in a place which would not ruin general look of it. Next update.
