### ISSUE TITLE
Ranks.yml SneakTime requirement miscalculation

### ISSUE THREAD

**Issue by klaidosHka** [Zrips/CMI#6655]
First of all, I think it's a statistics calculation problem, not the ranks system problem.
Instead of seconds it is calculating minutes for SneakTime.
Every `1 minute of sneaking is saved as 1 second`, that is seen the best when putting such requirement for ranks and then trying to see the progression through `/cmi rankinfo`.

---
**Cmi Version :** **`9.1.1.0`**

**Server Type :** **`Paper`**

**Server Version :** **`1.16.5`**

---
Also, maybe something can be done regarding the ArmorStands? To make them completely NOT interactable and yet showing their name above them, not under them. Or is it not really possible and would require additional hidden armorstand to be added, which would cause more problems? :C

(Asking, because it is quite a pain to create/edit/transfer XX holograms or else people steal all the items from the ArmorStands, even if they are in WorldGuard region and have assigned interactiveCommands onto them)

**Comment by Zrips** [comment]
Will fix sneak time with next update.
For holograms, you will need second armor stand to get name where it needs to be because that shift of nameplate happens on client side. You could simply place secondary invisible armor stand which would serve as name plate for that first one, but i have no plans to actually add specialized method to handle something like that.
