### ISSUE TITLE
ERRORS ON ITEMID 1.8.9

### ISSUE THREAD

**Issue by Betob89** [Zrips/CMI#6664]
I have found errors in some objects.
When you use the give command. I have uninstalled cmi and it delivers correctly. The object is the wood example LOG:2 gives you LOG:0

SERVER VERSION ISPIGOT 1.8.9
CMI VERSION: CMI9.1.1.3

**Comment by Zrips** [comment]
Will check it, but in general it would be a time to switch into using actual material names and not outdated and deprecated ones. Something like **/cmi give birchlog** or **/cmi give oaklog** will be allot more future proofed than old format which will get removed sooner or later entirely due to it being outdated and some what inconvenient.
