### ISSUE TITLE
Heads

### ISSUE THREAD

**Issue by JelmerNL** [Zrips/CMI#6680]
When I use /cmi head (player) it gives an old head from the player. How can I fix this?

**Comment by Zrips** [comment]
Player skin information is cached due to limitations in how often we can check out for actual information about current one. This should update on itself every 22 hours automatically as this is default update rate for each skin information. You can force this update with **/cmi skin update [playerName]**

**Comment by JelmerNL** [comment]
This feature is not supported on bungee network based servers. Is there any way to get around this?
