### ISSUE TITLE
Players can Use WASD in /afk with out the AFK module detecting them

### ISSUE THREAD

**Issue by WackoJacko22** [Zrips/CMI#6774]
**Description of issue:**
Players can move around with WASD while in /afk mode. As long as they do not move their mouse they can infinitely run around until kicked or any other movement controls.

Sometimes the afk system picks up the player, but has chance for it to not work.

**Cmi Version (using`/cmi version`):** 
9.1.3.2
**Server Type (Spigot/Paperspigot/etc):** 
Paperspigot
**Server Version (using `/ver`):** 
This server is running Paper version git-Paper-261 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 855637f)
You are 7 version(s) behind

**Comment by Zrips** [comment]
This is due to antiafk protection mechanics where in case players camera doesn't change then player will be counted as afk and simply using some anti afk contraption, like infinite water loop. This can be disabled, but at same time we wont be able to detect player moving in a loop to avoid being put into afk mode.
