### ISSUE TITLE
Hologram right click issue.

### ISSUE THREAD

**Issue by PastosBaran** [Zrips/CMI#6780]
While left-clicking on the hologram changes pages very quickly, right-clicking requires approaching the hologram. I will put the video about it below.

https://www.youtube.com/watch?v=ZYS7fAh9RqI

https://prnt.sc/wDWTTu4icFAV

**Comment by Zrips** [comment]
Due to latest changes in how we handle holograms we lost option to right click those, well, you still can if you hold item in your hand or you right click block behind hologram. Its internal weird minecraft behavior which will not fire any event if you right click air without any item in hand. Working on possible solution for this one but for time being this will be some what limitation. You could always switch back to old hologram click handling, but that one lacks some of the new features.
