### ISSUE TITLE
Vanilla Recipe Disappearing

### ISSUE THREAD

**Issue by mercurialmusic** [Zrips/CMI#7052]
### Description of Issue

Super weird thing happened with the vanilla campfire crafting and recipe in which it has completely disappeared from the game. Campfires cannot be crafted and they don't show in the vanilla crafting book (/recipe campfire still works fine). Not sure if others have gone missing, but that's the only one we've noticed so far. Removing CMI solved the issue.

### Version Information

```shell
CMI plugin version: 9.2.1.1 BungeeCord
CMILib: 1.2.1.0 -> 1.2.1.1
Server: Paper(387) 1.18.2-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-b CMI Chat: Disabled 
Modules -> 54 enabled 2 disabled: ranks, skin
```

### Errors

```shell
No errors
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by x1p** [comment]
Recipes are disappearing because normal players can push the newly introduced button to disable any recipe.
The permission `cmi.command.recipe.admin` is checked but despite that, everyone can disable a recipe!
How to enable them again:
- check your recipes.yml file
- check the section:
```yaml
Disabled:
  oak_wood: minecraft
```
- fix the recipes one-by-one in game by holding the base material, execute /recipe and turn them back on
- or remove this section all together and execute `cmi reload`

**This is so vital in a survival game that I recommend turning recipe off all together by removing the base permission, until this is fixed!**

**Comment by mercurialmusic** [comment]
Sure enough, it was in there. Thanks for the tip! Very strange that they would be able to do that when they don't have the perm! Will test with negating it and see if they still can.

**Comment by dan28000** [comment]
They can still even with the perm set to false

**Comment by mercurialmusic** [comment]
Ah yup. Looks like I've duplicated #7047 then. Will leave this as additional confirmation for now.

**Comment by Rexmen1** [comment]
Yep already reported this and not even a reply yet..

**Comment by mercurialmusic** [comment]
He's not one to ignore - I'm sure he'll get to it when he gets to it. It's not the end of the world.

**Comment by Zrips** [comment]
Issued hotfix to resolve this issue
