### ISSUE TITLE
Message bug for Kick and Ban

### ISSUE THREAD

**Issue by abenraged** [Zrips/CMI#7067]
### Description of Issue

Message bug for Kick and Ban

### Version Information

```shell
Versions:
CMI: 9.2.1.4 SqLite
CMILIB: 1.2.1.2
Server: Purpur 1.19-R0.1-SNAPSHOP

1. Bug kick

   info:
      defaultMessage: '&6( &c! &6) &7Zostales &cwyrzucony &7z serwera'
      cantKick: '&6( &c! &6) &cNie mozesz wyrzucic tego gracza'
      messageToAll: '&6( &c! &6) &6[playerDisplayName] &7zostal &cwyrzucony &7przez &c[senderDisplayName]'
      kickReason: ' &7za: &a[reason]'
      all: '&eKicked &6[amount] &eplayers from server'

Des: 
i can set only default (where prefix like [senderDisplayName] etc dont work)
or when i give reason for player so player only see kickreason:
u can edit section for kick like we have a temban?

2. Ban

If we ban a player with changed messages, he will get a correct message, but if the player wants to enter the server again, he will get a default notification
```

### Relevant Plugins

Nope

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by abenraged** [comment]
3. When u want mute player who never join the server we get message "Can't find player with this name" also u cant find this message for change in locales

**Comment by Zrips** [comment]
Can you elaborate more on first issue? Which exact line you are talking about, what you used and what result you got on your screen? 
For second issue, what command exactly are you using to ban players? Is it from CMI or another plugin? As in case you provided custom ban reason it should be shown on player ban event when he gets kicked and when he tries to rejoin.
For third issue, muting none existent player isn't really possible due to his data not existing at the moment, so we cant determine who needs to get this mute. You can change most generic locale lines inside CMILib locale folder, those got moved with CMI 9.x version to centralize locale files across multiple plugins to avoid duplicated entries.

**Comment by enragedprime** [comment]
So Ur first question:

When we kick player so he only see     kickReason: ' &7za: &a[reason]' this. Only reason

So 2 queston:

Im use /tempban when im tempban player so u see my custom message but when he again join he see default message from locales

**Comment by abenraged** [comment]
Still same isues lol nothing change please make this one template for all warn,mute etc. Cmi is great i dont want to use another plugin for bans etc.

**Comment by abenraged** [comment]
When u ban someone he see properly message but when he reconnect see english default message
