### ISSUE TITLE
/head giving the head of previous skin instead of current skin.

### ISSUE THREAD

**Issue by haids1** [Zrips/CMI#7174]
### Description of Issue

/head command is giving the head of a player's previous skin instead of a head of the current skin the player is wearing.
The following picture shows this issue: https://imgur.com/a/cgrAGLh

### Version Information

```shell
9.2.3.3
```

### Errors

```shell
No errors.
```

### Relevant Plugins

https://i.imgur.com/InEcQW6.png

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Head skin should get updated with next server restart. Due to how heads work we tend to avoid sending requests to Mojang servers for new skin data each time someone requests it as there is limited amount you can send per hour in total. What I can do is to add new command like **/cmil clearcache** to CMILib plugin which would clear records of skin and update it on next request. With next CMIlib update.

**Comment by haids1** [comment]
Hey @Zrips sorry to bother, but is there an estimated date for when the next CMIlib update will be released? Just so I know when the /cmil clearcache command will be available. Thank you!
