### ISSUE TITLE
[Feature] Add a -(dash) between the version in the jar name.

### ISSUE THREAD

**Issue by andrew121410** [Zrips/CMI#7236]
So Instead of `CMI9.2.4.2.jar` it would be `CMI-9.2.4.2.jar`

Every other plugin does this.

**Comment by CloudeLecaw** [comment]
your free to rename the jar files ;)

On Our Server we add _ between CMI and the Nummer and do this for each version so it become CMI_9.2.4.2.jar

I also could say... all other plugins do this xD  just because u see it for some.

Well i think this ticket can be closed. Solution is simple,,add the wished - by yourself each time :)

**Comment by mrfloris** [comment]
I think it's a super minor, low priority thing, to nitpick over this. It's really about convenience and readability. 

But I have to say, using some python or bash shell scripts for plugins to detect <plugin>*.jar vs <plugin>-<version or extra details>.jar, and then having to make an exception because cmi doesn't have the dash, complicates things slightly. haha. 

I wouldn't mind either way, if ALL zrips plugins could be like this format below, my life would be a little simpler:

```
<plugin>-<version>-<extra_info>.jar
CMI-1.2.3.4-beta.jar
CMI-5.5.5.5.jar
CMI-12.14.6.1-dev.jar

Jobs-1.2.3.4-beta.jar
Jobs-5.5.5.5.jar
Jobs-12.14.6.1-dev.jar

MobsFarmManager-1.2.3.4-beta.jar
MobsFarmManager-5.5.5.5.jar
MobsFarmManager-12.14.6.1-dev.jar

And not cmi1235.jar cmi1.2.3dev.jar or jobs_dev_1_2_3.jar
```

:D

**Comment by CloudeLecaw** [comment]
well i prefer

CMI_1.2.3.4-beta.jar
CMI_5.5.5.5.jar
CMI_12.14.6.1-dev.jar

Jobs_1.2.3.4-beta.jar
Jobs_5.5.5.5.jar
Jobs_12.14.6.1-dev.jar

MobsFarmManager_1.2.3.4-beta.jar
MobsFarmManager_5.5.5.5.jar
MobsFarmManager_12.14.6.1-dev.jar

so i rename most jar files (yes and also all Updates)
:-D

**Comment by CloudeLecaw** [comment]
so i am a small boy :3
