### ISSUE TITLE
checks for names with spaces seem not to be possible

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#7384]
### Description of Issue

checks for names with spaces seem not to be possible
in my example i tried

`- check:%cmi_iteminhand_displayname%==Maltes Schwert! msg! [playerName] OK `

Nothing happens may because of the Space in the name.. so it means you cant really
check for items with rarer names that mostly have more one word in its name

### Version Information

![Snag_15e0e80](https://user-images.githubusercontent.com/12080017/202582689-04c550ce-30ff-46ed-8752-59277eb2d6cb.png)

### Errors

no console error it simply seems not to work..

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Entire specialized check format is based on one word type deal which will only recognize it as specific check by lack of spaces. Having space support complicates things by quite a bit as now we would need to check entire input instead of taking single section between spaces. In general this could be solved by having different placeholder which would return output without spaces instead of trying to make entire specialized command working with one. Closing this one as I dont think its worth remaking entire specialized system to accept spaces. We could consider adding placeholder tho.

**Comment by CloudeLecaw** [comment]
a placeholder that prints out the name without spaces would also be a nice option so specialy checks for right name could be done :)
