### ISSUE TITLE
/ cmi importfrom does not save

### ISSUE THREAD

**Issue by Blueeyestar** [Zrips/CMI#739]
if I make warp with /cmi importfrom essentials or home .. everything is loaded but after a reboot of the server everything is deleted again should that be so?

**Comment by mercurialmusic** [comment]
Asking this only because I also derped it once, did a restart right after importing and things didn't save, which obviously it needs a little time to save things. But are you waiting a decent amount of time before restarting or just doing a restart straight away? The more you're importing the longer it will probably need to get it sorted.

**Comment by Blueeyestar** [comment]
I go to the server which runs for a few hours.
then I enter the import command. Then everyone is loaded.
And all are available. At the next server restart in x hours, all are gone. So all over again

**Comment by LogGits** [comment]
This should be resolved in the latest builds, if not please let me know.
