### ISSUE TITLE
[Request] Automatically save inventory of player when /clear is used

### ISSUE THREAD

**Issue by EmilHeilbo** [Zrips/CMI#744]
It would be nice if the plugin automatically saved a players inventory when /clear is used, as to mitigate potential damage from /clear being used by mistake.

**Comment by arturek1666** [comment]
That's why I wanted to have option to add confirmation to the /clear so you don't accidently remove items. xD

**Comment by LoneWolfEthan** [comment]
Having that option would be nice as well. I used /clear because I wanted to clear dropped items (and that's what I thought /clear did, I admit that's my own fault) and accidentally cleared more than 50 hours of playtime's worth of items, most of which I don't recall because I had just been stripmining for a few hours...

**Comment by CloudeLecaw** [comment]
/clear is vanilla is Clearing inventory ;) same to cmi clear.
/cmi clearground is for Ground Clearing

you also could drop an item unwanted and do /cmi groundclear or while a user is next to you that  
droped an item of higher worth,,, then ist also theadmins fault :3

so try to be carefull with /clear and also with cmis clear :3

**Comment by LogGits** [comment]
@Zrips Maybe with this, you could add a new event for this. InventoryClearEvent, whereby users can utilise the eventcommands yml file to run commands before or after the inventory is cleared.
