### ISSUE TITLE
Home ACLS

### ISSUE THREAD

**Issue by delbertina** [Zrips/CMI#756]
It would be a cool feature if players could set access control lists for their homes. Toggle between whitelist and blacklist and ability add players onto the list. Along with that, config options to set default setup for new users.

Used a plugin similar to [this one](https://dev.bukkit.org/projects/myhome) a few years ago, and would be cool to have similar functionality in CMI. :)

**Comment by CloudeLecaw** [comment]
it does not make sense to give Access to others homes
You have the /homes whereu can teleport to each home
and if you want an other Player came to you he can use the tpa if u gave Access to it
after that he can set his own home.

if he is owner of a Region (ProtectionPlugin) then he can give Access to allow other sethome or not or use /home at his reagion and also can deny teleporting to his Region if he set it up.

So why you should set others to your home`? Thats not the sense of Home to say "hey pls port to my home and get some stuff quickly".... no..

Admins allways can teleport to others homes normaly if u gave the permission.

**Comment by sgrayme** [comment]
I'm among those who would appreciate if CMI added home invites/whitelists.

I'm going to end up converting another plugin's home database (plugin no longer maintained and is blocking server upgrade) to CMI and it would be nice if I could include home invites in the conversion, as they frequently are part of social activity on my server. /tpa might seem similar enough, but it isn't the same (in fact, /tpa and such are restricted to staff on my server). If I have to work around a lack of home whitelists, the workaround will go against the "flavor" of the server and create a lot of inconvenience for members.

**Comment by sgrayme** [comment]
It's already been emphasized here, different servers may be configured differently. Mine falls under this.

Different world teleport options have specific functions.

Teleport itself (/tp) is an instant teleport, and does not exist past the owner logging off.
Warps are server-established points that are either accessible to everyone or a specific set of permission groups, no reliance on being invited.
Homes are personal "warps" which may or may not require invite and last as long as the creator desires.

Maintaining these distinctions allows providing clearer information about these forms of world transportation and more granular control about what a player can and can't do. For instance, I may wish to allow warps from certain areas but not homes.

While people can and frequently do use one home as a moving point, homes are primarily used for [mostly] static locations. Such as public player-built farms, separated/expansive land claims, and mining areas.

The "problems" stated about homes can be spoken of for using teleports and are actually among the reasons for not allowing teleports to all players. I've played and managed servers that allow tpa and tpahere and I saw far more tp abuse than home abuse. At the very least, a lot of harassment (demanding tp, spamming command as much as possible, trying to interfere with legit requests) and at the worse, trying to cover cheating or other bad behavior. On my server where homes are the only user-created teleportation (and limited), homes are only rarely abused.

Maybe it's because I'm talking about a server that's primarily PvE, has land claims, and allows "griefing" unclaimed land or maybe it's just the quality of people on the server (probably the latter, because they are pretty cool). Either way, I shared my usage case because it does exist and is relevant to this feature request. Which, this is a feature request related to something that exists in CMI. People can already make homes and allow anyone to visit them. What we're asking for, is giving our members a choice between nobody and everybody.

If you think homes should only be private, then set your server so only private homes can be made. 
If you think homes are duplicate functionality and should be removed as bloat, make your own ticket for that specific topic.

**Comment by CloudeLecaw** [comment]
im not convinced that homes should be used as private teleporter for all/Friends - who ever^^ for me a Home is just a fixed private Points that works like a teleporation. the diffence to a warp is that the Player can set/delet this teleportpoints by itself like he want.. But thats not what this thread should be for.


What would be ok for me is a config Option:
privateHomes / shareredHomes
if shared - the Player share them with all (not with just single players)
if private - they are private like it is currently.

**Comment by Zrips** [comment]
Just some reminder for everyone that you have 2 options when creating home, one is to create "public" home location and another is private one **/cmi sethome [homeName] -p** which will prevent players teleportation to this home even tho they have permission to teleport to another player home locations.

**Comment by delbertina** [comment]
To clarify, was the issue closed because this feature idea is not something you wish to add to the plugin? Not trying to flame, just confused. : )
