### ISSUE TITLE
Using minecraft:give instead of CMI's give for kit commands causes 1 extra item to be given out .

### ISSUE THREAD

**Issue by Corcustos** [Zrips/CMI#7810]
### Description of Issue

Title. Issue does not happen if kit is given via command. Reproduced on fresh config.yml, settings, and saves with only cmi, cmilib, vault, and luckperms installed. When running the command from kit, console says only 1 item was given but 2 appear in the player's inventory. If command is set to give 2, it will give 3. Always +1 extra.

### Version Information

```shell
CMI: 9.5.0.8 SqLite
CMILib: 1.2.5.3 
Server: Spigot 1.16.5-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled 
Modules -> 57 enabled 1 disabled: votifier
```

### Errors

```shell
Nothing in console/logs.
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Can you provide actual example of kit you have tested with?

**Comment by Corcustos** [comment]
> Can you provide actual example of kit you have tested with?

It currently happens with any kit I add a command to, even kits made from scratch with no other settings touched. Here is my [kits.yml](https://pastebin.com/AHGLhePD) that I'm able to reproduce 100% of the time with. It's just the default kits.yml with a test kit added.

**Comment by Zrips** [comment]
That one extra item looks weird, if this command was doubled then it would give double the amount, its a correct format for minecart vanilla and CMI give commands, so no error there. 
Could you test this one with completely fresh server, just to rule out any issues with server setup itself?

**Comment by Corcustos** [comment]
> That one extra item looks weird, if this command was doubled then it would give double the amount, its a correct format for minecart vanilla and CMI give commands, so no error there. Could you test this one with completely fresh server, just to rule out any issues with server setup itself?

It is already completely fresh with a newly built spigot jar using build tools. CMI is also stock. Only thing I've done is add luckperms, vault, and the test kit.

**Comment by Zrips** [comment]
Ok, issue looks to be rooted in 1.16.5 server version, for some reason when using minecraft:give command there is PlayerDropItemEvent, and this issue only happens when you have custom GUI open which prevents you from dropping items while its open, so event gets canceled yet player still receives item from canceled event and from that give command. 
At this point can't say I know work around to fix this issue as its none issue with later versions as it was fixed and give command is been handled more properly now. 
Suggestion would be to simply use CMI give command as it supports same item formats and will not cause this issue for you on older servers. Closing ticket for now.
