### ISSUE TITLE
java.lang.NoSuchFieldException: activeContainer

### ISSUE THREAD

**Issue by Dusten9752** [Zrips/CMI#7993]
### Description of Issue

When editing anything in GUIs this error floods console lagging the server.

### Version Information

```shell
--------------------------------------------------
CMI: 9.6.1.3 SqLite
CMILib: 1.4.0.1 
Server: Magma 1.16.5-R0.1-SNAPSHOT
CMI economy: Disabled CMI Chat: Disabled 
Modules -> 57 enabled 1 disabled: votifier
--------------------------------------------------
```

### Errors

```shell
https://paste.sparked.host/axekamohef
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
I can prevent those error messages being spammed, but there is little I can do with GUI misbehaving due to wild differences in how modded servers handle such things. CMI doesn't support modded servers officially, what works that works, everything else is either hard to fix or simply reasonably not possible. 
With next CMILib update error should disappear.
