### ISSUE TITLE
folia support

### ISSUE THREAD

**Issue by imfusheng** [Zrips/CMI#8018]
I want to use CMI on the folia server. Will this plugin provide support? If so, when will it be updated?

**Comment by Zrips** [comment]
There was initial update for CMILib to support Folia. Due to how wildly differently it handles some actions, CMI will need some more serious work on for it to work properly and not fail. Hard to say exact time line here, but it is planned as quite other plugins of mine got support for Folia, tho not officially yet.

**Comment by Captainpax** [comment]
update one this?
