### ISSUE TITLE
Restart Loop - Circular plugin loading detected!

### ISSUE THREAD

**Issue by BerndPixel** [Zrips/CMI#8041]
### Description of Issue

After update to the new CMI version, the server is in a restart loop 

### Version Information

```shell
9.6.2.3
```

### Errors

```shell
https://pastebin.com/rxWKji82
```

### Relevant Plugins

CMILib - V1.4.0.3, BentoBox - 1.24.0, Multiverse Core - 4.3.9

### Agreements

- [x] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by MC-MrBirdy** [comment]
> [22:33:10] [Server thread/ERROR]: [SimpleProviderStorage] Circular load order:
> [22:33:10] [Server thread/ERROR]: [SimpleProviderStorage]   Multiverse-Core -> BentoBox -> Citizens -> CMI -> Multiverse-Core
> [22:33:10] [Server thread/ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.

Seems the console is telling you to report it to Multiverse-Core or join the PaperMC discord for further help.
I can not confirm to having the same issue and am using: 
- CMI 9.6.2.4
- CMILib 1.4.1.0
- Multiverse-Core 4.3.9

**Comment by Zrips** [comment]
Its... Complicated. Its no related to latest CMI version as we had soft dependency for Multiverse-Core for ages by now, it can be caused by Multiverse-Core or BentoBox or Citizens adding dependency of the other plugin which created this loop of dependencies, even tho its a soft dependency and never was an issue or even is one on Spigot type servers. Will remove soft dependency for Multiverse-Core which is silly as it makes entire sof dependency broken thing, but well, it should not cause issues, might only show few extra messages reporting about missing worlds which will get loaded in on later time.
