### ISSUE TITLE
Placeholders for cmi glow doesn't work

### ISSUE THREAD

**Issue by NoltoxGit** [Zrips/CMI#8155]
### Description of Issue

Hello,
While trying to create a menu with glow checks, I just noticed that the following two placeholders return nothing:
- `%cmi_user_glow_name%`
- `%cmi_user_glow_code%`

But I've already activated my glow. You can see my video below which illustrates the bug..

https://github.com/Zrips/CMI/assets/75265787/a495690d-c211-418c-8508-a6d6b840e532

### Version Information

```shell
CMI: 9.6.5.1 SqLite
CMILib: 1.4.2.0
Server: Purpur 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI(CMIEInjector) CMI Chat: Enabled
Modules -> 26 enabled 33 disabled: spawnerProximity, cuffed, mirror, tablist, armorEffects, moneyCheque, skin, elytraBoost, rideAnimation, elytraLaunch, bossBarCompass, chatBubble, playerCombat, votifier, headDrop, spawnerCharge, vanish, namePlates, timedCommands, hpBossBar, launchPad, elytraExploit, anvilRenameColor, jail, spawners, flightCharge, deathMessages, disabledEnchants, worldLimitsElytra, ranks, sitAnimation, warmup, totemBehaviorr
```

### Relevant Plugins

Vault 1.7.3-CMI & PlaceholderAPI 2.11.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Will be fixed with next update for %cmi_user_glow_name%, for some reason it was still set to return translatebale color code and not plain name of it. Just keep in mind that %cmi_user_glow_code% returns actual color code and it will not show up as it will be translated, so adding extra text at the end helps out to see if it gets parsed correctly, something like /papi parse Zrips %cmi_user_glow_code%Color
