### ISSUE TITLE
Advancements (toast) messages are still not being reset

### ISSUE THREAD

**Issue by neokyle** [Zrips/CMI#8202]
### Description of Issue

Toast messages are not resetting, upon server start the first toast message to occur is repeated in place of any other toast message that is sent. 

### Version Information

```shell
CMI: 9.6.7.2 MySQL
CMILib: 1.4.2.2 
Server: PufferfishPlus 1.20.1-R0.1-SNAPSHOT
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
Modules -> 48 enabled 11 disabled: spawnerProximity, flightCharge, cuffed, tablist, votifier, shulkerBackpack, anvilRenameColor, jail, spawners, spawnerCharge, totemBehavior
```

### Errors

```shell
None
```

### Relevant Config Sections

```yaml
N/A
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Tested with regular pufferfish server, looks to be working correctly. Can't test PufferfishPlus as its paid version. I would suggest to test it out with free version so that we would know that its an issue with paid one. Alternatively you could update to 1.20.2 server version which should utilize different method for toast messages which should fix your issue.
