### ISSUE TITLE
[Bug] - Banlist is Ranklist

### ISSUE THREAD

**Issue by CloudeLecaw** [Zrips/CMI#830]
/cmi banlist
you get this....

![image](https://user-images.githubusercontent.com/12080017/45601297-4a5fd080-ba0b-11e8-9f89-350554e15aeb.png)

![image](https://user-images.githubusercontent.com/12080017/45601400-8cd5dd00-ba0c-11e8-9edd-a7a6c448ca8f.png)

**Comment by Zrips** [comment]
Actually... Its not a bug. As strange as it looks like. We do have command detection algorythim which will pick closest match if none is found by given command. So in this case, we dont really have /banlist command, but we do have /ranklist which is quite similar and was picked and shown instead of original. Will add extra message informing about misspell to avoid confusion in future.
