### ISSUE TITLE
Using the plugin on different servers

### ISSUE THREAD

**Issue by kainlighty** [Zrips/CMI#8367]
Can I use your plugin on a local server, I know that licensing is prohibited on SpigotMc in terms of bans, but I still want to know, will there be nothing?

**Comment by CloudeLecaw** [comment]
you should take a look on the wiki.:)

the fqa sais yes you can with one license. it only must be all yours servers.

**Comment by kainlighty** [comment]
There are some examples about a friend, but I found the answer that suits me, but I still didn't understand)) 

I am a technical administrator on the project, the owner bought a plugin, I want to transfer the plugin to a local server so that there is a server build for tests. Does this situation allow the transfer and launch of the plugin? **Yes/No?**

Just for run the test server and test other plugins with it (or put Essentials he-he).

**Comment by CloudeLecaw** [comment]
> There are some examples about a friend, but I found the answer that suits me, but I still didn't understand))
> 
> I am a technical administrator on the project, the owner bought a plugin, I want to transfer the plugin to a local server so that there is a server build for tests. Does this situation allow the transfer and launch of the plugin? **Yes/No?**
> 
> Just for run the test server and test other plugins with it (or put Essentials he-he).

if your the Administrator and an other one is the owner of the license of cmi, you just need to ask if he allows you to run his license on your local copy.
if he aggees you can use it. you just are not allowed to use it if you plane to run an own online server with it. dont forget to copy the cmi folder to you local testserver too, because you will need his lisence that is located in the cmi main folder.

i hope this answers your question. :-)

**Comment by kainlighty** [comment]
I understand that it is not prescribed, but I always try to find out if I can use plugin without VDS server))

After all, if something happens, I will be guilty..
