### ISSUE TITLE
support folia.jar

### ISSUE THREAD

**Issue by pinuxio** [Zrips/CMI#8524]
good morning everyone, I wanted to know if you have plans to adapt cmi to folia? new paper fork

**Comment by Zrips** [comment]
Folia is currently in heavy development and isn't made to be used on live servers, so would not rush to switch to something like that any time soon. That said, CMI is a big plugin with quite few things which needs special handling change due to how Folia fundamentally changes some of the things. It's in the to-do list and some areas are being updated to support folia servers, but full support can take some time

**Comment by bobhenl** [comment]
As the folia seems to be more and more popular even supported by the most plugins already, would be great if CMI can slowly starting support it

**Comment by Zrips** [comment]
Initial supported version will come out with next update. Tho, this is ONLY as initial update and quite some work still needs to be done on it for it to work properly. It will load on Folia server and most things will work, but you will see error messages here and there until it gets fully addressed. Folia is extremely picky now and quite few things need to be specifically remade to fit Folia requirements and how it processes data

**Comment by pinuxio** [comment]
great job, no errors except for

[ServerMain/ERROR]: [DirectoryProviderSource] Error loading plugin: Could not load plugin 'CMIEInjector v1.0.2.3' as it is not marked as

**Comment by Zrips** [comment]
You can get new version here
[https://www.zrips.net/wp-content/uploads/2024/03/CMIEInjector1.0.2.4.jar](https://www.zrips.net/wp-content/uploads/2024/03/CMIEInjector1.0.2.4.jar)

**Comment by Zrips** [comment]
Closing this ticket for now. When you encounter issues relating to Folia, it will mention region/global/tick threads in error message, just let me know by making a ticket about it.
