### ISSUE TITLE
Can you disable bans in cmi?

### ISSUE THREAD

**Issue by CzechSmazakOnTop** [Zrips/CMI#8977]
So im using another plugin and i need to disable bans in cmi i searched the config but nothing.

**Comment by Zrips** [comment]
There are no config option because its entirely based on your ban related commands, removing access to ban commands will essentially disable ban handling. Other than this we have option to enable/disable custom ban feedback messages in config file which will be shown to the player who is banned and was denied entry to the server due to that.
