### ISSUE TITLE
Player heads dropping to victim inventory

### ISSUE THREAD

**Issue by BirminghamBoy** [Zrips/CMI#9059]
### Description of Issue

When a player is killed and their head dropped via CMI, the head goes straight into the victim's inventory upon respawn rather than dropping for the killer to pick up.

Mentioned this in the Discord multiple times with no response, so I assume this is a CMI-end bug. 

### Version Information

```shell
[Thu 11:54:06 INFO ] --------------------------------------------------
  [Thu 11:54:06 INFO ] CMI: 9.7.5.0 SqLite-> 9.7.5.3
  [Thu 11:54:06 INFO ] CMILib: 1.5.1.0
  [Thu 11:54:06 INFO ] Server: Paper(13) 1.21.1-R0.1-SNAPSHOT+
  [Thu 11:54:06 INFO ] CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Enabled 
  [Thu 11:54:06 INFO ] Modules -> 55 enabled 11 disabled: spawnerProximity, flightCharge, hpBossBar, tablist, playerCombat, votifier, holograms, spawners, spawnerCharge, namePlates, bossBarCompass
  [Thu 11:54:06 INFO ] --------------------------------------------------
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
By the code CMI will drop head at the spot victim died, it's not placing items directly into inventory, if it does then you might have different plugin handling this behavior and not CMI in particular. Will add small delay for ability to pickup item when its dropped, in case player managed to grab that item before he fully died. If issue persists with next update, let me know. Tho could not reproduce your issue on my test setup, so not 100% sure that it was caused by CMI, but this change will be a good addition in any case.
