### ISSUE TITLE
Same issue as before: Kits are on permanent cooldown even after updating

### ISSUE THREAD

**Issue by cookieclicker21** [Zrips/CMI#9077]
### Description of Issue

I posted about the bug previously, the kits just being on a permanent cooldown and not being able to be used by anyone besides the operators, i updated to the most recent version of CMI 9.7.5.4 and the issue still is present unfortunately, any help would be appreciated

### Version Information

```shell
CMI: 9.7.5.4
```

### Errors

```shell
None
```

### Relevant Plugins

CMI: 9.7.5.4

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by mercurialmusic** [comment]
I have NOT tested this and we don't use the cooldown, but I wonder if it has ever worked correctly for you the way you're expecting or if this is a recent development? 

I ask because ages ago we ran into the problem where any usage set on the kits was global. We expected that all players could use the kit X times, but instead only the people who got to it first could use it. That is, if we had a one time use kit, only one person could use it at all and no one else. Because of that, we simply don't use the feature since it doesn't make sense for us, so we use other methods. 

A slightly more detailed description of what your expectations are, what you've tried, when this started happening, etc. might be useful to help troubleshoot what's going on.

**Comment by cookieclicker21** [comment]
The kits are not useable by anyone other then operators, the cooldown shows no matter who it is and the cooldown does NOT go down and is just stuck , i have had this issue for a bit even before i updated to 9.7.5.4, its set as one time use and different kits have different cooldowns, even if i set to 2 or more uses the issue is still there, so far as i have used the kits they haven’t worked as i wanted them to

**Comment by Zrips** [comment]
@cookieclicker21 
Can you check database for actual kit records of when each of them got used? And check current server time with something like `/cmi servertime` as something wonky is going on here. 
And as you mentioned that no one else has access to kits except operators, how do you give kits to the players?
