### ISSUE TITLE
more elevator names = no elevators.

### ISSUE THREAD

**Issue by BlackRandomCraft** [Zrips/CMI#9113]
### Description of Issue

when more names for elevators are specified, all elevators stop working at all
<details>
  <summary>screenshots</summary>

![image](https://github.com/user-attachments/assets/f1fe0127-6472-4fc4-be53-a08ff1c02003)

![image](https://github.com/user-attachments/assets/e9236776-5e30-4657-9a4a-675fe17260bf)

![image](https://github.com/user-attachments/assets/09113ef3-5eb6-47d6-a6ea-81ec2a36be8d)
</details>

### Version Information

```shell
--------------------------------------------------
CMI: 9.7.5.8 MySQL-> 9.7.5.9
CMILib: 1.5.1.3 
Server: Paper(2233) 1.20.6-R0.1-SNAPSHOT-
CMI economy: Enabled Vault: 1.7.3-CMI CMI Chat: Disabled 
Modules -> 64 enabled 2 disabled: tablist, votifier
--------------------------------------------------
```

### Relevant Config Sections

```yaml
Optimizations:
  ElevatorIndicator:
  - '[CMIElevator]'
  - '[Elevator]'
  - '[Лифт]'
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Well yes, because at the moment elevator name is being recognized only as a single one and not as a list. I would suggest to always avoid creating lists if original value wasn't in a list format, as those needs different handling on code side and in most cases will cause it to not work.
Will make few changes to allow multiple elevator titles with next version.
