### ISSUE TITLE
CMI Vanish issues

### ISSUE THREAD

**Issue by Ste3et** [Zrips/CMI#9143]
### Description of Issue

There are two issues present on my server with CMI Vanish:

- Vanished Players get still MSG's and the vanishedit option `Private Message` will be ignored
- Vanished Players still play TeleportEffects then `hidewhenvanished` is defined in the preset.

### Version Information

```shell
Paper: 1.21.1 @b483da4
CMI Version: 9.7.6.1
CMILib: 1.5.1.3
```

### Relevant Config Sections

```yaml
TpUp: circle;c:200,50,210;twist;part:5;r:0.5;pitch:90;move:0,0.33,0;offset:0,-0.2,0;target:[playerName];hwv
TpDown: circle;c:150,50,10;part:5;r:0.5;pitch:90;move:0,-0.33,0;offset:0,2.2,0;hwv;target:[playerName]
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by Zrips** [comment]
Preset is only a preset, those are default values when player never modified it with vanishedit, after first modification we will be using players selected options and ignore default values even if you change them later. So just double check if this option is actually enabled/disabled for the player with /vanishedit
Teleport effects showing up on teleport will be fixed with next update
