### ISSUE TITLE
cmi error with citizen

### ISSUE THREAD

**Issue by crismanx1** [Zrips/CMI#9157]
### Description of Issue

does not understand the corresponding commands with npc only with blocks or armor stan

### Version Information

```shell
cmi version : 9.7.5.9
cmi lib : 1.5.1.3
```

### Agreements

- [X] My server is supported by CMI.
- [X] My version of CMI at the time of this report is up to date.
- [X] I have searched the github and asked around before making this report.

**Comment by CloudeLecaw** [comment]
#9156

**Comment by Zrips** [comment]
@crismanx1 
There was an issue with specialized commands, specifically click types, not being recognized properly when interacted with entities. This will be fixed with next update. If you had different issue, then please double check that records of interactiveCommands and Citizens plugin for recorded NPC id's and UUID being same. Closing ticket for now.
