### ISSUE TITLE
more placeholders for parsing someone's else values

### ISSUE THREAD

**Issue by TheIVYT** [Zrips/CMI#9239]
Please add more placeholders as %cmi_p_[playerName]_display_name%. There is only one placeholder, that can parse only other player's displayname

**Comment by mrfloris** [comment]
Specialized commands ptarget and bperm can both help in a lot or situations, there's also a PAPI ecloud called parseOthers which can help you a lot.

**Comment by TheIVYT** [comment]
ParseOther doesn't work with offline players, what %cmi_p_[playerName]_display_name% does. I need to use those placeholders in other plugin, not in command/chat

**Comment by mrfloris** [comment]
Oooh good point.

**Comment by Zrips** [comment]
@TheIVYT 
What type of placeholders are we talking about here specifically? Because I can't just enable parsing of placeholders for everyone we have as it could cause issues and performance drops if its misused and people would misuse it. I can enable some placeholders for cached data we have on offline players, would avoid doing that on offline players to get things like their inventory contents or anything related to loading their actual data file to grab needed information.

**Comment by TheIVYT** [comment]
Here are some placeholders, that I want to see:
1. reverse of %cmi_p_[playerName]_display_name%, something like %cmi_p_[playerDisplayName]_name% that returns original offline player's name by his display one. If player has no displayname - returns the original one.
2. %cmi_p_[playerName]_cuffed%
3. %cmi_p_[playerName]_banned%
4. %cmi_p_[playerName]_muted%
5. %cmi_p_[playerName]_jailed% | %cmi_p_[playerName]_jailreason% | %cmi_p_[playerName]_jailname% | %cmi_p_[playerName]_jailtime%
6. %cmi_p_[playerName]_god%
7. %cmi_p_[playerName]_online% (idk what it is for if %cmi_user_online% only works through /cmi placeholders parse)

**Comment by Zrips** [comment]
Will add listed placeholders, except the first one, as we are not tracking players by their display name which can be way different from any records, include color codes, prefixes and so on, which on itself could dynamically change. So you should always use players actual name, well, nickname would work too for %cmi_p_[playerName]_display_name%
