### ISSUE TITLE
Flight and Gamemode Issue

### ISSUE THREAD

**Issue by Getblock** [Zrips/CMI#940]
**Description of issue or feature request:**

Fly always gets disabled on relogging in even with safefly login permission. Gamemode always changes to survival whenever we change world or relogging in.

**Cmi Version (using`/cmi version`):**  8.0.19.0

**Server Type (Spigot/Paperspigot/etc):**  Spigot

**Server Version (using `/ver`):**   git-Paper-273 MC:1.13.1

**Relevant plugins (Delete if this isn't needed):**  Multiverse core 2.6

**Comment by CloudeLecaw** [comment]
using multiverse or pwi?

Well then look in ist configs ;)
Alsogive yourself the Bypass permissions from cmi - beeing op is not allways enough

**Comment by kikelkik** [comment]
I am having the same issue.

**Multiverse worlds.yml:** 
`
worlds:
  t_Creative:
    ==: MVWorld
    hidden: 'false'
    alias: t_Creative
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: HARD
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: CREATIVE
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: -1497.0
      y: 55.0
      z: 1055.0
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '1234567'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
  t_weltn:
    ==: MVWorld
    hidden: 'false'
    alias: t_weltn
    color: WHITE
    style: NORMAL
    pvp: 'true'
    scale: '1.0'
    respawnWorld: ''
    allowWeather: 'true'
    difficulty: HARD
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
      monsters:
        ==: MVSpawnSubSettings
        spawn: 'true'
        spawnrate: '-1'
        exceptions: []
    entryfee:
      ==: MVEntryFee
      amount: '0.0'
    hunger: 'true'
    autoHeal: 'true'
    adjustSpawn: 'true'
    portalForm: ALL
    gameMode: SURVIVAL
    keepSpawnInMemory: 'true'
    spawnLocation:
      ==: MVSpawnLocation
      x: 3.5
      y: 62.0
      z: 255.5
      pitch: 0.0
      yaw: 0.0
    autoLoad: 'true'
    bedRespawn: 'true'
    worldBlacklist: []
    environment: NORMAL
    seed: '3145593'
    generator: 'null'
    playerLimit: '-1'
    allowFlight: 'true'
`

**PerWorldInventory (PWI) config.yml:**

`
# Set the level of debug messages shown by PWI.
# INFO: Print general messages
# FINE: Print more detailed messages about what the plugin is doing
# DEBUG: Print detailed messages about everything
logging-level: 'INFO'
# If true, the server will change player's gamemodes when entering a world
# The gamemode set is configured in the worlds.yml file
manage-gamemodes: false
# If true, players will have different inventories for each gamemode
separate-gamemode-inventories: true
# If true, any worlds that are not in the worlds.yml configuration file will share the same inventory
share-if-unconfigured: true
# True if PWI should set the respawn world when a player dies
manage-death-respawn: false
# Attempt to figure out which world a player last logged off in
# and save/load the correct data if that world is different.
# REQUIRES MC 1.9.2 OR NEWER
load-data-on-join: true
# Disables bypass regardless of permission
# Defaults to false
disable-bypass: false
# Set the duration in minutes for player profile information to be cached
cache-duration: 10
# Set the maximum number of player profiles that can be cached at any given time
cache-maximum-limit: 1000
# Disables the nagging message when a world is created on the fly
# Intended for users who know what their doing, and don't need to have worlds configured
disable-nag-message: false
metrics:
    # Choose whether or not to enable metrics sending.
    # See https://bstats.org/getting-started for details.
    enable: false
    # Send the number of configured groups.
    # No group names will be sent!
    send-number-of-groups: true
    # Send the total number of worlds on the server.
    send-number-of-worlds: true
# All settings for players are here:
player:
    # Save and load players' economy balances. Requires Vault!
    economy: false
    # Load players' ender chests
    ender-chest: true
    # Load players' inventory
    inventory: true
    # All options for player stats are here:
    stats:
        # Load if a player is able to fly
        can-fly: true
        # Load the player's display name
        display-name: false
        # Load a player's exhaustion level
        exhaustion: true
        # Load how much exp a player has
        exp: true
        # Load a player's hunger level
        food: true
        # Load if a player is flying
        flying: true
        # Load how much health a player has
        health: true
        # Load what level the player is
        level: true
        # Load all the potion effects of the player
        potion-effects: true
        # Load the saturation level of the player
        saturation: true
        # Load a player's fall distance
        fall-distance: true
        # Load the fire ticks a player has
        fire-ticks: true
        # Load the maximum amount of air a player can have
        max-air: true
        # Load the current remaining air a player has
        remaining-air: true
`

**PWI worlds.yml:**

`groups:
  default:
    worlds:
    - t_weltn
    default-gamemode: SURVIVAL
  creative:
    worlds:
    - t_Creative
    default-gamemode: CREATIVE
`

**CMI config.yml WorldLimits:**

`WorldLimits:
  # By setting to true fly and gamemode limitations per world will be aplied for player on world change if they dont have appropiate permission node
  Enabled: true
  # World list with default game modes
  # If player will have cmi.worldlimit.gamemode.bypass permission node, game mode wont be changed
  # Posible modes: creative, survival, adventure, spectator, 
  Gamemode:
  - t_weltn:Survival
  - t_Creative:Creative
  # If player will have cmi.worldlimit.fly.bypass permission node, fly mode wont be changed
  Fly:
  - t_weltn:False
  - t_Creative:True
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoof: true
  # When set to false, only players with cmi.worldlimit.fly.aboveroof can fly above world build limit
  FlyAboveRoofLimitations:
  - t_weltn-256
  - t_Creative-256
  # If player will have cmi.worldlimit.god.bypass permission node, fly mode wont be changed
  GodMode:
  - t_weltn:False
  # Prevents particular entity spawn reasons in defined worlds. All posible reasons: NATURAL, JOCKEY, CHUNK_GEN, SPAWNER, EGG, SPAWNER_EGG, LIGHTNING, BUILD_SNOWMAN, BUILD_IRONGOLEM, BUILD_WITHER, VILLAGE_DEFENSE, VILLAGE_INVASION, BREEDING, SLIME_SPLIT, REINFORCEMENTS, NETHER_PORTAL, DISPENSE_EGG, INFECTION, CURED, OCELOT_BABY, SILVERFISH_BLOCK, MOUNT, TRAP, ENDER_PEARL, SHOULDER_ENTITY, DROWNED, SHEARED, CUSTOM, DEFAULT
  SpawnReasons:
    t_weltn:
    - None
    t_Creative:
    - None
`

The permission **cmi.worldlimit.fly.bypass** ist set to true.


When I used Essentials before instead of CMI, it worked all well, so I don't think that the settings for WorldLimits is neccessary at all. But testing it with WorldLimits.enabled: false has got the same effect of resetting the player to flymode false. 

Its the same matter if I just change the gamemode from survival (with fly enabled) to creative and back to survival: You gonna fall down with fly disabled. So CMI seems not to respect wether a player's flymode is set to true.

**Comment by BiGUNMAN** [comment]
Same, this has existed for way too long and needs to get patched.

**Comment by Zrips** [comment]
Things like this one should be tested without any other plugin as its usually caused by another plugin disabling fly mode or changing game mode entirely after CMI processes player state.
