### ISSUE TITLE
Bug: Incorrect Enderchest Permissions Referenced

### ISSUE THREAD

**Issue by digitalcrowd** [Zrips/CMI#95]
Opening enderchest from invsee, results in this permission being fired: cmi.invedit, vs cmi.command.ender.others which should be correct.

**Comment by Zrips** [comment]
Should be fixed with next build

**Comment by MCTyler** [comment]
Wait...so I will need to change my Permissions for Invedit cause of this suggestion? I want my Mods to be able to see all of a players Items with invsee/invedit.

**Comment by CloudeLecaw** [comment]
/cmi inv <player>
- permissions:
cmi.command - needed to execute cmi commands
cmi.command.inv - allows to see Players inventory
cmi.command.inv.others - allows to see others Players inventory
cmi.invedit - Grants option to edit inventory

/cmi ender <player>
- permissions:
cmi.command - needed to execute cmi commands
cmi.command.ender - allows to see Players enderchest
cmi.command.ender.others - allows to see others Players enderchest
cmi.enderedit - Grants option to edit enderchest

clicking on the enderchest in the GUI Need the same permissions like when you would have
the ender commands permissions, but currently it fires cmi.invedit even if ist no editing.
cmi.command.ender and cmi.command.ender.others shouldbe fired (asked for),
also sometimes in the enderchest, cmi.invedit was/is fired instead of cmi.enderedit
and this is will be fixed in next versions .

Note:
i never got why it is cmi.enderedit and cmi.invedit.
These two permisisons ruin (are leaving) the permisisonstructure CMI created...more sens to fill in this structure would be cmi.command.ender.edit and cmi.command.inv.edit

**Comment by Zrips** [comment]
MCTyler
It will not change anything, it simply will not require cmi.invedit to click on ender chest button or teleport button to perform action. No in general, you will not see any changes

**Comment by Zrips** [comment]
CloudeLecaw
CMI was originally made as simple inventory editor, like way way back. And those permissions are from time when there was no specific structure for permissions. I will have to change them at some point to be more consistent with others.
