### ISSUE TITLE
ArmorStand editor PlotSquared compatibility

### ISSUE THREAD

**Issue by Rukes** [Zrips/CMI#968]
Players with permission to edit armorstands are able to edit armorstand on other player's plots. Would be nice to fix

**Comment by Zrips** [comment]
Armorstand interaction checks 2 things before allowing armor editing: 1. PlayerInteractAtEntityEvent which is generic interaction with entity, if that is allowed, then moving further.
2. PlayerArmorStandManipulateEvent generic armor stand manipulation event, if that one is allowed, then player should be allowed to change armorstand contents. 
And which version of minecraft are you running where this issue is existing?

**Comment by LogGits** [comment]
Basically for this to work as you like @Rukes you need PlotSquared to cancel `PlayerInteractAtEntityEvent` or `PlayerArmorStandManipulateEvent` (ideally the first one). Try making a compatibility request on their issue tracker asking them to cancel the PlayerInteractAtEntityEvent for players who don't have access to a plot.
