### ISSUE TITLE
Fix please "Last seen..." infinite log

### ISSUE THREAD

**Issue by Yhenko** [Zrips/CMI#994]
Hi, how can I fix this? with the command, the server crashes

https://i.gyazo.com/e99f35078ee0ecbec23e1e54dbafe64b.mp4 

CMI Version: 8.0.19.0
Spigot 1.12.2 (Latest)

Im using MySQL.

**Comment by Melowelei** [comment]
Hello @Yhenko,
You have this message because you have duplicated player (same username, but different UUID), this is probably caused because you changed the status of your server (Cracked/Premium).
You can fix this by using the command `/cmi removeuser [UUID]`, after doing this, you will no more see this spam on your console.

**Comment by Yhenko** [comment]
> Hello @Yhenko,
> You have this message because you have duplicated player (same username, but different UUID), this is probably caused because you changed the status of your server (Cracked/Premium).
> You can fix this by using the command `/cmi removeuser [UUID]`, after doing this, you will no more see this spam on your console.

Yes, i know, but there are more than 6000 duplicated players, the command crash the server...

**Comment by LogGits** [comment]
I think there is also a `/cmi removeuser duplicate` or `/cmi removeuser duplicates` (can't remember which one).

**Comment by Yhenko** [comment]
Some help? please :(

**Comment by Zrips** [comment]
With next update will limit output to max of 25 entries. Tho duplicates should no longer appear with previous update after cleaning up database with appropriate command.
